### ISSUE TITLE
Flüssigkeiten lassen sich nicht aus Tanks nehmen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#1]
Ich konnte kein Lava mit einem Eimer aus einem Potable Tank oder aus dem Tinker Seared Tank nehmen.

**Comment by krakel** [comment]
das scheint jetzt behoben zu sein, habe es mit Lava getestet

**Comment by combak** [comment]
Funktioniert mit Bucket und Clay Bucket aus dem Portable Tank aber nur mit dem Bucket aus dem Smeltery Tank. (Oli)

**Comment by DerOliDE** [comment]
Ich habe mal bei anderen Packs geguckt, dort funktioniert das auch nicht mit dem Clay Bucket die Lava aus dem Smeltery Tank zu bekommen, daher schließe ich das hier mal als "Feature statt Bug" ab.
