### ISSUE TITLE
kleiner Guide für den Anfang

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#10]
Ich schreibe mal in loser Reihenfolge auf, was man so alles beachten muß. Vielleicht kann man daraus Tips für den Anfang machen.
- die Welt ist böse, erwarte überall Mobs; beim Fällen der Bäume, beim Graben, aus der Luft
- der Aufenthalt in der Nähe von Lava ist gefährlich
- das Graben nach Erzen ist sinnlos, da sind keine (nur einzelne für spezielle Mods)
- schnell Licht und Behausung bauen
- fliegen können ist hier ein absolutes Muss
- da sind Dungeons unter den Inseln, die beinhalten möglichen guten Loot
- diverse Mobs droppen wichtige Items

**Comment by krakel** [comment]
Nether 
- der ist absolute gefährlich, dahin zu gehen ohne gute Rüstung und Waffen ist definitiv tötlich
- ist es dunkel, ohne Nachtsicht geht da garnichts

**Comment by krakel** [comment]
AgriCraft 
- das Unkraut ist übel, man sollte beim Züchten Barrieren zwischen den Feldern machen

**Comment by krakel** [comment]
Ars Magica
- ersten Skillpunkte mit bedacht vergeben
- /amuicfg - allows you to fine tune the graphic user interface
- /respec [player] - presumably converts your spent skill points to unspent skill points.
- /setmagiclevel [player] [number(max 99)] - sets your level to the desired one
- /giveskillpoint [amount_blue] [amount_green] [amount_red] [player]
- /takeskillpoint [amount_blue] [amount_green] [amount_red] [player]

**Comment by combak** [comment]
Sehr gut da ist unser HQM Autor. Viel Spaß Grayal :) G.

**Comment by DerOliDE** [comment]
Ich verlinke das hier mal zum Questbuch Beitrag (https://github.com/combak/ShatteredWorld/issues/71) und mache das hier zwecks Übersicht dicht.
