### ISSUE TITLE
Forstday Refill Workbench

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#101]
Wenn man in die Workbench mehrere Holzblöcke reinlegt werden die nocheinander über die einzelnen Arbeitsschritte beareitet. So weit so gut. Nach dem ersten Duchlauf übernimmt er alle Teile wieder in den Eingangsslot, aber, ein Teil wird wieder nach unten zurück gelegt. Warum auch immer. Dadurch wird der nächste Arbeitsschritt blockiert, weil der Ausgabeslot blockiert ist.

**Comment by DerOliDE** [comment]
Wurde gefixt.
