### ISSUE TITLE
TConstruct Smeltery "realistischer" 

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#102]
Ich würde gerne etwas in den Melting Rezepten der Tinkers Construct Smeltery arbeiten. Hintergrund ist, dass hier 1. mehr Realismus mit rein kommt und 2. auch etwas mehr Anspruch. Dazu hier 2 Beispiele:
- Schmelztemperatur Cobalt liegt real bei 1495°C

Ich würde hier folgende Materialien auf höhere Schmelztemperaturen setzen:
- Redstone
- Cobalt
- Ardite
- Manyullyn
- Alumite
- Obsidian 
- ...

Diese sollen dann in der Schmelze nur mit Pyrotheum schmelzbar sein. Nennen wir es mal Tier 2 Schmelze. Vergleicht mal im Internet die Tabellen bezüglich der Schmelzpunkte mit denen bei uns. Man muss nur beim Anpassen aufpassen, dass man nicht irgendwo einen Showstopper mit einbaut. Z.B. schmilzt Eisen bei ca 1200°C.

**Comment by DerOliDE** [comment]
Gerne, da müssen wir nur schauen das wir uns keinen gamebreaker produzieren.

**Comment by BakermanLP** [comment]
Weise den mal mir zu

**Comment by BakermanLP** [comment]
Kann ich die Smeltery Scripts in Github als aktuell nehmen? Dann kannst du erst mal nicht an den Flüssigkeiten arbeiten. Sollte aber in 1-2 Stunden als erster Entwurf fertig sein.

**Comment by krakel** [comment]
Wieso nutzt ihr dazu nicht den Steelofen. Der hat auch Temperatur:

**Comment by DerOliDE** [comment]
Aktuelle ja, nur die Passagen mit den Custom Fluids wurden wegen dem CustomItems Problem auskommentiert.

**Comment by BakermanLP** [comment]
Die genannten Materialien dienen normalerweise dazu, um Legierungen herzustellen und das geht nur in der normalen Smeltery.

**Comment by BakermanLP** [comment]
Das Ändern von Cobalt Ardite usw gestaltet sich schwer, da zu viele Produkte in der Schmelze geschmolzen werden können ( ca. 38 Items z.B. für Cobalt ).

**Comment by krakel** [comment]
Es wäre auch sehr hilfreich, wenn man wüßte welches Material welche Hitze erzeugt. Im INet habe ich dazu nichts gefunden. Kennt jemand irgend eine Quelle?

**Comment by krakel** [comment]
Sehe gerade das es nur Lava und Pyrotheum geben soll.

**Comment by BakermanLP** [comment]
Könnte man als Quest mit einbauen. Alternativ ein Buch wie in Agrarian
Skies 2

Uwe Dörl notifications@github.com schrieb am Mo., 13. Juli 2015 12:09:

**Comment by DerOliDE** [comment]
Das könnte man erstmal in die Wiki eintragen oder wenns mehr Arbeit sein 
soll, dann via MineTweaker als Tooltipp an alle Flüssigkeiten dranklatschen.

Am 13.07.2015 um 11:56 schrieb Uwe Dörl:

**Comment by DerOliDE** [comment]
Vorschlag Tooltip an Fluid Block und Bucket:
![smeltery-temperature](https://cloud.githubusercontent.com/assets/5699429/8654524/1642999a-298b-11e5-99e1-cde63fe37288.png)

**Comment by BakermanLP** [comment]
Oh, sehr schön.

**Comment by DerOliDE** [comment]
So Tooltip an die Flüssigkeiten geklatscht aber habe noch das Problem, das Fuel Gas nicht funktioniert sobald ich folgende Zeile einkommentiere:
https://github.com/combak/ShatteredWorld/blob/master/scripts/TinkersConstruct.zs#L375

Behauptet er das er bcadditions:fuelgasBlock nicht finden kann.

**Comment by DerOliDE** [comment]
Fehlt hier noch irgendwas oder wurde hier schon alles erledigt?

**Comment by BakermanLP** [comment]
Kannste vorerst schliessen IMHO.
