### ISSUE TITLE
Sekundäre Produkte aus dem Pulverizer und der Sagmill entfernen

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#103]
Wie wäre es, die Sekundären Produkte im Pulverizer und in der Sagmill zu entfernen beim Vorgang ...

Cobble -> Sand -> Dust 

Vorteile:
- Erleichterter Aufbau
- weniger Pipes / Itemducts und dadurch weniger Serverlast

Damit wäre dann auch ein Endausbau wie folgt möglich (weniger Maschinen):

**Comment by Grambosch** [comment]
Bei dem Punkt komm ich nicht ganz mit, die Nebenprodukte nutzen doch denselben Ausgang wie die Primären (TE ist da ja auch konfigurierbar) , wenn ich also die item conduits/itemducts etc mit FIltern versehe an den EInganssieben tut sich an der Anzahl der Conduits/itemducts nicht , oder übersehe ich etwas?

**Comment by BakermanLP** [comment]
Bei der "Dreierreihe" für das Sieve mit Dust kommen aus jedem Pulverizer / SagMill Nebenprodukte raus. Wenn man vom Endausbau (6x Pulverizer für Gravel Sand und Dust ausgeht, müssen Nebenprodukte zusätzlich abgeführt werden, da diese nicht in den nächsten Pulverizer wandern dürfen.

Aufbau mit Nebenprodukten:
![aufbau3](https://cloud.githubusercontent.com/assets/3873443/8252710/98b359f2-1688-11e5-9b69-a3a431017a65.jpg)

Aufbau ohne Nebenprodukten:
![aufbau4](https://cloud.githubusercontent.com/assets/3873443/8252716/a11fa79e-1688-11e5-8f9c-6798aa3fb5fa.jpg)

**Comment by krakel** [comment]
Soweit ich weiß darf man in diesem Modpack nur eine beschränket Anzahl von bestimmten Maschienen einsetzen. Weiß jetzt nicht ob das für Pulverizer auch gilt.
Hier mal ein Aufbau mit nur 3 davon:
[Imgur](https://i.imgur.com/V2WMwcl.jpg)

**Comment by BakermanLP** [comment]
Der Fairness halber sei auch folgender Aufbau erwähnt, der auch funktioniert, aber in dem Fall zwingend Ducts benötigt. Zusätzlich dazu können der erste und zweite Pulverizer verstopfen, da die Sekundären Produkte unter Umständen nicht ausgegeben werden können. Ja, man könnte dann noch Void Upgrades reinsetzen. Zur Info: der Pulverizer links ist mit 2 Speed Upgrades, der Mittlere mit einem Upgrade versehen.

![aufbau5](https://cloud.githubusercontent.com/assets/3873443/8253174/76df2554-168d-11e5-85f8-c9bdc7b1d7e1.jpg)

**Comment by BakermanLP** [comment]
Einen habe ich noch vergessen zu sagen, wenn man in obigem Aufbau die Drawers weglässt, dann passiert folgendes:
![aufbau6](https://cloud.githubusercontent.com/assets/3873443/8253376/78bbef4a-168f-11e5-80aa-942a58231aa7.jpg)

Herumliegende Items, ist das normal, das die Pulverizer die Sachen, die sie nicht weg kriegen, einfach auf den Boden werfen (, oder auch die Itemducts?)

**Comment by DerOliDE** [comment]
Das sind die Itemducts wenn sie kein Servo/Retriever als "Buffer" haben, da wird dann auch versucht Material durch die Leitung in eine Maschine zu jagen, wenn diese bereits voll ist.

**Comment by krakel** [comment]
Du brauchst nur eine Leitung, wenn du an den Sieves Filter einsetzt und alles aus den Pulverisern in eine Leitung gibst. Durch die Filter bekommt jeder was er braucht und es werden auch keine Items gedroppt. Ein verstopfen ist allerdings wohl noch möglich.
Aber haben wir nicht andere Probleme, als ein paar Kabel weniger.

**Comment by BakermanLP** [comment]
Betrachten wir das mal als nicht zu realisieren und "closen" das mal
