### ISSUE TITLE
Thaumcraft Nodes

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#104]
Ich weiß nicht woran es liegt aber in unserer Welt sind die Nodes , außer den Objektgebundenen (Obsitiles etc), komplett unter den Inseln, Das ist natürlich kontraproduktiv und müßte irgendwie gefixed werden wenn das Dauerzustrand ist

**Comment by DerOliDE** [comment]
Hast Du eine Höhe als Beispiel?

**Comment by Grambosch** [comment]
Bedrockhöhe würd ich mal behaupten alles unter 10, scheint in der Generierung irgendwo nicht vorgesehen zu sein das wir SKy DImensions haben

**Comment by Grambosch** [comment]
Als temporäre Lösung geb ich erstmal platzierbare Nodes aus

**Comment by DerOliDE** [comment]
Wenn es dafür keine Lösung gibt könnten wir die später auch über ein Händler verkaufen.

**Comment by Grambosch** [comment]
Händler/HQM Belohnungen (aber die sollten schon recht teuer/selten sein

**Comment by Grambosch** [comment]
Wink für Grayal: Questbelohnungen weit hinten in Reihen die keiner machen will ..

**Comment by krakel** [comment]
Ich wollte eigentlich die Nodes da lassen wo sie sind. Ist halt eine weiter Herausforderung sich auf Level 0 zu begeben und nach diesen Nodes zu suchen. Wenn ich sehe wie andere in dieser Höhe sogar ihre Gräber wieder finden, ist das ja schon fast zu leicht.

**Comment by Grambosch** [comment]
Vertrau mir einfach mal und mach 5-10  rein als Questbelohnung. Das ist nicht viel und gerade genug um ein wenig Zauberei zu betreiben mit den Stäben und noch nicht genug um ne ordentliche Powered Node zu machen. Gräber geht ja auch nur weil die einen Block unter sich generieren und die Nodes werden beim Umzug meist beschädigt das die auch weniger liefern bis( hin zum ausbrennen geht das)

**Comment by DerOliDE** [comment]
Sind die Nodes noch ein Problem oder kann der Issue geschlossen werden?

**Comment by krakel** [comment]
Es sind 10 Aura Nodes im Questbuch verteilt und man bekommt am Anfang vom Thaumcraft Queststrang eine Node in a Jar mit je 10 Essenzen.
Du kannst alle Loots aus dem Questbuch als Überblick in der ShatteredWorld_reward.txt nachsehen.
Kann somit geschlossen werden.
