### ISSUE TITLE
SagMill nimmt die Rezepte aus ExNihilo aus der Core Config nicht

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#105]
EnderIO SagMill nimmt die Rezepte aus der Datei SAGMillRecipes_Core.xml für die ExNihilo Produkte nicht.

**Comment by DerOliDE** [comment]
Die *Core.xml kann nicht verändert werden, die geänderten Rezepte müssen in die *User.xml

**Comment by BakermanLP** [comment]
Ist klar, aber die stehen bereits drinnen in der Core und die funktionieren nicht. Auch ein kopieren der bereits bestehenden Rezepte aus der Core in die User funktionieren nicht.  Ich wollte die Rezepte gleich dem Pulverizer machen. Im Moment sind die Rezepte genauso wie der Hammer

**Comment by BakermanLP** [comment]
Es gibt dazu einen Issue SleepyTrousers/EnderIO#1962 , wobei es sich um eine Abhängigkeit handelt. Im Moment werden die Rezepte nicht verwendet, da die Mods in der falschen Reihenfolge geladen werden. Das müssen wir im Auge behalten, da sonst die SagMill zu einem Hammer Ersatz werden kann.

**Comment by DerOliDE** [comment]
Nochmal verifizieren, ob das noch aktuell ist.

**Comment by Grambosch** [comment]
Sag Mill nimmt keine Ore Sands Gravel an

**Comment by Grambosch** [comment]
Kann man hier noch was tun? Oder liegt das außerhalb unserer Macht?

**Comment by DerOliDE** [comment]
Neuere Version nachdem der Issue bei EnderIO geschlossen wird gibt es nur als beta, die möchte ich nur ungern verwenden. 

Betroffen sind hiervon ja scheinbar nur die Ex Nihilo Erze also imho weniger dramatisch.
