### ISSUE TITLE
ExNihilo Alu Gravel Sand und Dust in Pulverizer bearbeiten

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#106]
Warum soll der das nicht können? Kann ja auch alle anderen Gravel, Sand und Dust Arten aus ExNihilo

**Comment by DerOliDE** [comment]
Dann hätte der Ex Astris Automatic Hammer überhaupt keine Daseinsberechtigung mehr außerdem brauchen wir den "Flaschenhals" bei der Rohstofferzeugung. 

Ich würde wie in einem anderen Issue erwähnt das Limit des Hammers auf 3 pro Spieler hochsetzen (Gravel, Sand & Dust) aber den Pulverizer würde ich nicht noch mit ins Boot holen.

**Comment by BakermanLP** [comment]
Zur Erklärung, im Moment ist die Sagmill per Core config so eingestellt, dass sie wie der Hammer funktionieren würde. Tut sie zwar nicht, aber sie würde. Ich möchte die Sagmill genauso wie den pulverizer einstellen, da für mich beide Geräte das gleiche können sollten

**Comment by DerOliDE** [comment]
Dann würde ich es eher noch in der SAGMill, das ganze Erzzeug habe ich z.Z. eh paussiert wegen der TE & ModTweaker Problematik.

Hier habe ich auch schon den Kram in eine Tabelle gestopft:https://docs.google.com/spreadsheets/d/1zKIdorqNQWiwt_Z4_e7-si2ZeNc7_XbQRXWofXEgvRw/edit#gid=0

**Comment by BakermanLP** [comment]
Das wurde getestet mit modtweaker-1.7.10-2-0.8.3.jar

**Comment by BakermanLP** [comment]
Kann man nun schliessen.
