### ISSUE TITLE
andere Heat Sources für Cruicible

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#108]
Ich weiß, das andere Heat Quellen deaktiviert wurden. Da aber die Anzahl der Cruicible limitiert sind, sollte diese Sperren wieder entferrnt werden. So hat man einen kleinen Spielraum in der Lava Produktion. So extrem ist der Vorteil dann auch nicht.

**Comment by DerOliDE** [comment]
Ich biete max. 2 fach nach Schwierigkeit sortiert:
- Lava = 1,3 fach
- Netherrack + Fire = 1,6 fach
- Thaumcraft Nitor = 2 fach

**Comment by krakel** [comment]
Das wäre doch schon was.

**Comment by Grambosch** [comment]
Dreh Nitor und Netherrack bitte , Nitor muss man ja erstmal einiges drum machen

**Comment by DerOliDE** [comment]
Okay, war mir da nicht so sicher, weil Nether böse und so. ;-)

**Comment by DerOliDE** [comment]
- Lava = 1.33
- Fire = 1.66
- Nitor = 2.0
