### ISSUE TITLE
Destabilized Redstone

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#109]
Es gibt einen wichtigen Unterschied, den man im Auge beahlten sollte.
Ein Redstone bringt:
- Magma Crucible 100mB Destabilized Redstone
- Tinker Schmelze 144mB Destabilized Redstone

Der Wert aus Thermal Expansion war schon immer so. Der Wert aus Tinker muß so sein, damit 9 Redstone einen Block ergeben, wie es bei Metallen ist.
Folgendes Problem: 
Um Molten Signalum herzustellen braucht man 144mB Silver, 432 mB Copper und 1000mB Destabilized Redstone. Das Destabilized Redstone kann man in der Schmelze aber nur mit 7 Redstone herstellen. Dabei bleiben aber am Ende 8mB übrig, was äußerst blöd ist. 
Kann man da was machen?

**Comment by DerOliDE** [comment]
Nur ein Copy n' Paste Fehler, muss hier angepasst werden:
https://github.com/combak/ShatteredWorld/blob/master/scripts/TinkersConstruct.zs#L257-L262

**Comment by DerOliDE** [comment]
Verhältnis gefixt.
