### ISSUE TITLE
Barley kann nicht in Flour gewandelt werden

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#111]
Barley konnte doch früher wie Wheat behandelt werden und zur Herstellung von Dough benutzt werden. Das geht nicht mehr. Nur noch der klassische Weg zu Brot, der ja demnächst korrigiert wird.
3 Barley => 1 Brot
1 Barley => 1 Barley Flour

**Comment by Grambosch** [comment]
Das kommt sobald ich irgendeine Möglichkeit habe die "Pussy" Variante für Brot (Mehl backen) korrekt rausnehmen kann siehe https://github.com/combak/ShatteredWorld/issues/82

**Comment by DerOliDE** [comment]
Ich mache den Issue mal zu sehe Ref : https://github.com/combak/ShatteredWorld/issues/82
