### ISSUE TITLE
Pam's Market ist "overpowered"

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#112]
Ich mach einfach dazu mal ein Issue auf, damit wir das nicht vergessen.

**Comment by DerOliDE** [comment]
Sollte meiner Meinung nach auch deaktiviert werden und wie von Hellamie vorgeschlagen mit NPCs via Ruf Händler gelöst werden.

**Comment by DerOliDE** [comment]
Market wird deaktiviert, wenn es eine bessere Lösung als die NPCs gibt können wir ihn wieder aktivieren.
