### ISSUE TITLE
Probleme mit dem Server

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#114]
Ich weiß nicht wie ich es genauer beschreiben sollte im Titel oder ob es von Relevanz für den Hauptserverbetrieb ist der ja dann kommen soll , aber wenn der Server "allein" vor sich hinrechnet
geht er in den Performancemode (der aber im Nitradointerface abgeschaltet ist) und beim aufwecken bricht die Serververbindung ganz ab und ich krieg erstma eine Server wird gestartet Meldung
Das ganze dauert dann ein paar Minuten und dann geht das verbinden wieder ganz normal

**Comment by Grambosch** [comment]
Laut Serverauskunft startet der tatsächlich neu

**Comment by DJPTiger** [comment]
Grambosch da hängt mit dem Absturtz von mir zusammen weil seid dem ist das.

**Comment by Grambosch** [comment]
Nope das war schon öfter so

**Comment by DerOliDE** [comment]
Können später ja mal den Sampler drauf schmeißen und gucken was der so ausspuckt.

**Comment by BakermanLP** [comment]
Welche Ausstattung hat der Server?

Oliver notifications@github.com schrieb am Di., 23. Juni 2015 14:57:

**Comment by DerOliDE** [comment]
@BakermanLP Es ist ein Nitrado Server mit 6GB, was da für Hardware dahinter steckt weiß ich allerdings nicht.

**Comment by BakermanLP** [comment]
Meine Erfahrungen mit nitrado sind durchwachsen. Trotz genug Speicher hatte
ich bei manchen Packs Performance Probleme. Dazu kommt noch eine schlechte
bis nicht funktionierende Konsole. Eventuell kann ich von meinem virtuellen
Server genug freiräumen.

Oliver notifications@github.com schrieb am Do., 25. Juni 2015 17:25:

**Comment by Grambosch** [comment]
Ist ja zZ kein Problem mit der Performance , läuft ja eigentlich alles, War halt eher ob da irgendwo im restart ein Problem ist das wir nicht gesehen haben bisher

**Comment by DerOliDE** [comment]
Ich mach hier auch mal dicht.
