### ISSUE TITLE
Charcoal

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#115]
Mir ist das mit dem Charcoal noch nicht ganz klar. Die Idee mit dem Köhlern ist ja ganz nett. Für die ersten Fackeln und Öfen ist das ja nicht schlecht. 
Wie habt ihr euch das gedacht? 
Für eine umfangreiche Erzproduktion reicht das aber nicht, wenn die auf Charcoal basiert. Davon brauch man eine ganze Menge. Wenn es da keine automatische Möglichkeit gibt, sehe ich schwarz.
Und ein bischen Technik soll ja wohl drin sein!

**Comment by Grambosch** [comment]
"Industrielle" Gewinnung von Holzkohle wäre dann ja über Retorten , aber lass erstmal Punkt 1 abschließen , die Köhler Sobald das funktioniert und verwertbar ist kann die Retorte ja in Angriff genommen werden

**Comment by DerOliDE** [comment]
Die industrielle Charcoal Herstellung wird ja scheinbar kein Einzug mehr in die Forest Mods erhalten, daher schließe ich diesen Issue und verweise auf https://github.com/combak/ShatteredWorld/issues/190
