### ISSUE TITLE
Crucible Heat Source Fire Problem

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#117]
Es wird zwar Melting Speed 1.66 angezeigt aber es passiert nichts.

**Comment by DerOliDE** [comment]
Interessanter Fehler, wenn man das Feuer neu ansteckt läuft es ein paar Sek. dann hört das schmelzen wieder auf.

**Comment by DerOliDE** [comment]
Cross-Ref: https://github.com/jaredlll08/ModTweaker2/issues/225

**Comment by DerOliDE** [comment]
Mit der aktuellsten Version gehen überhaupt keine Änderungen mehr.

**Comment by Zixxl** [comment]
ModTweaker2 0.9.2 wurde released, der Bug sollte behoben sein

**Comment by DerOliDE** [comment]
Danke für den schnellen fix, ich habe mir gerade die aktuelle Version 
runter geladen und teste es. :)

Am 13.08.2015 um 11:13 schrieb Zixxl:

**Comment by DerOliDE** [comment]
Läuft wieder rund.
