### ISSUE TITLE
Water Shards aus Ice

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#119]
Aus einem Ice bekommt man ein Water Shard und bis zu 6 Ice Shards. Aus 4 solchen Ice Shards macht man dan wieder ein Ice Block. Ein fast unendliche Geschichte. Habe aus einem Stack Ice Blocks bis jetzt 3 Stacks Water Shards gekommen. Und der Prozess läuft noch mit den letzten Ice Shards wärend ich das schreibe.

**Comment by Grambosch** [comment]
Ist bekannt aber danke für die Errinerung
