### ISSUE TITLE
das eingestellte Resource Pack wird nach dem Neustart deaktiviert

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#12]

**Comment by combak** [comment]
Die Fehler werden ja immer skurriler... (Oli)

**Comment by krakel** [comment]
Wenn ich die ResourceLoader-1.1.jar mal rausnehme wird das Resource Pack korrekt geladen.

**Comment by krakel** [comment]
http://minecraft.curseforge.com/mc-mods/226447-resource-loader
Der Mod Autor scheint wohl schon bescheid zu wissen.

**Comment by krakel** [comment]
Habe mal die  ResourceLoader-1.0.jar ausprobiert und funktioniert einwandfrei. So wie es aussieht hat die 1.1 nur dieses zusätzliche oresources Verzeichnis, welches wir nicht nutzen.

**Comment by DerOliDE** [comment]
Fixed in Version 0.5.1, dort wurde der Resource Loader auf 1.2 geupdated.
