### ISSUE TITLE
Generatoren

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#120]
Abgleich zwischen Baukosten und Nutzen

**Comment by DerOli82** [comment]
Magmatic Dynamo hat noch das Default Rezept.

**Comment by DerOliDE** [comment]
Wir wollten noch die Effizienz für den Adv. Generator verbessern, damit sich das Ganze als Multiblock lohnt. Findet sich jemand der mal dadrüber schauen mag?

**Comment by BakermanLP** [comment]
Ein einfacher Weg wäre die Werte für Fuel anzupassen (nach oben). Entweder man reduziert den Verbrauch oder / und erhöht die Energieausbeute. Aber auch das würde ich im Moment nicht machen, nachdem bdew hier die Essiciency Upgrades in Version 0.9.16 reingebracht hat:
https://bdew.net/generators/efficiency-upgrades/

**Comment by DerOliDE** [comment]
Der Adv. Generator soll sich halt als sehr teurer Multiblock (schau Dir mal die Rezepte an) von den anderen einzel Block Generatoren abheben und die lassen sich u.a. ja auch pimpen (Augments oder Capacitor), da wäre ein Efficiency Upgrade imho nicht unbedingt ein Argument dagegen.

P.S.: An der Lava sollte man allerdings nichts schrauben sonst gibt es wieder einen Selbstläufer mit dem Magma Crucible.

**Comment by BakermanLP** [comment]
Modversionen für den Test:
- bdlib-1.9.1.97-mc1.7.10.jar
- generators-0.9.17.102-mc1.7.10.jar

Testaufbau:
![generatoraufbau](https://cloud.githubusercontent.com/assets/3873443/9270682/e0154988-4273-11e5-91c1-35a1298e44ea.jpg)
- 8 Turbinen
- Gas Turbine Controller
- Flux Generator
- Fluid Intake Valve
- Resonant Energy Cell (leer)

Test jeweils mit 1 Bucket of fuel

Ergebnisse:
800RF/t 
0,50 mB/t
1.658.600 RF

Mit Fuel Air Mixer
800RF/t
0,40 mB/t
2.024.800 RF

Mit Fuel Air Mixer + Gas Mixer Compressor
800RF/t
0,30 mB/t
2.775.200 RF

Gold Plated Turbines
1200 RF/t
0,73 mB/t
1.650.000 RF

Enderium Plated Turbines
4000 RF/t
2,4 mB/t
1.652.000 RF

Enderium Plated Turbines + Fuel Air Mixer + Gas Mixer Compressor
4000 RF/t
1,4 mB/t
2.772.000 RF

Meine Meinung dazu ... sehr ausgewogen und süffig im Abgang :)
Die Werte passen auch zu den restlichen Werten anderer Mods, die ich hier der Vollständigkeit halber mit reinschreibe

Thermalexpansion Compression Dynamo:
4 Water + 1 Fuel Bucket

Ohne Augmentations:
80 RF/t
1.500.811 RF

Mit Fuel Efficency Level 3
80 RF/t
2.776.000 RF

Mit Power Output Level 3
640 RF/t
1.062.400 RF

Mit Fuel Efficency Level 2 + Power Output Level 1
160 RF/t
1.801.642 RF

Mit Fuel Efficency Level 2 + Power Output Level 2
320 RF/t
1.651.308 RF

Combustion Engine:
60 RF/t
1.500.000 RF

Bezüglich der Rezepte habe ich ein paar Kritikpunkte, die werde ich aber im Forum posten, da die hier thematisch nicht reinpassen

**Comment by DerOliDE** [comment]
Über die Effizienz könnte man streiten, wenn ich mir jetzt den Compression Dynamo mit max. Efficiency anschaue, dann ist der Gesamt Output im Endeffekt fast genau das was der Adv. Generator in der mit "Fuel Air Mixer + Gas Mixer Compressor" Variante Leistet, der einzige Unterschied ist die Dauer mit ~ Faktor 10.

Der Faktor Dauer lässt sich aber damit ausgleichen das ich einfach 10 Compression Dynamos nehme, dann hätte ich ein ähnlich großen Multiblock mit fast identischer Leistung.

**Comment by Nedelosk** [comment]
Habe mal das TE Script Problem beseitigt.
https://github.com/combak/ShatteredWorld/commit/bf3f12803339a739ee368aa876c5dd7828b3de6a
