### ISSUE TITLE
Food Groups erweitern

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#123]
- Pies ( eventuell getrennt nach süß und herzhaft )
- Cake ( selbes Spiel )
- Chocolate Bars 
- Fish
- Meeresfrüchte

**Comment by DerOliDE** [comment]
DJPTiger hat sich die Mühe gemacht alles essbare aufzulisten ( see: https://github.com/combak/ShatteredWorld/blob/master/docs/Food.ods ) daraus müsste man noch sinnvolle FoodGroup ableiten.

**Comment by hellamie** [comment]
https://www.dropbox.com/s/ybjt1gfxsm05ben/Food.ods?dl=0

Hier ist die Foodgroup Datei noch mal ich habe sie eben noch mal Durchgelesen und kleine Änderungen vorgenommen.

**Comment by DerOliDE** [comment]
Danke hab es ins Git übernommen.

**Comment by DerOliDE** [comment]
@hellamie Kleiner Tipp um die richtigen Namen für die Food Items zu bekommen:
Im Technic Launcher Ordner unter **../modpacks/shattered-world/config** die Datei **Waila.cfg** öffnen und den Eintrag **B:waila.cfg.metadata=false** auf **B:waila.cfg.metadata=true** setzen. Dann bekommst Du im Spiel wenn Du mit der Maus über das Item gehst den internen Namen der Items in grau angezeigt.

**Comment by DerOliDE** [comment]
War die falsche Config die Datei ist **neiintegration.cfg** und der Eintrag ist **B:"Internal Name"=true**. Dann sieht man den internen Namen beim Mouse over.

**Comment by hellamie** [comment]
habe Fertig

**Comment by DerOliDE** [comment]
Alles in die Config übernommen, einige Food Groups habe ich anders benannt und/oder zusammengefasst.
