### ISSUE TITLE
Tool Core von Buldcarft Additions kein Rezept

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#124]
Es kann natürlich sein, das man das auf anderem Weg lernen muß. Kenne mich mit dem Mod nicht aus.

**Comment by DerOliDE** [comment]
Soweit ich weiß betrifft das lernen nur die Benutzung der Gegenstände aber nicht die Herstellung. Ich hab jetzt aber kA was ein Tool Core ist oder machen soll. ^^

**Comment by krakel** [comment]
Ich habe ein Bugreport in Buildcraft Additional aufgemacht.
https://github.com/BCA-Team/Buildcraft-Additions/issues/446

**Comment by iTitus** [comment]
Theoretisch sollte das Rezept existieren. Habt ihr BuildCraft Compat und NEI installiert?

**Comment by iTitus** [comment]
![2015-08-19_23 08 15](https://cloud.githubusercontent.com/assets/5154317/9369073/46df3668-46c7-11e5-9d25-148509f2e21d.png)

**Comment by iTitus** [comment]
Allerdings ist BC 7.0.9 nicht aktuell, versucht mal Version 7.0.20

**Comment by DerOliDE** [comment]
Ich aktuallisiere heute mal die Version und teste es. NEI und BC  Compat sind bei uns auch mit drin.

**Comment by DerOliDE** [comment]
Ich habe alle BuildCraft Mods geupdatet und jetzt funktioniert es. Danke für die schnelle Hilfe.
