### ISSUE TITLE
wurde schon über Thaumic Energistics nachgedacht

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#125]
Wir haben Extra Cells. Warum eigentlich nicht Thaumic Energistics (Thaumcraft in AE2)?
Kann ntürlich sein, dass ihr das schon abgelehnt habt.

**Comment by DerOliDE** [comment]
Gab es da nicht Probleme zur Aktuallität zwischen Thaumic Energistics 
und AE2?

Am 29.06.2015 um 09:48 schrieb Uwe Dörl:

**Comment by Grambosch** [comment]
Wurde angedacht aber da war tatsächlich zu dem Zeitpunkt ein Kompatibilitätsproblem

**Comment by DerOliDE** [comment]
Ich schau mir das mal für 0.7.0 an.

**Comment by BakermanLP** [comment]
Die Kompatibilitätsprobleme sollten eigentlich kaum noch vorhanden sein. Das war eben am Anfang die Verwirrung mit den Applied Energistics Versionen und Thaumcraft. Sollte jetzt gehen (siehe AgrarianSkies2)
