### ISSUE TITLE
Einige Blöcke in EnderIO nicht gießbar

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#126]
Für folgende Blöcke in EnderIO fehlen Flüssigkeiten:
- Energetic Alloy Block
- Redstone Alloy Block
- Conductive Iron Block
- Dark Steel Block - wird gebraucht für Dark Steel Anvil und Dark Steel Grinder Coil Holder
- Soularium Block

Die anderen werden nicht gebraucht.

**Comment by DerOliDE** [comment]
Selbe Spiel ab in den Ore Processing Issue https://github.com/combak/ShatteredWorld/issues/61
