### ISSUE TITLE
EnderIO Photovoltaic Cell habt ihr übertieben

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#127]
Die Photovoltaic Cells aus Ender IO bestehen aus keinem Teil mehr das aus Ender IO Selbst ist.
- Photovoltaic Cell: Redstone Comp Chipset (Buildcraft), Deep Blue Pigmented Glass (Botany), Energized Silicon Chip (ProjectRed), Silicon Chip (ProjectRed), Power IO Module (Adv. Generator)
- Advanced Photovolaic Cell: Pulsating Chipset (Buildcraft), Flux Crystal (Redstone Arsenal), Hardened Lumium Glass (Thermal), Power IO Module (Adv. Generator)

Das muß doch nicht sein. Zum einen sind das meiner Meinung nach zu viele Fremdteile. Zum anderen gibt es in EnderIO auch einige netter Teile als Spaßbremsen wie Enticting Crystal und co.

**Comment by DerOliDE** [comment]
Entweder extrem teuer, ausschalten oder limitieren. Sonst haben wir wieder so Spezialisten die sich davon hunderte aufs Dach klatschen, weil gratis Strom.

**Comment by krakel** [comment]
Nicht ausschalten. Teuer genug ist es. Aber es sollte wenigstens ein Baustein drin sein, der aus dem ursprünglichen Mod kommt.

**Comment by Grambosch** [comment]
Angesichts dessen das EnderIO überall sonst vertreten ist in fast jedem Rezept seh ich da kein Problem , das Produkt ist ja noch aus dem Mod

**Comment by Grambosch** [comment]
Rezeptänderung aufgrund von "Problemen" mit Botany , wie gewünscht mit EnderIO Bauteil 
https://github.com/combak/ShatteredWorld/commit/3374146ed20b4c7be00b35025dd3e82b0a3c00f9
