### ISSUE TITLE
Dark Steel und Dark Steel Block doppelt in EnderIO und Forest Day

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#128]
Diese Item sind in beiden Mods definiert. Wenn wir keine Doubletten haben wollen, muß daran auch noch gearbeitet werden.

**Comment by DerOliDE** [comment]
Wandert in den Ore Processing Issue https://github.com/combak/ShatteredWorld/issues/61

Da könntest Du übrigens auch solche Dinge selbst reinschreiben. ;-)
