### ISSUE TITLE
Ex Nihilo/Astris Balancing (Oli)

### ISSUE THREAD

**Issue by combak** [combak/ShatteredWorld#13]
Menge an Material aus den Sieves anpassen.

Ex Astris Maschinen und Upgrades verteuern

**Comment by combak** [comment]
Strom fürs Autosieve anpassen etc G.

**Comment by krakel** [comment]
Der Crash beim Sieben von Sand entsteht durch die Einstellung in der Konfig von ExAstris. Dort sind einige Werte auf 0 gesetzt. Dadurch bekommt ExNigilo ein Problem.
Ich habe es ihm schon geschildert und hoffe auf eine schnelle Korrektur. Er hat diesen Fall nicht vorgesehen. Ich glaube ores, die nicht droppen sollen, sollten nicht in den Listen stehen. Eine Dropchance von 0 ist nicht vorgesehen.

**Comment by krakel** [comment]
Ex-Nihilo ist schon bei 1.38-34 seit 27.4. Vielleicht ist da der Sandbug schon gehoben.
http://www.curse.com/mc-mods/minecraft/221696-ex-nihilo#t1:other-downloads

**Comment by DerOliDE** [comment]
Es kommt eine Exception ( java.lang.IllegalArgumentException: n must be positive ) aber Sand lässt sich noch immer nicht sieben.

/Edit
Die Ausgaben lassen sich aber auch via ModTweaker entfernen.

**Comment by krakel** [comment]
Kannst du mir den Stacktrace mal auf Pastbin posten. So kann ich Code nachschauen, ob der Fix schon drin ist.

**Comment by krakel** [comment]
Habe mal mit Decompiler rein geschaut. Fix ist noch nicht drin.

**Comment by krakel** [comment]
es gibt eine neue Version Ex-Nihilo-1.38-35.jar

**Comment by DerOliDE** [comment]
In 0.5.3 kommt die Version 1.38-36 rein, damit ist das Resource = 0 Problem gelöst.

**Comment by DerOliDE** [comment]
Die Dropchance für Certus sollte noch etwas nach unten geregelt werden der Rest gefällt mir bis jetzt.

**Comment by BakermanLP** [comment]
Durch den Wegfall der Chunk Loader sollte hier eventuell noch etwas wieder nach oben korrigiert werden, aber das ist nur ein Vorschlag.

**Comment by DerOliDE** [comment]
Das einzige was bis jetzt nach unten reduziert wurde ist Draconium und 
das sollte imho rar bleiben.

Beim Testserver hatte ich bis dato auch noch keinen Chunk Loader und es 
kommt trotzdem einiges an Material zusammen, so wie es auch bei uns in 
Agrarian Skies 2 ohne Chunk Loader mehr als genug Material gibt.

Am 13.08.2015 um 10:26 schrieb BakermanLP:

**Comment by BakermanLP** [comment]
Nach sechs Stacks Crushed End Stone gar nichts? Sieht nach extrem wenig aus. In NEI wird mir die Wahrscheinlichkeit bei 0% angezeigt beim Sieben von Crushed End Stone. Eventuell macht der Mod da einen Rundungsfehler?

**Comment by DerOliDE** [comment]
Das ist ein Rundungsfehler, die Wahrscheinlichkeit ist aber extrem selten, dafür haben wir ja das End noch mit Hardcore Ender Expansion ausgeschmückt, damit es dort unbegrenzt Inseln gibt und man es sich dort holen muss/kann.

**Comment by krakel** [comment]
Ich habe da aber jede Menge raus bekommen. Habe meine Resultate doch in diesem Thread gepostet.
https://github.com/combak/ShatteredWorld/issues/137

**Comment by BakermanLP** [comment]
10000 EndStone zu 13 Draconic Dusts ist viel? OK, bei dem Bedarf danach in dem Mod wird das lustig :)

**Comment by krakel** [comment]
So war das aber gewollt und es entsprach genau der eingestellten Wahrscheinlichkeit. Außerdem sind noch 19 Ore beim Mineren reaus gekommene. Damit die Insel nicht in kürzester Zeit weg ist, wurde ja auch ein anerer End Mod eingesetzt. So ist für jeden genug Endstone da.
Ok. Viel ist relativ. Aber diese extremen Zahlen sollen das Endgame betonen.
