### ISSUE TITLE
Crossbow Limb Cast und Crossbow Bode Cast haben keine Mats

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#131]
Wollte mir gerade einen Crossbow machen. Diese beiden sind nicht über die Schmelze machbar. Kein Mats bei den Alumbrass Cast dran.

**Comment by krakel** [comment]
Bow Limb Cast ist auch leer.

**Comment by DerOliDE** [comment]
Kann sich da jemand drum kümmern der Ahnung von den Tinkers Waffen hat bzw. welche Materialien dafür sinnvoll sind?

**Comment by BakermanLP** [comment]
Ich mache hier mal einen revolutionären Vorschlag ... alle Einträge in den restrictions.cfg löschen. Ist es nicht egal, aus welchen Materialien sich jemand seine Werkzeuge baut? 

Mit einer nicht vorhandenen restrictions.cfg Datei (wird ja neu erzeugt), funktioniert das nämlich wieder. 

Ich bin der Meinung, dass man zur Not, falls ein Material IMBA ist, dieses in der MaterialOverrides.cfg anzupassen. Kandidaten dafür wären Signalum und Lumium, das ich gleich setzen würde zu Manyullyn.

**Comment by DerOliDE** [comment]
Beim Werkzeug war das damals eine Realismus Entscheidung zu sagen Material x würde sich für Bauteil y eigenen.

**Comment by BakermanLP** [comment]
Wie gesagt, ohne die Restrictions.cfg geht es. Einen Fehler habe ich darin leider keinen gefunden. Ich sehe da eigentlich keine Nachteile, wenn man das weg lässt. Einfacher wird dadurch eigentlich nichts.

BTW: Das ist ein Duplikat von combak/ShatteredWorld#26

**Comment by krakel** [comment]
Ich würde den Wegfall begrüßen. Der Vorteil ist doch eher gering. Naja und Realismus in Minecraft?

**Comment by DerOliDE** [comment]
Das ist mein Kompromiss Angebot. Alles außer Bone, Cactus, Netherrack und Paper ist erlaubt.

**Comment by krakel** [comment]
Ein guter Kompromiss.

**Comment by BakermanLP** [comment]
Geht von meiner Seite aus in Ordnung.

**Comment by DerOliDE** [comment]
Dann ist das Thema erst einmal beendet.
