### ISSUE TITLE
System vergisst gesetzte Erze

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#132]
Ich habe schon eine ganze Weile zwei Redstone Ore Pflanzen am Laufen. Jetzt habe ich die 3. gesetzt und das System sagt mit 1 von 3. Zum Test habe ich noch ein 4. Ore gesetzt und es ging. Vielleicht ist da beim Restore was schief gelaufen.
Und habes es gerade getestet. Ich kann beliebig viele Iron Ore Blöcke setzen.

**Comment by DerOliDE** [comment]
Die Redstone Teile hast Du 100% gesetzt bevor die auf sie Liste gewandert sind (gibts erst seit 6.3), vergangenes setzen kann ich nicht erkennen und jetzt hast Du mit dem 3. +  4. die 2 von 3 gesetzt.

Iron Ore ist ein Fehler, weil ich versehentlich Iron Block auf die Liste gesetzt hab siehe /lr limits. Bitte vorher mal in die andern Issues gucken das wurde mit Sicherheit schon einmal hier erwähnt.
