### ISSUE TITLE
HQM Crash beim start des Servers (0.6.4a)

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#133]
Crash Report: http://pastebin.com/30s2qfX6

**Comment by krakel** [comment]
HQM überlebt aktuell die massiven Updates nicht. Man muß die hqm Datei einmal rausnehmen, den Server neu starten. Danach kann man sie wieder rein nehmen und der Server startet normal. Zumindest bei meinen Test zu Hause.

**Comment by DerOliDE** [comment]
Läuft jetzt wieder wie gewünscht.
