### ISSUE TITLE
Server im Nether sehr langsam

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#135]
Ich habe den Server im Nether ausgebremst.
Entweder war es das Aus- und Einloggen im Nether. Oder weil ich einen Skelettspawner in den Nether teleportiert habe und einmal Curse Earth drunter gestellt habe. Kann aktuell nicht einloggen (timeout).

**Comment by DerOliDE** [comment]
Ich machen neustart und stell mal auf peaceful

**Comment by krakel** [comment]
Bin direkt neben meinem Portal im Nether und kann nichts machen. Nach 10s fliege ich wieder mit Timeout raus. Alle meine Bewegungen sind auch sehr langsam. Vielleicht warte ich bis du nachher online bist.

**Comment by DerOliDE** [comment]
Ich war gerade online und bin rausgeflogen als Du online gekommen bist.

**Comment by krakel** [comment]
Ich denke mal, es ist das Curse Erath. Denn bis dahin war alles in Ordnung.

**Comment by DerOliDE** [comment]
Ich habe die Cursed Earth deaktiviert und den Server neugstartet.

**Comment by DerOliDE** [comment]
Nachdem Du Dich eingeloggt hast wird das Log hiermit zugespamt: http://pastebin.com/4VRRzsiA

**Comment by krakel** [comment]
Bin rein gekommen, kommte zwei Blöcke abbauen und zu meiner Fram laufen. Alle Bewegungen waren sehr langsam. Kann keine Schalter betätigen. Fliege trotzdem nach 10s raus.
Ich habe noch 4 Spikes stehen, ein paar Storage Drawer, 1 Vacuum Hopper. Vielleicht ist das zusammenspiel zwischen Spawner und Cursed Earth das Problem.

**Comment by krakel** [comment]
Der hier hat genau den gleichen Stacktrace. Nur verstehe ich dessen Lösung nicht.
https://github.com/rwtema/extrautilities/issues/470

**Comment by DerOliDE** [comment]
Mit Wrong Location kann ich nix im Log finden.

**Comment by krakel** [comment]
Sieht wohl wie ein defekter Chunk aus.
http://www.minecraftforum.net/forums/support/modded-client-support/2377560-crash-upon-loading-world

**Comment by krakel** [comment]
Ich vermute der Vacuum Hopper ist der Übeltäter, denn der hatte keine Items weiter geleitet. Vorher hatte ich die Skelette per Hand gekillt.

**Comment by DerOliDE** [comment]
Dann deaktiviere ich den auch mal und starte neu, wenn das nicht klappt wird der Nether resetet.

**Comment by krakel** [comment]
Ich bin aber im Nether, wie komme ich dann da raus?

**Comment by DerOliDE** [comment]
Ich teleportier Dich dann zu mir.

**Comment by krakel** [comment]
Ich konnte zwar alles abbauen, hat mich aber trotzdem raus geschmissen. Der Hopper war aber noch da.

**Comment by DerOliDE** [comment]
Welchen Hopper hast Du verwendet? Ich hab den von Open Blocks deaktiviert.

**Comment by krakel** [comment]
Den kleinen schwarzen, aus Hopper+Obsidian+Ender Eye. Hoffe der Name war richtig.

**Comment by DerOliDE** [comment]
Das ist der aus OpenBlocks, ich werde jetzt den Nether reseten sieh zu das Du erst nach mir einloggst nicht das Du in einer Wand stirbst.

**Comment by krakel** [comment]
Werde erstmal eine kleine Pause machen und mich später im TS melden.

**Comment by DerOliDE** [comment]
Okay

**Comment by krakel** [comment]
Exact der gleiche Aufbau mit Vacuum Hopper, Storage Drawer, Cursed Earth und teleportiertem Spawner funktionier ohne Probleme im SMP.

**Comment by krakel** [comment]
Aber jetzt. Habe mich kurz ausgeloggt und wollte mich wieder einloggen. Das geht jetzt nicht meht.

```
[10:04:36] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. 
During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.
This violates the general contract of java.lang.Object.hashCode().  
See bullet point two in that method's documentation. 
object #1 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 1069073138 hashCode= 138575871 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@1069073138{m:32767, i:net.minecraft.item.ItemBlock@1928304319, v:2114}; 
object #2 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 2064039564 hashCode= 138575871 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@2064039564{m:32767, i:net.minecraft.item.ItemBlock@1928304319, v:2114}
```

**Comment by krakel** [comment]
Habe eine Issue bei denen aufgemacht: https://github.com/CoFH/Feedback/issues/651

**Comment by DerOliDE** [comment]
Eigenartig wenn man bedenkt das die verwendeten Blöcke scheinbar überhaupt nix mit CoFH am Hut haben.

**Comment by krakel** [comment]
Ich denke aber das da was beim Ausloggen passiert. Den auf unserem Server haben wir ja einen anderen Fehler.
Wie lösche ich jetzt den defekten Nether bei mir? Welche Datei oder welches Verzeichnis muß ich löschen?

**Comment by DerOliDE** [comment]
Im World Verzeichniss den DIM-1 Ordner löschen

**Comment by krakel** [comment]
Aktuell ist der Stand folgender. Wenn ich mich mit diesem Aufbau aus dem Nether auslogge, wird das Spiel nicht korrekt geschlossen. Erst ein kompletter Restart löst das Problem und ich kann mich wieder normal einloggen, auch mit dem ganzen Aufbau im Nether.

**Comment by krakel** [comment]
Ich verstehe es nicht. Habe in der alten Welt alle Blöcke abgebaut, trotzdem das Problem mit dem relogg. Habe eine neue Welt erstellt. Alle Blöcke aufgestellt, auch einen Skelett Spawner teleportiert. Keine Probleme. Kann Aus- und Einloggen.

**Comment by krakel** [comment]
Interessanter Post von KingLemming auf mein Issue!

**Comment by krakel** [comment]
Gammel gerade so auf dem Server rum und werde aller 20min so aus dem Spiel geworfen. Der Server ist dann kurz weg. Sieht wie ein schneller Neustart aus. Kann aber auch an Nitrado liegen.

**Comment by Grambosch** [comment]
Steht da allen Ernstes das Cofh absichtlich MC abschießt weil die kein Modtweaker wollen oder hab ich noch nen Sonnenstich?

**Comment by krakel** [comment]
Das hast du wirklich missverstanden. Meine Vermutung, das CofH ein Problem verursacht, war falsch. Weil die alte Javainstance noch nicht beendet war, trat dieser Fehler auf.
Er meinte nur das dieses seltsame Verhalten allgemein bekannt ist. Das Modtweaker selbst das verursacht. So habe ich das zumindest verstanden.
Was machen wir jetzt?

**Comment by krakel** [comment]
Schade das ich heute nicht zur richtigen Zeit online war. Es muß doch jemand geben, der sich mit dem Problem mit Modtweaker auskennen. Vielleicht machen wir irgenwo was falsch.

**Comment by krakel** [comment]
Ich habe noch ein Post gefunden von dem Autor von Modtweaker selbst, indem er gewisse Probleme mit Rezepten berichtet, die zwischen gespeichert werden. Sehr blöd die Sache.
https://www.reddit.com/r/feedthebeast/comments/3acdqc/psa_never_use_mt_reload_or_anything_of_the_like/?sort=old
Ein User berichtet da auch von Problem mit Dimensionen und logout

```
A slight note to go on top of this: MT automatically reloads when closing out of a world 
and then entering one, so you should also be relaunching your client whenever you 
disconnect from a server or singleplayer world. It also does it when you switch texture 
pack from within a world.
```

Und das wird von einem Modtweaker Entwickler beantwortet

```
This is going to be fixed in an upcoming version, 
where it will only reload if actually needed.
```

Das deckt sich auch mit der editierten Antwort von KingLemming

```
This might be related to the fact that you say it wasn't completely unloaded. 
In which case, the Modtweaker script is running again and causing it.
```

**Comment by DerOliDE** [comment]
Also abwarten und Tee trinken.

**Comment by krakel** [comment]
Ich habe nochmal etwas experimentiert und dabei wirklich einen Konflikt zwischen Modtweaker und Thermal Expansion festgestellt. Wenn ich die Scripte ThermalExpansion.zs und ThermalFoundation.zs raus nehme, habe ich keine Probleme beim reloggen im Nether. Mit bekomme ich Exception von cofh.thermalexpansion.util.crafting.SmelterManager.refreshRecipes. Dieser Refresh der Rezepte zerstört das Zusammenspiel. 
Interessant dabei ist, das ich immer die falsche Dimension dim 1 gelöscht habe. Das ist nicht der Nether, sondern das End. Der Dimensions Reparatur Mechanismus scheint da irgend was zu korrigieren. Wir sollten in Zukunft immer die dim -42 (Deep Dark) nehmen, da diese Dimension sowieso nicht genutzt werden soll.
Deshalb sollten wir, um weiter testen zu können, diese Scripte erst einmal wieder raus nehmen und den Nether nochmal zurück setzen.

**Comment by DerOliDE** [comment]
Das Deep Dark ist deaktiviert und sollte auch nicht mehr erzeugt werden 
wenn es gelöscht wird, das ist keine Option aber eventuell eine 
Dimension via Multiworld.

Vielleicht sollten wir dann wirklich warten bis CoFH für Thermal 
Expansion sein eigene Custom Recipes Schnittstelle fertig hat bevor wir 
da noch mehr Energie in ModTweaker Rezepte reininvestieren.

Am 08.07.2015 um 08:45 schrieb Uwe Dörl:

**Comment by krakel** [comment]
Ich sehe nur in meinen lokalen Saves das da auch ein Verzeichnis für dim -42 angelegt wird. Deshalb habe ich dieses nutzloses Verzeichnis zum Löschen vorgeschlagen.

Aktuell kann man nicht sauben testen, da nach ca. 20min der Server restarted wird. Habe gestern im Nether eine Restaurierung der Portale und des Zugangs zur Festung gemacht. Dabei hat mich mein Provider kurz raus geschmissen. Seit dem ist wieder dieses Problem. Deshalb raus mit den Scripten und Reset vom Nether, damit wir weiter testen können.

**Comment by krakel** [comment]
Hast du was gemacht? Der Server läuft seit Stunden ohne Probleme.
Habe unser Problem bei ModTweaker2 und MineTweaker3 gepostet. Mal sehe was da rauskommt.

**Comment by DerOliDE** [comment]
Ich hab nichts am Server gemacht.

Reference zu den Mod-/MineTweaker wäre nett.

Am 08.07.2015 um 10:59 schrieb Uwe Dörl:

**Comment by krakel** [comment]
https://github.com/jaredlll08/ModTweaker2/issues/175
https://github.com/stanhebben/MineTweaker3/issues/202

**Comment by Zixxl** [comment]
Wie ich das verstanden habe, testet ihr gerade das ModPack auf eurem Server. Kann ich eine experimentelle Version von ModTweaker2 zur Verfügung stellen, die ihr testen könnt? Ich versuche  gerade einige Probleme zu beheben, unter anderem dieses. Ich kann aber nicht versprechen, dass schon alle Funktionen stabil laufen.

**Comment by DerOliDE** [comment]
Ich persönlich habe nichts dagegen, wenn die anderen nichts dagegen 
haben können wir das machen.

Am 08.07.2015 um 13:21 schrieb Zixxl:

**Comment by krakel** [comment]
Herz was willst du mehr, wenn die Modentwickler persönlich helfen wollen.

**Comment by Zixxl** [comment]
Ich habe viel in ModTweaker2 geändert, kann aber nicht alles alleine testen. Ihr helft mir damit also auch :+1:

**Comment by BakermanLP** [comment]
Danke an @Zixxl für die Hilfe hier. Kriegst ne Einladung zum Staffelstart in unserer dann neuen Let's Play Staffel :)

**Comment by Zixxl** [comment]
@BakermanLP in der Version sind dann übrigens auch die beiden Features drin, die du für ModTweaker2 gewünscht hast (Smeltery Fuel & Smeltery Recipes)

Fuel Funktionen:

```
mods.tconstruct.Smeltery.addFuel([Liquid], [(int)Power], [(int)Duration]);
mods.tconstruct.Smeltery.addFuel(<liquid:water>, 1300, 80);

mods.tconstruct.Smeltery.removeFuel([Liquid]);
mods.tconstruct.Smeltery.removeFuel(<liquid:lava>);
mods.tconstruct.Smeltery.removeFuel(<*>);
```

Logging command:
`/mt tconstruct`

**Comment by BakermanLP** [comment]
@Zixxl Herzlichen Dank. Dann können wir da noch mehr tweaken :+1:

**Comment by Zixxl** [comment]
Einen build von meiner dev-Version könnt ihr hier runterladen:
http://188.138.106.124/ModTweaker2/

/edit: Fehler, die diese Version betreffen, bitte direkt in meinem Fork posten: https://github.com/Zixxl/ModTweaker2

**Comment by Zixxl** [comment]
Sehe gerade, die Fehlermeldung hier unterscheidet sich von der, die bei ModTweaker2 gepostet wurde. Die ergibt auch irgendwie absolut keinen Sinn:
`Equal objects must have equal hashcodes.`
und

```
object #1 [...] hashCode= 138575871 [...]
object #2 [...] hashCode= 138575871 [...]
```

Für mich sehen die beiden "hashCode"s gleich aus.

**Comment by Grambosch** [comment]
Ich weiß nicht obs von Belang ist aber die unterscheiden sich in der vorherigen ID
id= 1069073138
id= 2064039564
Nicht das sich da 2 Items um einen hashcode hauen (bin kein Modder/Informatiker , ich versuchs immer zu umschreiben)

**Comment by krakel** [comment]
Das wird genauso sein. Die Equals Funktion sagt, diese zwei Objecte sind verschieden. Die Hashfunktion sagt die sind gleich. Das darf lauf Definition von Java nicht sein. Finde interessant, das das erkannt wurde.

**Comment by DerOliDE** [comment]
Die ModTweaker alpha b02 ist jetzt in die 0.6.5 gewandert.

**Comment by Zixxl** [comment]
Wenn zwei unterschiedliche Objekte den gleichen hash haben ist das kein Problem, Kollisionen können vorkommen. In diesem Fall wird dann mittels der equals Funktion geprüft ob diese gleich sind. Die Fehlermeldung beschreibt aber, das zwei Objekte einen unterschiedlichen Hash haben, aber der Inhalt gleich ist. Dass darf nicht passieren. Bin noch etwas ratlos, wie so ein Fehler auftreten kann.

**Comment by krakel** [comment]
Du solltest nicht so intensiv nach diesem seltsamen Fehler suchen. Er trat nur auf, weil in der VM die alte Minecraft Instance noch nicht sauber entladen war und ich trotzdem schon wieder ins Spiel starten wollte. Dadurch wurden die gleichen Objekte in den Speicher geladen und produzierten diesen Konflikt. Ich mußte damals die gesamte VM abschießen. 
Das einzige was man untersuchen könnte, sind mögliche Ursachen, warum das Spiel nicht entladen werden kann. Leider kann ich kein Procedere anbieten um dieses Verhalten zu reproduzieren. Ich wollte mich im Nether ausloggen und das klemmte irgendwie. Werde das demnächst mit der neuen Version testen.

**Comment by Zixxl** [comment]
Bin gespannt ob die neue Version von ModTweaker2 ohne Probleme funktioniert. Konnte wie gesagt noch nicht alles testen, kann aber Bugs direkt beheben und neue Versionen schnell zur Verfügung stellen.

**Comment by Grambosch** [comment]
Mitwirkende Modautoren find ich super und wenn ich dabei mir nicht noch englisch abringen muss ist alles gut

**Comment by krakel** [comment]
Ich habe mal meine Testwelten neu durchprobiert. Ich kann mich in allen normal im Nether aus- und einloggen. Es sieht so aus, das der Fehler behoben ist.

**Comment by krakel** [comment]
Der Server spinnt aktuell mal wieder rum. Nach einiger Spielzeit startet er einfach neu durch! Ist aber ein schneller Neustart. Nicht das das nur eine Nitrado Sache ist. Wie voll ist der benutze Arbeitsspeicher?

**Comment by DerOliDE** [comment]
In die nächste Version wandert die aktuelle alpha b03 mit rein und morgen werde ich beginnen intensiv damit zu werkeln (Ore Processing). Probleme sind mir bis jetzt bei der b02 noch nicht aufgefallen.

**Comment by DerOliDE** [comment]
Ich mach den Issue mal dicht, wenn es in 0.7.0 wieder zu Problemen kommen sollte einfach neuen ggf. mit Cross-Ref. auf diesen aufmachen.
