### ISSUE TITLE
Resultat sieben Endstone

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#137]
Ich habe jetzt ca. 10000 Endstone Blöcke verarbeitet. Dafür habe ich ca. 4 Tage gebraucht und 11 Draconium Dust + Reste erhalten. Im End habe ich dieses Loch gemacht. Wir müssen jetzt überlegen, was passiert, wenn da mehrere Spieler arbeiten und viel mehr Dust produzieren wollen. Die Insel wird dann schnell Geschichte sein.

![2015-07-07_17 19 32](https://cloud.githubusercontent.com/assets/4434299/8565935/6df6dba4-255a-11e5-88b3-413e8cdbd75d.jpg)

**Comment by krakel** [comment]
Außerdem habe ich noch 19 Draconic Ore rausgeholt. Habe nur die von dem Bereich im Bild benutzt und nicht die Ränder mitgenommen.

**Comment by krakel** [comment]
Das neue End ist super. Sehr viel Endstone und viele interessante Strukturen. Leider aber keine Lycanite Mobs mehr.
![2015-07-12_18 30 56](https://cloud.githubusercontent.com/assets/4434299/8638741/e87e15b4-28c4-11e5-859a-86334f46f299.jpg)

Und da ich gerade bei Bildern bin. Habe mal das knallen in der Basis untersucht. Wenn das so weiter geht wird bald die gesamte Insel ausgehölt sein.
![2015-07-11_18 53 46](https://cloud.githubusercontent.com/assets/4434299/8638744/ee8bff5c-28c4-11e5-859e-f8cd997a22b9.png)

**Comment by DerOliDE** [comment]
Was knallt wo un warum?
