### ISSUE TITLE
The End

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#139]
Hatten es ja schon im TS kurz besprochen aber ich schreib es auch nochmal hier nieder, damit es jeder zu lesen bekommt, das es sinnvoll wäre noch Hardcore Ender Expansion mit ins Boot zu nehmen. Damit hätten wir dann nicht nur die "kleine" Insel im End, sondern quasi ein endloses End. (klingt komisch, ist aber so ^^)

Damit gäbe es keinen Ärger um die knappen Ressourcen auf der Insel.

**Comment by krakel** [comment]
Ich würde das begrüßen. Denn aktuell ist das End auch nicht annähernd so schlimm wie ich dachte. Mit ordentlicher Rüstung und guter Flugfähigkeit ist es der absolute Easymode. Man muß nur hoch genug über der Oberfläche bleiben.

**Comment by BakermanLP** [comment]
Halte ich für eine gute Erweitetung

Uwe Dörl notifications@github.com schrieb am Mi., 8. Juli 2015 16:10:

**Comment by Grambosch** [comment]
Na dann tun wir das doch

**Comment by DerOliDE** [comment]
Permission bekommen, wandert in die 0.6.6
