### ISSUE TITLE
Adv. Generators Balancing (Oli)

### ISSUE THREAD

**Issue by combak** [combak/ShatteredWorld#14]

**Comment by Grambosch** [comment]
Rezepte sind angepasst. Wäre da configseitig noch was zu tun?

**Comment by DerOliDE** [comment]
Ggf. nochmal den Heater anschauen der war zu mindestens in Project Phoenix extrem stark.

**Comment by DerOliDE** [comment]
Config overrides: http://bdew.net/generators/configuration/ 

Beispiele habe ich leider keine gefunden.

**Comment by BakermanLP** [comment]
So extrem stark fand ich den eigentlich gar nicht. Welcher Aufbau, welcher Output, welcher Verbrauch?

**Comment by DerOliDE** [comment]
Ich hatte den Aufbau nie im Betrieb aber es war/ist(?) soviel Energie zu erzeugen das man über den Magma Crucible Lava für den Heater herstellen kann und trotzdem noch mit plus an Energie rausgeht.

**Comment by DerOliDE** [comment]
Hab mal ein Testaufbau auf dem Testserver hingestellt und der ist definitiv ein Minusgeschäft.
