### ISSUE TITLE
Zyklischer Server Absturz 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#142]
http://pastebin.com/hbwcPMTg

Soll vermutlich ein JVM Bug sein und ich habe testweise Java 8 auf dem Server aktiviert.

**Comment by krakel** [comment]
Es läuft wieder des halbstündige Speichern vom Ingame Forge System. Wird sicher bald der Plattenplatz eng.

**Comment by DerOliDE** [comment]
Das Forge Essentials Backup Modul habe ich nicht wieder aktiviert, ebenso habe ich diese Optionen (extra Verzeichnis) seit den letztens updates nicht mehr angefasst.

**Comment by DerOliDE** [comment]
Das Problem hat sich mit Java 8 erledigt.
