### ISSUE TITLE
erlaubte Kommandos

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#143]
Habe gerade festgestellt, das einige Kommandos möglich sind.
- /back - portet einen zur letzten Position (meistens des letzten Todes)
- /craft - öffnet ein Craftinggrid
- /drop - kann man wohl irgendwas in die Welt setzen
- /home - setzt ein Home Position

Und noch einige andere. Kann natürlich sein, das ihr das allgemein eingeschalten habt. Sicher muß da nochmal ein Blick drauf geworfen werden.

**Comment by DerOliDE** [comment]
Befehle die für die Spieler erlaubt sein sollten:
- /home => Teleportpunkt zur eigenen Dimension setzen.
- /tpa => Damit Spieler in die Dimensionen anderer Mitspieler kommen.
- /spawn => Rückkehr in die Lobby.

**Comment by BakermanLP** [comment]
/home halte ich auch für sehr sinnvoll, da man damit aus blöden Situationen kommt, wie z.B. irgendwo festhängen. Einen wirklichen Vorteil hat er davon meiner Ansicht nach nicht. Über die erlaubten Kommandos sollte man auch mit den neuen ForgeEssentials Versionen schauen.

**Comment by DerOliDE** [comment]
Da Forge Essentials nicht mehr im Pack ist, sind diese Commands nicht mehr relevant.
