### ISSUE TITLE
Kein Moonstone

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#144]
Ich habe alle Bedingungen für diesen Moonstone aus Ars Magica erfüllt. Jetzt müßten eigentlich so langsam Meteore fallen, die Moonstone bringen. Aber irgendwie passiert das nicht.
Im INet kursieren diffuse Informationen dazu. Min. Level 10 (ich habe 14), ein Vanilla Biom (ist schwer zu erfüllen), Mondphasen (kein Problem). Vielleicht können wir da ein Rezept als Ersatz anbieten?

**Comment by krakel** [comment]
Ups, ich habe gerade meinen ersten natürlichen Moonstone abgebaut. Es ist ein Meteor in der Nähe meines Waterbioms nieder gegangen. Es geht also. Nur sehe, sehr selten.

**Comment by DerOliDE** [comment]
Trotzdem noch ein _teures_ Rezept einpflegen oder ist die Sache damit gegessen?

**Comment by krakel** [comment]
Ich würde trotzdem noch ein Rezept machen, aber richtig teuer. Das soll vom Mod Entwickler Sicht aus sehr rar sein.

**Comment by Grambosch** [comment]
Ich versuch mal ne Thaumcraftinfusion draus zu machen

**Comment by krakel** [comment]
Ein gute Idee. Kann ruhig bis zu 9 Pedestal haben.
Was ich auch nicht finden konnte, ist Tarma Root (auch Ars Magica). Man braucht das zwar nur für wenig Rezepte, aber die sollten auch möglich sein. Das Zeug sollte aber nicht ganz so extrem sein. Normaler Weise spawnen die in Extrem Hills. Habe jetzt auch mal ein Biom dahin umgewandelt. Glaub aber nicht das da was auftaucht.

**Comment by krakel** [comment]
Sehe gerade das ich nicht rechnen kann. Das Maximum, was ich in Videos gesehen habe sind 4*3 Pedestal, also 12. Naja, du wirst das schon machen.

**Comment by DerOliDE** [comment]
Wäre nett wenn das zur 0.7.0 fertig wäre.

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/blob/master/scripts/Thaumcraft-Shattered%20Magic

**Comment by krakel** [comment]
Super Arbeit. Aber jetzt fehlt leider noch ein nettes Rezept für Tarma Root. Das wird zwar nur für sehr wenige Sachen gebraucht, aber trotzdem wichtig. Eigentlich sollte es in Höhlen wachsen, aber alle meine Versuche auf dem Testserver schlugen fehl.

**Comment by Grambosch** [comment]
Ist drin

**Comment by krakel** [comment]
Beide Rezepte sehen sehr gut aus.
