### ISSUE TITLE
einige Natura Items lassen sich nicht craften

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#147]
Einige Items aus speziellem Holz lassen sich in Natura nicht craften. Die Zuordnung scheint etwas mit dem Holz zu tun.
Trapdoor, Fence Gate, Pressure Plate, Button läßt sich nur aus Eucalyptus herstellen

**Comment by DerOliDE** [comment]
Wäre nett wenn sich jemand findet, der das für die 0.7.0 fertig machen könnte.

**Comment by DerOliDE** [comment]
Einige Rezepte werden nicht im NEI angezeigt aber lassen sich craften, nur die Sticks musste ich abändern, da gibt es jetzt aus 2 Natura Planks = 1 Natura Stick damit es nicht unter die OreDict Planks fällt.
