### ISSUE TITLE
Liste Essbarer Sachen im Pack Stand 0.6.6

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#148]
Ich weiß gerade nicht wie ich hier eine Datei Hochlade. Von derher mach ich das über einen Link

https://www.dropbox.com/s/wtdtognjjw0wcmq/Essen.ods?dl=0

hier könnt Ihr es runterladen.

**Comment by DerOliDE** [comment]
Hab es hochgeladen aber die IDs hättest Du Dir sparen können, die ändern sich mit jeder neuen Welt.

**Comment by DerOliDE** [comment]
Zwecks Übersicht mit https://github.com/combak/ShatteredWorld/issues/123 verlinkt und geschlossen.
