### ISSUE TITLE
Saybeans als Fleischersatz deaktivieren

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#149]
Ich habe in einem anderen LP gehoert, das man Sojabohnen als Fleischersatz deaktivieren kann. Habe aber dazu sonst nichts gefunden. Wisst ihr was davon und wollen wir das eventuell? Da wir im weiteren Verlauf des Spiel eigentlich keinen Hunger leiden werden, wäre das ein Ersatz mehr für die Nahrungserstellung zu tun.

**Comment by DerOliDE** [comment]
Wäre ich dagegen aus dem einfachen Grund das Pflanzen weniger ticken als Tiere.
