### ISSUE TITLE
Cutter Handle hat gleiches Rezept wie Crops

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#15]
Cutter Handle von Forest Day hat das gleiche Rezept wie die Crops aud AgriCraft. NEi zeigt noch das Rezept für Crops an. Man bekommt aber immer dies Cutter.

**Comment by ghost** [comment]
In der neusten Version gefixt.

**Comment by combak** [comment]
Forest Day 1.4.0f kommt ins nächste Release. (Oli)
