### ISSUE TITLE
Forest-Mods Integration

### ISSUE THREAD

**Issue by Nedelosk** [combak/ShatteredWorld#150]
Mal ne kleine Gedächtnisstütze für mich. Außerdem können nach der Version 0.7.0 noch Vorschläge hier rein gepostet werden für meinen Mod.

**Comment by DerOliDE** [comment]
Nur Server Variante: http://pastebin.com/rtFg4HfV

**Comment by krakel** [comment]
Habe mal einen Blick auf die aktuelle Version gemacht.
- Images für Rubber Fluid und Rubber Bucket fehlen
- einige Namen sind nur ID Namen "forest.nc.block.???" oder "tile.corn.name"
- der Iron Hammer wird so sicher mit gleichem Hammer aus IC2 oder GT kollidieren in anderen möglichen Modpacks
- wie kommt man an den Seed für das Corn?

Tiefer habe ich noch nicht geschaut. Sollten wir vielleicht mal zusammen machen. Eventuell könnten wir technologische Schritte in das Questbuch einbauen.

**Comment by DerOliDE** [comment]
@Nedelosk Wann kann ich wieder eine neue Version bekommen und funktioniert die Charcoal Produktion schon?

Ich würde nämlich gern demnächst wieder eine neue Version raus bringen, die Multiworld Geschichte scheint ja doch etwas länger zu dauern.

**Comment by Nedelosk** [comment]
Ich arbeite daran weis noch nicht genau wann.Aber dieses Wochenende. :)

**Comment by Nedelosk** [comment]
![2015-10-02_13 55 32](https://cloud.githubusercontent.com/assets/10259214/10245980/52c1aaac-690d-11e5-8e89-1bda228b3234.png)
Rendern ist was schönes. :)

**Comment by DerOliDE** [comment]
Ein Ameisenhügel. :)

**Comment by Nedelosk** [comment]
grrrrrrrrrrrrrrrrrrr

**Comment by Nedelosk** [comment]
https://github.com/combak/ShatteredWorld/commit/43a0995677850c2b456e7543f95892dad706d8f4, https://github.com/combak/ShatteredWorld/commit/8781ebcc85a358e843a21cc09905868f137e8f72

**Comment by DerOliDE** [comment]
Ich bringe heute eine neue Version raus, wenn Forest Day soweit ist wäre es gut, wenn nicht wird das auf 0.7.2 verschoben.

**Comment by krakel** [comment]
Exception und Client Crash in NEI bei Rezept für Charcoal.
https://github.com/Nedelosk/Forest-Mods/issues/19

**Comment by krakel** [comment]
Könntest du bitte eine kurze Bauanleitung für den "Ameisenhügel" hier reinstellen.

**Comment by Nedelosk** [comment]
3-3-2 Klotz aus Holz bauen.Und dann den mittleren Block von oben anzünden mit einem Feuerzeug.

**Comment by krakel** [comment]
Funktionier super. Schade das andere Größen wie 5x5x2 nicht möglich sind. Schön auch, das bei verschiedenem Holz auch die Seiten des Stapel verschieden aussehen.
![2015-10-26_11 53 21](https://cloud.githubusercontent.com/assets/4434299/10727203/5addc792-7bd8-11e5-9492-146ac433b3e4.jpg)

**Comment by krakel** [comment]
Wie lange qualmen diese Hügel eigentlich? Im Tooltip wird ja leider noch kein Fortschritt angezeigt. Verändernt sich das Aussehen, wenn sie fertig sind?

**Comment by Nedelosk** [comment]
12000 Ticks und ja er veränder sich.

**Comment by krakel** [comment]
Ah, gerade einer fertig. Sorry, mikriger Hügel.

**Comment by krakel** [comment]
![2015-10-26_12 04 19](https://cloud.githubusercontent.com/assets/4434299/10727385/baf1736c-7bd9-11e5-984d-1858cd7f07f0.jpg)

**Comment by Grambosch** [comment]
Stöcke geht wieder nu is das Campfire kaputt a gibts nur die Ringe b krieg ich kein Fuel rein

**Comment by Grambosch** [comment]
Beim befüllen eines Barrels mit nem Holzeimer kam es zu einer spontanen Transmutation des Materials so das ich nun einen Eiseneimer besitze , ebenso gibt mein (ercheateter (s.o.)) Furnace erst mal nur beim klicken auf den Ausgabeslot forestmodnei Rezepte an

**Comment by Nedelosk** [comment]
1: Schon gefixt : 
![2015-10-29_21 26 47](https://cloud.githubusercontent.com/assets/10259214/10831148/246356c4-7e84-11e5-8a4f-ceaae33894ca.png)
2: Kann ich nicht bestätigen bei mir geht das alles.
![2015-10-29_21 36 20](https://cloud.githubusercontent.com/assets/10259214/10831296/1d7e5236-7e85-11e5-84c1-3638206b1e48.png)

3: Schon gefixt : 
![2015-10-29_21 35 02](https://cloud.githubusercontent.com/assets/10259214/10831262/f2b911f8-7e84-11e5-8473-6255ece5c3a1.png)

**Comment by krakel** [comment]
Das Rezept für das Campfire wird nicht im NIE angezeigt.

**Comment by Nedelosk** [comment]
Doch : 
![2015-10-31_18 10 16](https://cloud.githubusercontent.com/assets/10259214/10864844/b742007c-7ffa-11e5-9e65-78ae3c00adc5.png)

**Comment by Nedelosk** [comment]
![2016-04-06_22 48 08](https://cloud.githubusercontent.com/assets/10259214/14337697/89f5a9aa-fc70-11e5-9b0e-085cb9f4f5f6.png)
![2016-04-07_03 35 51](https://cloud.githubusercontent.com/assets/10259214/14337845/e719de2a-fc71-11e5-9b0d-fba767469452.png)

Ich habe die Holzkohlemeiler mal von 3x2x3 auf min 4x2x4 bis auf max 9x5x9 erweitert.

**Comment by DerOliDE** [comment]
Denke diesen Issue kann man auch schließen, wenn nichts mehr neues in Forest Mods integriert werden wird.
