### ISSUE TITLE
Leere Welten

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#154]
ForgeEssentials Problematik.

Cross-Ref.: https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1722

**Comment by krakel** [comment]
Hat es einen Grund, warum wir aktuell ForgeEssential 892 benutzen und nicht die aktuelle 908er. Im Issue beziehst du dich auf die 908er, aber wir benutzen die im Moment nicht.

**Comment by DerOliDE** [comment]
Als ich die Version 0.7.0b gepackt habe war der Build 892 aktuell, die Problematik besteht aber auch noch mit dem aktuellsten Build mit dem ich das natürlich auch getestet habe.

**Comment by olee** [comment]
Braucht ihr Multiworld recht dringend oder so?
Wenn ja, kann ich das evtl. ein wenig in der Priorität nach oben rücken.
An sonsten könnte das ein Weilchen dauern, bis ich mir Zeit dafür nehme.

**Comment by DerOliDE** [comment]
Das Modpack baut halt konzeptionell auf Multiworld auf, da jeder Spieler oder jedes Team seine eigene Dimension zum bauen erhalten soll. 

Da das zur Zeit nicht geht hängen wir da etwas in der Luft, wenn ihr da etwas mehr manpower reinstecken könnt, wäre das für uns eine große Hilfe.

**Comment by olee** [comment]
Gut werde mal sehen was ich machen kann die Tage.
Wenn ihr so was mit Teams machen wollt, dann werden euch vermutlich die _Faction_ features gefallen welche für demnächst geplant sind (wollte ich eigentlich vor multiworld machen...)

**Comment by DerOliDE** [comment]
Danke schon einmal im voraus für die Bemühung. :)

Am 11.09.2015 um 23:17 schrieb Björn Zeutzheim:

**Comment by DerOliDE** [comment]
@olee Ich möchte ja kein "Druck" machen aber es sind schon ~ 2 Monate vergangen und das Problem besteht noch immer, wann ist denn mit einer Lösung zu rechnen oder kann man Dir irgendwie unter die Arme greifen?

**Comment by DerOliDE** [comment]
Über 4 Monate Stillstand, nun wird der Forge Essentials Multiworld Part rausfliegen und durch eine eigene Lösung ( https://github.com/DerOli82/yadm ) ersetzt werden. Erste Testversion wird es mit der 0.7.2 voraussichtlich nächste Woche geben. closed

**Comment by olee** [comment]
Dann wünsche ich euch mal viel Erfolg.
Ich wünschte ich könnte das ganze mal fixen, aber ich habe leider wirklich wenig Zeit im Moment.
Wäre interessiert, ob es denn bei euch auch funktioniert!

**Comment by DerOliDE** [comment]
@olee Nichts für ungut, ich habe ja wirklich Verständnis wenn jemand zeitliche Engpässe hat, das kenne ich gut genug aber es währe wirklich nett gewesen auf die Anfragen von Krakel und mir vor ~2 Monaten zu reagieren und einfach zu sagen, das man es zeitlich nicht schafft, dann hätten wir uns schon früher damit arrangieren können.
