### ISSUE TITLE
Forestry NEI keine Rezepte

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#156]
Von Maschienen und kraftbaren Blöcken werden die Rezepte nicht in NEI angezeigt. Ein Test hat aber gezeigt, dass das Craften möglich ist, wenn man die Rezepte kennt.

**Comment by krakel** [comment]
Es scheint wohl seit kurzem Problem bei der NEI Integration zu geben. Das aktuelle Forestryteam arbeitet jetzt aber nur noch an ihrer Version 4.0, bei dem NEI besser integriert sein wird und einige andere alten Zöpfe abgeschnitten wurden. Wir können nur hoffen, das da bald eine final Version raus kommt und wir sie eventuell übernehmen können.

**Comment by Nedelosk** [comment]
Ohh Grayal hast du mir etwa mal zugehört ?

**Comment by Nedelosk** [comment]
Forestry 4.0 ist nun stabel. Das Heist in der nächsten Version haben wir wieder NEI.

**Comment by DerOliDE** [comment]
Schaue ich mir mal heute an.

**Comment by DerOliDE** [comment]
Binnie Mods ist noch nicht für Forestry 4 verfügbar, sprich noch warten.

**Comment by DerOliDE** [comment]
Binnies Mod wird mit der 0.7.2 vorerst deaktiviert, um Forestry 4 zu testen, welches auf jeden Fall in die Finale Version von Shattered World kommen soll mit oder ohne Binnies.

**Comment by DerOliDE** [comment]
Forestry 4 + Binnies Mod + Binnie Patcher läuft.
