### ISSUE TITLE
Ist Blood Magic doch zu mächtig?

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#157]
Nachdem ich mir heute das Video von Direwolf20 angeschaut habe bin ich etwas ins grübeln gekommen.
https://www.youtube.com/watch?v=EvQH8Y7zMWw&list=PLaiPn4ewcbkEC_hsSjPSqN8Mz3qWVC_MA&index=120
ab Minute 10 baut er da die komplette Endinsel ab

Allerdings habe ich mir danach das Video davon angeschaut, wie er das gebaut hat. Danach war es dann doch nicht mehr so schlimm. Der Aufwand ist ziemlich hoch und man braucht auch das höchste Tier des Altars. Aber vielleicht seht ihr das ja anders.

**Comment by DerOliDE** [comment]
Ggf. kann man ja noch immer einzelne Rituale abschalten aber wir sollten auf jeden Fall testen ob die spätere protected Overworld mit irgendeinem Mist "beschädigen/zerstören" lässt.

**Comment by krakel** [comment]
Beim Studium des Direwolf20 Videos ist mir das Sanguine Scientiem Buch aufgefallen. In diesem werden alle Spells von Blood Magic InGame erklärt. Bei uns fehlt das noch. Laut http://minecraft.curseforge.com/mc-mods/224791-blood-magic muß dazu die Guide-API separat hinzu gefügt werden. Könnten wir das für unser Pack auch machen?

**Comment by DerOliDE** [comment]
Schau ich mir später mal an.

**Comment by krakel** [comment]
Ich habe mir mal das Spellsystem angeschaut. Alle Dinge darin werden im Prinzip aus 4 Elementen aufgebaut.
- Brace ... sind einfach und abhängig vom Altar Level 0/2/4
- Cable ... bissle Stein und Simple Catalyst und Altar Level 3
- Core ... die Basis aller Spellkomponenten bestehend aus "Master Blood Orb + Empty Core + Weak Blood Shard + Essence x4 + Vanilla Item x2"
- Plate ... legt das Level der Verbesserung fest, werden im Alchemic Chemistry Set mit vielen Essencen und Shards hergestellt, Altar Level 4/5/5/6

Für eine Spellcombination braucht man im Prinzip nur je eine Komponente. 

Im Beispiel von Direworf20:
Particle Generator + Earth Former + Environmental Spell Modifier + 
Unstable+Standard+Reinforced+Imbued Spell Empowerer + 
Unstable+Standard+Reinforced+Imbued Spell Augmentor

Das ist jeweils bis zum höchsten Level getrieben: Partikel auf Boden mit Umgebungseffekt, 4 fach Stärke, 4 fach Wirksamkeit. 
Beim Bauen dieser Komponenten wird man eigentlich nur von den Cores und den Plates aufgehalten. Die Plates sind vom Altar Level abhängig und ausreichend kompliziert. Die Cores sind relative einfach und hier könnten wir ansetzen. Alles basieren auf dem Empty Core (Simple Catalyst + Gold Ingot x2 + Iron Ingot x2 + Glass x4). Wenn wir dieses Rezept deutlich teurer und schwerer machen wird die Hürde für alle Spells deutlich höher gesetzt. 
Ein weiterer limitierender Faktor, den ich nicht kenne, ist der Blutverbrauch pro Spell. Aber der wird sicher vom Mod aus teuer sein, da jede Verbesserung auch die vorherige verstärkt. So das die Kosten dafür sicher in etwa Unstable +1, Standard +2, Reinforced +3 Imbued +4. Linear bedeutet das 10 fach Kosten, dual 30 fach Kosten. Müste man im Code nachschauen was programmiert wurde. Der Autor warn aber vor Blutverbrauch, so das sicher die 2. Variante drin ist.

Ansonsten sieht das Ganze von weitem sehr umständlich und kompliziert aus. Ich habe bis jetzt noch niemandend auf den letzten Servern gesehen, der dieses System benutzt. Vielleicht sollten wir nicht so viel Panik schieben. Allerdings schauen viele Direworlf20's Videos und sind jetzt vielleicht darauf aufmerksam geworden, so wie ich.

**Comment by DerOliDE** [comment]
Mir geistert noch so im Kopf rum, dass es bei Blood Magic auch noch Block placer/breaker geben könnte. Kann mich da wer aufklären? ^^

**Comment by krakel** [comment]
Soweit ich weiß, eigentlich nicht. Blood Magic ist in dieser Beziehung eher wie Thaumcraft. Werde auch nochmal ArsMagica abklopfen. Nicht das uns da was auf die Füße fällt. Was ist mit AE2 Anhilation Pane?

**Comment by DerOliDE** [comment]
Die AE2 Geschichten sind schon deaktiviert

**Comment by krakel** [comment]
Also doch, man kann mit BM im höchsten Level einen 7x7 Bohrer bauen. Der baut auch die geschützten Items ab und umgeht die Machanik. Aber man bremst sich dadurch nur selbst aus.

**Comment by Grambosch** [comment]
Gibt es da ein/en Block/Item das nur dabei gebraucht wird und das man sperren könnte wen nötig?

**Comment by krakel** [comment]
Der Empty Core 4868:1 bremst das ganze System aus und wird sonst für nichts anderes gebraucht. Er wird nur für die Blöcke des Spellsystem benötigt.

**Comment by DerOliDE** [comment]
Die Rituale lassen sich auch via Config unter "ritual_blacklist" deaktivieren, bspw. Ritual of the Crusher baut Blöcke ab

Das andere sind ja dann die complex spells, da müsste man dann doch nicht den Empty Core und damit alles, sondern den nächsten Schritt bspw. Tool Core oder eins weiter Tool Forge rauswerfen.

**Comment by krakel** [comment]
Ich hoffe aber nur, wenn die Spells Probleme machen sollten. Aktuell sehe ich das nicht. Habe noch nie jemanden diese Spells benutzen sehen. Meist waren alle mit anderen Mechaniken schon viel weiter, als sich BM dazu zu nutzen.

**Comment by DerOliDE** [comment]
**Alles** was Blöcke setzen oder abbauen kann **muss** raus, egal ob Spieler _wahrscheinlich_ nicht auf die Idee kommen könnten oder _wahrscheinlich_ die Mechaniken nicht kennen.

Ich will mir im nachhinein nicht die Arbeit machen zu rekonstruieren, was irgendwo schief gelaufen ist, weil noch irgendein Block Placer/Breaker aktiv war.

**Comment by krakel** [comment]
Also Block Placer sehe ich ein. Aber alles was Blöcke abbauen kann ist ein wenig übertrieben. In jeden Zaubermod, den wir haben, sind irgend welche Stäbe oder Zauber, die Blöcke abbauen koennen (Maschinen Ok). Ein bischen Bergbau sollte schon möglich sein. Und wie willst du die blanke Hand verhindern?

**Comment by DerOliDE** [comment]
Soll ich das wirklich nochmal erklären? Blanke Hand, sämtliche Tools und wahrscheinlich auch die Zauberstäbe, sollte man mal testen, verwenden das Block Break Event, welches durch den Spieler ausgelöst wird und ich in Limited Resources abfragen kann.

Bei Maschinen gibt es keinen Spieler der das Event auslöst und ob diese überhaupt über dieses Event ablaufen ist auch unklar, da die auch direkt aus den Chunks Blöcke entfernen könnten.

Am Ende haben wir dann Spieler, die durch was auch immer, ihre limitierten Blöcke haben abbauen lassen und dann rum jammern weil sie keine neuen platzieren können, solang es kein refresh in Limited Resources gibt.

P.S.: Der Excavation Focus aus Thaumcraft triggert das BlockBreakEvent.

**Comment by krakel** [comment]
Dann sollten folgende Rituale aus sein:
- Ritual of Magnetism - holt Erze an die Oberfläche
- Mark of the Falling Tower - Meteor mit viele Erzen und Zerstörung in der Umgebung

Teleposer - kann alles teleportieren

Muß das aber noch testen

**Comment by DerOliDE** [comment]
Zum Teleposer verweise ich mal auf die Configs hier:
https://github.com/combak/ShatteredWorld/blob/master/config/AWWayofTime.cfg#L389-L420
https://github.com/combak/ShatteredWorld/blob/master/config/Sanguimancy.cfg#L18-L21

**Comment by DerOliDE** [comment]
Wie schaut es an dieser Front aus?

**Comment by Grambosch** [comment]
Vorerst Close! Alles sieht erst mal gut aus. Und nen Weg irgendwas auszuhebeln findet bestimmt wer...lassen wir es auf uns zukommen
