### ISSUE TITLE
Blood Magic das Bound Blade kann nicht benutzt werden

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#16]
Wie alle anderen Waffen ist auch dieses Schwert geblockt. :(

**Comment by combak** [comment]
Glaub da brauch es mal eine Liste welche Tools "zwingend" notwendig sind und freigegeben werden müssen. (Oli)

**Comment by krakel** [comment]
Habe mal die Mods durchgeschaut und alle rausgesucht, die noch Sperrmeldung haben.

Applied Energistics
- Certus / Nether Quartz Werkzeuge+Waffen

Ars magica
- Bound Werkzeuge+Waffen

Bloood Magic
- Bound Werkzeuge+Waffen

Botania
- Manasteel / Elementium Werkzeuge+Waffen
- Terra Blade / Shatterer 
- Vitreous Pickaxe
- Soulscribe
- Holy Sword Excaliber

Draconic Evolution
- Draconic Sword
- Sword of the Wyvern

EnderIO
- The Ender
- Dark Pickaxe / Axe

Ex Asrris
- Thaumium Hammer

Extra Utilities
- Etheric Sword
- Erosion Shovel
- Destruction Pickaxe
- Healing Axe
- Reversing Hoe

Forbidden Magic
- Chameleon Werkzeuge+Waffen
- Diabolist Fork
- Riding Crop
- Rapier of the Strix
- Shovel of the Purifier
- Axe of the Skulltaker

Minecraft
- Iron / Wooden / Stone / Diamond / Golden Werkzeuge+Waffen

Natura
- Gastwood / Bloodwood / Darkwood / Fusewood /Quartz Werkzeuge+Waffen

Thaumcraft
- Void / Thaumium  Werkzeuge+Waffen
- Pickaxe of the Core
- Hoe of Growth
- Shovel of the Earthmover
- Sword of the Zephyr
- Axe of the Stream
- Primal Crusher
- Crimson Blade

Thermal Foundation
- Copper / Tin / Silver / Lead / Ferrous / Electrum / Invar / Bronze / Shiny Werkzeuge+Waffen

Witching Gadgets
- Primordial Greataxe / Claymore / Warhammer

**Comment by DerOliDE** [comment]
Diverse Waffen/Werkzeuge in 0.5.1 freigeben falls noch etwas _wichtiges_ fehlt neuen Issue aufmachen ;-)
