### ISSUE TITLE
Harvest Level Wood

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#161]
Ich habe jetzt das Harvest Level Wood hinzugefügt, damit benötigt man nun die Forest Day Axe bevor man überhaupt einen Baum fällen kann, so wie es eingangs geplant war.

Wahrscheinlich müssen jetzt noch andere Blöcke angepasst werden, da sich das Harvest Level um ein nach oben verschoben hat, das muss noch geprüft werden.

Die erste Quest im Questbook Chapter 1 "Aller Anfang ist schwer" muss dementsprechend geändert werden. Zu erst Blätter schlagen um Sticks zu bekommen, dann Flint aus Gravel craften, um danach einen Baum zu fällen.

**Comment by krakel** [comment]
Mir ist das noch nicht ganz klar.
Habe die neuen Configs zu Tinker mal übernommen. Damit zeigt mir das System einen Harvest Level zu Holz an, aber ich kann immernoch das Holz mit der Handkante abschlagen. Wie wollt ihr das verhindern?
Genau das gleiche gilt für Gravel. Dafür wird eine Schaufel oder die Handkante benötigt.
Handkante heißt eigentlich auch jedes andere Item von einer Feder bis zu TNT.

**Comment by DerOliDE** [comment]
Ich hab es an Birch und Oak Wood Logs getestet und die konnte ich nicht 
mehr mit der Hand abbauen, in der BlockOverride.cfg wurden die Logs und 
Planks vom Harvest Level 0 auf 1 gesetzt und sollten somit nicht mehr 
per Hand abbaubar sein.

Am 21.09.2015 um 08:33 schrieb Uwe Dörl:

**Comment by krakel** [comment]
Dann mache ich was falsch. Ich habe extra eine neue Welt mit normalen Rechten erstellt. Habe allerdings nur die 2 Configs in Tinker übernommen. Kann weiterhin alles mit der Handkante abschlagen.

Ein geänderter Quest soll so aussehen?
- abschlagen von Laub, um Sticks zu erhalten.
- suchen und abschlagen von Gravel, um Flint herzustellen
- bauen der ForestDay Axt aus 2 Sticks + 2 Flints (diese Axt ist bei mir noch als Werkzeug gesperrt)

**Comment by DerOliDE** [comment]
Kopiere Dir am besten den kompletten IguanaTinkerTweaks Ordner, da haben 
sich fast alle Dateien verändert. ;-)

Ja die Quest passt so, man brauch jetzt auch nur noch drei Gravel pro 
Flint sonst haut das ohne Crafting Table net hin.

Am 21.09.2015 um 09:12 schrieb Uwe Dörl:

**Comment by krakel** [comment]
Ich bin ein Künstler :(
Man darf natürlich nicht nur seine Git-Kopie updaten, sondern auch alle Dateien im Spiel. Geht bei mir jetzt auch. Das wird spaßig zu Anfang. Habe fast 2 Bäume entlaubt, bis ich 2 Sticks hatte.

**Comment by DerOliDE** [comment]
Ich hatte die 2 Sticks schon nach nem halben Baum. ^^

Am 21.09.2015 um 11:33 schrieb Uwe Dörl:

**Comment by BakermanLP** [comment]
Vorschlag habe ich ins Forum geschrieben, da mir das hier unpassend erschien. Die Anzahl der Sticks erschien mir gerade beim Testen auch als OK.

**Comment by DerOliDE** [comment]
Hättest Du auch hier reinschreiben sollen nutzen die Issues ja auch zur 
Diskussion. :)

Am 22.09.2015 um 10:28 schrieb BakermanLP:

**Comment by DerOliDE** [comment]
IMHO ist es nicht mehr möglich Logs mit der Hand abzubauen, daher closed
