### ISSUE TITLE
ProjectRed Silicon mit EnderIO Silicion via OreDict verknüpfen?

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#162]
Hat jemand etwas dagegen wenn ich das ProjectRed Silicon deaktiviere und via OreDict mit dem EnderIO Silicon kompatible mache? Das besteht prinzipiell auch nur aus Sand un Kohle.

/Edit
Oder ggf. Rezept drin lassen mit EnderIO Silicon als Output und dann via OreDict kompatible machen.

**Comment by krakel** [comment]
Ich denke da hat keiner was dagegen.
