### ISSUE TITLE
Furnace Sync

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#163]
Vanilla Furnace und Redstone Furnace Rezepte wurden/werden synchronisiert, hier für mich eine kleine Erinnerungshilfe welche Rezepte in den Induction Smelter wandern müssen.

Induction Smelter:
- ~~Vinteum Ore (Ars Magica 2) => Vinteum Dust (Ars Magica2)~~
- ~~Sunstone Ore (Ars Magica2) => Sunstone (Ars Magica2)~~
- ~~Moonstone Ore (Ars Magica2) => Moonstone (Ars Magica2)~~
- ~~Blue Topaz Ore (Ars Magica2) => Blue Topaz (Ars Magica2)~~
- ~~Chimerite Ore (Ars Magica2) => Chimerite (Ars Magica2)~~
- ~~Cinnabar Ore (Thaumcraft) => Quicksilver (Thaumcraft)~~
- ~~Amber Bearing Stone (Thaumcraft) => Amber (Thaumcraft)~~
- ~~Octuple Compressed Cobblestone (Extra Utilities) => Block of Bedrockium (Extra Utilities)~~
- ~~Endium Ore (Hardcore Ender Expansion) => Endium Ingot (Hardcore Ender Expansion)~~

Alloy Smelter:
- ~~Iron Wire (Unhardened) (BC Additions) => 2x Iron Wire (BC Additions)~~
- ~~Gold Wire (Unhardened) (BC Additions) => 2x Gold Wire (BC Additions)~~
- ~~Diamond Wire (Unhardened) (BC Additions) => 2x Diamond Wire (BC Additions)~~
- ~~Raw Heating Conducting Plating (BC Additions) => Heating Conducting Plating (BC Additions)~~
- ~~Raw Conductive Plating (BC Additions) => Conductive Plating (BC Additions)~~
- ~~Limestone Cobble (Tinkers Steelwork) => Limestone (Tinkers Steelwork)~~
- ~~Scorched Cobblestone (Tinkers Steelworks) => Scorched Stone (Tinkers Steelworks)~~
- ~~Rough Brownstone (Tinkers) => Brownstone (Tinkers)~~
- ~~Red Silicon Compound (ProjectRed) )> Infused Silicon (ProjectRed)~~
- ~~Glowing Silicon Compound (ProjectRed) )> Energized Silicon (ProjectRed)~~
- ~~Stone (Vanilla) => 2x Circuit Plate (ProjectRed)~~
- ~~Arcane Compound (Ars Magica2) => 2x Arcane Ash (Ars Magica2)~~
- ~~Netherrack (Vanilla) => Nether Brick (Vanilla)~~
- ~~Binder Composite (EnderIO) => 4x Conduit Binder (EnderIO)~~
- ~~Block of Quartz (Vanilla) => Burnt Quartz (Extra Utilities)~~
- ~~Slag (TE) => Light Gray Rockwool (TE)~~
- ~~Gravel (Vanilla) => Concrete (Chisel2)~~
- ~~Compressed Strach (Forest Day) => Hardened Strarch (Forest Day)~~

Pulverizer:
- ~~Balanced Shard (Thaumcraft) => Salis Mundus (Thaumcraft)~~
- ~~Corn (Forest Day) => Strach (Forest Day)~~

Hängt auch mit https://github.com/combak/ShatteredWorld/issues/61 zusammen.

**Comment by DerOli82** [comment]
@Nedelosk Wann benötigst Du den Strarch bzw. was für ein Tech Level wird das sein? Muss der zwingend schon beim Vanilla Furnace verfügbar sein?

Wenn nicht wurde ich ihn mit zum Alloy Smelter stecken und ggf. das Corn mit Pams Corn kompatible machen.
