### ISSUE TITLE
ProjectRed Red Alloy mit EnderIO Redstone Alloy via OreDict verknüpfen? 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#164]
Wieder eine Ore Dict Frage :)

Sollen die beiden Materialien zugunsten der EnderIO Variante kompatible werden?

**Comment by krakel** [comment]
Ich würde das begrüßen. Da wir alle anderen Materialien vereinheitlicht haben, sollten wir hier nicht halt machen. Dabei würde ich das Rezept von EnderIO bevorzugen.
