### ISSUE TITLE
Botania Verhalten von passive Blumen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#165]
So wie ich das aktuell verstanden habe, ist das Verhalten der passive Blumen (Dayblooms, Nightshades and Hydroangeas) mit der Version R1.7 209 so eingestellt, das die immer verschwinden und durch Dead Bushes ersetzt werden. Alle anderen Blumen, die aktiv befüllt werden müssen, verschwinden nicht. Der Config Parameter I:passiveWither.time=-1 soll wohl nur die Lebensdauer der ersteren betreffen. Allerdings sind doch in der vorletzten Welt nach einiger Zeit alle Blumen verschwunden, oder war das anders.
Siehe:
https://www.reddit.com/r/feedthebeast/comments/3e04ye/ftb_infinity_182_botania_flower_issue/?sort=old
http://botaniamod.net/changelog.php unter R1.7 209 und früher

**Comment by krakel** [comment]
Mein Gedanke ist hier, wenn dieses Verhalten so funktioniert (passive verschwinden, aktive bleiben stehen), könnten wir das Originalverhalten wieder herstellen (24000) und so riesige Wasser-Mana-Farmen vermeiden. Man muß sich so gedanken zum Füttern der anderen Blumen machen.

**Comment by hellamie** [comment]
Oli oder Alfred haben eingestellt das die alle Blumen nach einiger Zeit "verblüht" sind.. SO habe ich das zuminest in Errinnerung.

**Comment by krakel** [comment]
Ich glaube aber, das sich der Parameter I:passiveWither.time, der bei uns auf 12096000 steht nur für die drei oben genannten Blumen gilt. Alle anderen verblühen von Haus aus nicht. Der Mod Programmierer wollte damit große passive Manafarmen unterbinden. Und wir wollen ja auch alle arten von "Monsterfarmen" erschweren. Ich habe auf dem Server einen Test aufgebaut und alle Blumen aufgestellt.
![2015-10-13_12 06 03](https://cloud.githubusercontent.com/assets/4434299/10452198/1666ef82-71a4-11e5-80c0-a1d665446227.jpg)
Danach habe ich über das Botania Buch den Wert des Parameters auf 24000 gestellt. Wenn das geht, müssen wir auch noch prüfen, ob das jeder machen kann, oder nur die OPs.
Werde in 2 Minecrafttagen sehen was da noch ünrig ist.

**Comment by krakel** [comment]
Es ist genau, wie ich vermutet habe. Mußte es auf einer Singleplayerwelt nachstellen und habe die Zeit auf 6000 gesetzt.
Vorher:
![2015-10-13_12 49 11](https://cloud.githubusercontent.com/assets/4434299/10453116/2b3d97c0-71aa-11e5-9a14-36811a2b7b86.jpg)
Nachher:
![2015-10-13_12 57 33](https://cloud.githubusercontent.com/assets/4434299/10453122/327b7110-71aa-11e5-8b89-0c8433658681.jpg)
Es sind nur die oben genannten Blumen verschwunden. In der neuesten Version von Botania werden daraus Dead Bushes! Wir könnten als auf das gewünschte Verhalten vom Mod Entwickler umstellen.

**Comment by DerOliDE** [comment]
Sofern es kein Einspruch gibt würde ich wieder den Standardwert ( 2 Minecraft-Tage ) herstellen, da es ja nun nur die passive Mana-Generation betrift.

**Comment by hellamie** [comment]
jaa...da mus ich aber viel vorarbeit leisten....das heist dann alle wie viel RL Stunden sind die weg?

**Comment by DerOliDE** [comment]
24000 ticks = 1200 sek = 20 min.

**Comment by Grambosch** [comment]
20 min ist trotzdem zu wenig grade zu anfang. Da craftet man länger als die Blume hält. Mach halt ne Stunde oder so.

**Comment by DerOliDE** [comment]
Wie wäre es mit einer Minecraft Woche (140min)?

**Comment by Grambosch** [comment]
Joa , sonst kommt man ja nicht aus dem craften raus zu anfang
