### ISSUE TITLE
[Mod] iBench

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#166]
Ein Mod-Wunsch von Baker: http://minecraft.curseforge.com/projects/ibench

Ich sehe ja so mobile Workbenchs etwas kritisch aber werfe das hier mal zur Diskussion in den Raum.

**Comment by hellamie** [comment]
Botania hat einen der auf Mana Items herstellt..ist kein Direkte Werkbank aber mus mann mal überlegen.

**Comment by krakel** [comment]
Sieht ganz nett aus. Klein und ein paar schöne Extras. Habe nichts dagegen.

**Comment by Grambosch** [comment]
Mit dem Clipboard an sich hab ich keine Probleme , das ist ok aber die kommenden Features mit nem Ofen und zb Autocompressen von Cobble wenn man bergbauen geht (ist ja nur ein Beispiel da geht bestimmt mehr mit) da wirds dann wieder schwieriger

**Comment by BakermanLP** [comment]
Dann einfach das Update sein lassen. Mein Vorschlag basiert auf der
aktuellen Version. Da fand ich nichts wirklich schlimmes. Eventuell die
"zusätzlichen" neun Slots ...

Grambosch notifications@github.com schrieb am Fr., 16. Okt. 2015 14:31:

**Comment by Grambosch** [comment]
Ich hab grad mit Larson geredet der schaut mal das er ein Clipboard reinbastelt in seinen Mod

**Comment by Grambosch** [comment]
Ach so , ja die aktuelle find ich auch nicht schlimm btw, aber schau mal wann da das letzet Update kam.Das sieht nicht aus als ob da wer aktiv dran arbeitet , seis drum wir finden ne Lösung für den Wunsch

**Comment by DerOliDE** [comment]
Ich habe es mir noch nicht angeguckt aber lassen sich die neuen Features vielleicht einfach ausschalten?

**Comment by BakermanLP** [comment]
Die gibt es noch nicht. Eventuell, wenn eine neuere Version mal rauskommt, dann könnten die vielleicht drinnen sein.

**Comment by DerOliDE** [comment]
Ich schmeiße die Mod im nächsten Update mal mit rein, raus nehmen kann man sie dann immer noch.

**Comment by DerOliDE** [comment]
Wenn ich mir anschaue wann die Mod erschienen ist, habe ich zweifel das da überhaupt noch das Update kommt. ;-)

Wäre auch nicht nötig das Larson das bei sich einbaut, das Ganze hat eine open source Lizenz und man könnte es nach bedarf forken.

**Comment by DerOliDE** [comment]
Kommt zum testen in die nächste Version, darum erstmal closed.
