### ISSUE TITLE
Eventuelle Erleichterung durch ContentTweaker

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#167]
Hallo,

eventuell könnten wir uns hier ein wenig Arbeit erleichtern, wenn wir folgenden Mod verwenden:
http://minecraft.curseforge.com/projects/contenttweaker

Damit soll es möglich sein, eigene Blöcke, Items und Fluids in das Spiel zu bringen mittels dieses Minetweaker Addons. 

Sollten wir uns mal ansehen.

Michael (aka BakermanLP)

PS: Den Mod Autor kennen wir

**Comment by DerOliDE** [comment]
Wenn das besser als CustomItems arbeitet, würde ich damit mein 
CustomFluids Not-Flicken ersetzen.

Am 22.10.2015 um 10:23 schrieb BakermanLP:

**Comment by DerOliDE** [comment]
Es gibt schon etwas was mich daran stört ohne es bis jetzt getestet zu haben, weder der ContentTweaker noch die dafür benötigte lib FluxedCore haben eine Lizenz oder eine Erlaubnis damit ich es in ein Modpack einbinden darf, da werde ich die Tage mal nachhacken.

**Comment by BakermanLP** [comment]
Ich denke, dass er zuerst den Mod gemacht hat und dann von jemandem auf die Lizenz gestossen werden muss. Seine bisherigen Werke stehen unter MIT License

**Comment by DerOliDE** [comment]
Zu mindestens Minetweaker hat "nur" eine Permission aber keine open source licence aber egal ich teste das jetzt erstmal und wenn das so läuft wie gewünscht frage ich nach. ;)

**Comment by DerOliDE** [comment]
Zickt zur Zeit noch mit den Fluid Texturen rum aber prinzipiell würde ich damit Custom Fluids ersetzen, dann muss ich wenigstens eine Mod weniger pflegen. ^^

**Comment by DerOliDE** [comment]
Probleme gelöst, kommt in die 0.7.2
