### ISSUE TITLE
[Mod] Launch GUI

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#168]
Vorschlag als Information Panel zum start des Spiels. Kann lästig sein aber dort könnte man diverse wichtige Infos unterbringen.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2149411-launchgui-a-way-to-notify-your-players

**Comment by krakel** [comment]
Was ich hier vermisse, ist ein "nicht nochmal zeigen" Button. Man muß bei jedem Start dieses Fenster wegklicken. (allerdings ein kleines Übel)
Ansonsten ein gutes Tool für allgemeine Informationen.

**Comment by DerOliDE** [comment]
Ja das nervt mich auch aber das könnte man ggf. noch als Request beim Author reinpullen.

**Comment by DerOliDE** [comment]
Die "show once" Option ist sogar schon in der Mod enthalten.
