### ISSUE TITLE
MineTweaker script loading order problems

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#169]
Für den Autopacker braucht man eine Auto Workbench (BC Factory). Dazu braucht man zwei Stone Gears (Buildcraft). Diese lassen sich nicht herstellen. Auch nicht die Alternative Basic Gear (Ender IO).
Stein kann man auch nicht hießen. Zumindest wird kein Rezept in NEI angezeigt.

Kein Image für Machin Upgrade: Auto-Eject (BuildCraft Additions). Wird auch für Autopacker gebraucht.

**Comment by Nedelosk** [comment]
Ich habe keine Ahnung warum das so ist im Skript steht :
recipes.remove( enderioBasicGear );
recipes.addShaped( enderioBasicGear, [ [ null, odCobblestone, null ], [ odCobblestone, forestDayWoodGear, odCobblestone ], [ null, odCobblestone, null ] ]);

**Comment by krakel** [comment]
Vielleicht eine Unaufmerksamkeit von Oli?

**Comment by Nedelosk** [comment]
Wie meinst du das ?

**Comment by krakel** [comment]
Naja, wer dockert alles noch an den Scripts rum. :)

**Comment by DerOliDE** [comment]
Für was brauchst Du das Stone Gear überhaupt? Das Basic Gear ist auch vom Ore Dict Typ gearStone.

**Comment by krakel** [comment]
Das läßt sich auch nicht herstellen!

**Comment by DerOliDE** [comment]
Interessant bei mir geht es, sowohl in der dev Umgebung als auch im Technic Launcher aber im Script hab ich jetzt mal aus dem Forest Day Gear ein ore:gearWood gemacht, da es ja jetzt im Ore Dict steht.

**Comment by Nedelosk** [comment]
Liegt bestimmt an den überschriebenen Skripts.Mal schell neu installieren.

**Comment by DerOliDE** [comment]
Eine Vermutung hätte ich noch die Gears werden via Ore Dict entfernt ( OreDictionary.zs ) und in anderen Dateien ggf. wieder hinzugefügt. Eventuell wird das neue Rezept dort nochmal entfernt. Benenne die OreDictionary.zs mal in 0-OreDictionary.zs um damit die ganz oben steht.

**Comment by krakel** [comment]
Habe den config und script Ordner neu gemacht. Keine Veränderung.

Was machen eigentlich die .gitignore Files in den Ordnern config, costumnpc und srcipts Ordnern?

**Comment by krakel** [comment]
vielleicht hilft das

```
...\Shattered World\minecraft\scripts\AdvancedGenerators.zs (3 hits)
    Line 136: val thermFoundGearInvar             = <ThermalFoundation:material:136>;
    Line 171: recipes.addShaped( advGeneValveFuidIn,[ [ null, null , null ], [ buildcraftFluidPipeEmerald, thermFoundGearInvar, buildcraftFluidPipeGold ], [ null, enderioChassis, null ] ]);
    Line 174: recipes.addShaped( advGeneValveFluidOut,[ [ null, null , null ], [ buildcraftFluidPipeGold, thermFoundGearInvar, buildcraftFluidPipeEmerald ], [ null, enderioChassis, null ] ]);

 ...\Shattered World\minecraft\scripts\EnderIO.zs (10 hits)
    Line 35: val enderioBasicGear       = <EnderIO:itemMachinePart:1>;
    Line 40: val forestDayWoodGear = <ForestDay:item.gearWood:1>;
    Line 40: val forestDayWoodGear = <ForestDay:item.gearWood:1>;
    Line 51: val buildcraftGearIron              = <BuildCraft|Core:ironGearItem>;
    Line 51: val buildcraftGearIron              = <BuildCraft|Core:ironGearItem>;
    Line 70: # Changed Gear Crafting
    Line 71: recipes.remove( enderioBasicGear );
    Line 72: recipes.addShaped( enderioBasicGear, [ [ null, odCobblestone, null ], [ odCobblestone, forestDayWoodGear, odCobblestone ], [ null, odCobblestone, null ] ]);
    Line 72: recipes.addShaped( enderioBasicGear, [ [ null, odCobblestone, null ], [ odCobblestone, forestDayWoodGear, odCobblestone ], [ null, odCobblestone, null ] ]);
    Line 80: recipes.addShaped( enderioGeneratorStirling, [ [ bcAdditionCoilBasic, advGenePowerIO , bcAdditionCoilBasic ], [ projectRedConductivePlate, buildcraftGearIron, projectRedConductivePlate ], [ enderioChassis, vanillaFurnace, enderioChassis ] ]);              

  ...\Shattered World\minecraft\scripts\OreDictionary.zs (22 hits)
    Line 138: val oreDictRemoveGears = [
    Line 139:   <ore:gearWood>,
    Line 140:   <ore:gearStone>,
    Line 141:   <ore:gearIron>,
    Line 142:   <ore:gearGold>,
    Line 143:   <ore:gearCopper>,
    Line 144:   <ore:gearTin>,
    Line 145:   <ore:gearSilver>,
    Line 146:   <ore:gearLead>,
    Line 147:   <ore:gearNickel>,
    Line 148:   <ore:gearPlatinum>,
    Line 149:   <ore:gearMithril>,
    Line 150:   <ore:gearElectrum>,
    Line 151:   <ore:gearInvar>,
    Line 152:   <ore:gearBronze>,
    Line 153:   <ore:gearSignalum>,
    Line 154:   <ore:gearLumium>,
    Line 155:   <ore:gearEnderium>
    Line 197: # Remove Gear Crafting
    Line 198: for gear in oreDictRemoveGears
    Line 198: for gear in oreDictRemoveGears
    Line 200:   recipes.remove( gear );

  ...\Shattered World\minecraft\scripts\ThermalExpansion.zs (16 hits)
    Line 34: val thermFoundGearSilver            = <ThermalFoundation:material:130>;
    Line 35: val thermFoundGearInvar             = <ThermalFoundation:material:136>;
    Line 36: val thermFoundGearFerrous           = <ThermalFoundation:material:132>;
    Line 37: val thermFoundGearElectrum          = <ThermalFoundation:material:135>;
    Line 43: val buildcraftGearGold              = <BuildCraft|Core:goldGearItem>;
    Line 43: val buildcraftGearGold              = <BuildCraft|Core:goldGearItem>;
    Line 889:                   [buildcraftGearGold, bcAdditionCoilLava, buildcraftGearGold], 
    Line 889:                   [buildcraftGearGold, bcAdditionCoilLava, buildcraftGearGold], 
    Line 895:                   [thermFoundGearSilver, bcAdditionCoilLava, thermFoundGearSilver], 
    Line 895:                   [thermFoundGearSilver, bcAdditionCoilLava, thermFoundGearSilver], 
    Line 901:                   [thermFoundGearFerrous, bcAdditionCoilLava, thermFoundGearFerrous], 
    Line 901:                   [thermFoundGearFerrous, bcAdditionCoilLava, thermFoundGearFerrous], 
    Line 907:                   [thermFoundGearElectrum, bcAdditionCoilLava, thermFoundGearElectrum], 
    Line 907:                   [thermFoundGearElectrum, bcAdditionCoilLava, thermFoundGearElectrum], 
    Line 913:                   [thermFoundGearInvar, bcAdditionCoilLava, thermFoundGearInvar], 
    Line 913:                   [thermFoundGearInvar, bcAdditionCoilLava, thermFoundGearInvar], 

```

**Comment by DerOliDE** [comment]
@krakel Dinge ausschließen die reine clientseitige Konfiguration sind, wie bspw. MapWriter oder NEI, im customnpcs die playerdatas und die im Script Ordner könnte mittlerweile weg.

**Comment by DerOliDE** [comment]
@krakel Schon versucht die OreDictionary.zs so umzubenennen wie ich es vorgeschlagen hab?

**Comment by krakel** [comment]
Dachte, man kann nur eine .gitignore im root Ordner anlegen.

**Comment by DerOliDE** [comment]
@krakel Ja ich hab das jetzt auch zusammengefasst, das Programm was ich benutzte legt das in die einzelnen Ordner.

**Comment by krakel** [comment]
Ok, wenn ich auf 0-OreDictionary.zs umbenenne, geht es. Wir sollten wohl im script Ordner eine Namensgebung wie im Linux Dienste Ordner benutzen. :)

**Comment by DerOliDE** [comment]
Reicht wenn wir OreDictionary.zs, Furnaces.zs und später Fluids.zs nach oben schieben, das sind bis jetzt die einzigen "globalen" Scripts

**Comment by Grambosch** [comment]
Nur zum Verständnis: Hab ich was verkehrt geschrieben in dem Script?Ich dachte eigentlich an der Autoworkbench hab ich nix gemacht.

**Comment by DerOliDE** [comment]
@Grambosch Nein Du hast nix falsch gemacht, ist ein Fehler in der Reihenfolge wie die Scripts geladen wurden, die 3 genannten müssen zuerst geladen werden.

**Comment by Grambosch** [comment]
Fein

**Comment by krakel** [comment]
Ich würde die aber nicht alle 0-\* nennen, sondern da auch eine Reihenfolge rein bringen: 0-OreDictionary, 1-Furnaces, 2-Fluids

**Comment by DerOliDE** [comment]
done

**Comment by DerOliDE** [comment]
Interessant jetzt funktioniert es bei mir nicht mehr, wieder so ein Windows Linux Voodoo -.-

**Comment by DerOliDE** [comment]
"Any number of script files can be stored in these directories - they will all be executed, in no particular order."  

http://minetweaker3.powerofbytes.com/wiki/Tutorial:Introduction

Ist nicht wirklich ein System zu erkennen: http://pastebin.com/EXjgUeJA

**Comment by krakel** [comment]
Er nimmt sie bestimmt in der Reihenfolge, in der sie in der Filetabelle stehen und die hängt von der Reihenfolge der Erstellung ab. Das hat dann nichts mir Linux/Windows zu tun, nur mit dem Zeitstempel der Dateien. Äußerst blöd.

**Comment by krakel** [comment]
Wie ich vermutet habe, und eine kleine Änderung würde schon helfen:

``` java
public Iterator<IScriptIterator> getScripts() {
        List<IScriptIterator> scripts = new ArrayList<IScriptIterator>();
        if (directory.exists()) {
// ein simples Arrays.sort(directory); würde hier schon helfen
            for (File file : directory.listFiles()) {
                if (file.isDirectory()) {
                    scripts.add(new ScriptIteratorDirectory(file));
                } else if (file.getName().endsWith(".zs")) {
                    scripts.add(new ScriptIteratorSingle(file));
                } else if (file.getName().endsWith(".zip")) {
                    try {
                        scripts.add(new ScriptIteratorZip(file));
                    } catch (IOException ex) {
                        MineTweakerAPI.logError("Could not load " + file.getName() + ": " + ex.getMessage());
                    }
                }
            }
        }
        return scripts.iterator();
    }
```

**Comment by krakel** [comment]
Ich habe mal ein Issue bei denen aufgemacht.
https://github.com/stanhebben/MineTweaker3/issues/270
Hoffe das ist der richtige Github Bereich.

**Comment by DerOliDE** [comment]
Wegen so einem Unfug kann einem die Lust schon wieder vergehen...

**Comment by DerOliDE** [comment]
Custom Builds sind erlaubt ( see https://github.com/stanhebben/MineTweaker3#customized-builds ), ich werde mich heute an die Lösung dieses Problems setzen.

**Comment by DerOliDE** [comment]
Ich habe uns einfach mal ein customized build gemacht indem die files sortiert werden, das scheint auch soweit zu funktionieren und wird vielleicht heute noch in einen weiteren Hotfix wandern.

closed in 0.7.1b
