### ISSUE TITLE
keine Rezepte für Backpack!s Backpack

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#17]
Nur im NEI werden sie nicht abgezeigt. Wenn man weiß wie, kann man sie craften.

**Comment by Grambosch** [comment]
Hatte gestern Rezepte...also Close

**Comment by krakel** [comment]
Stimmt leider nicht. Alle Items 4097,4098 und 4097:1-15 haben keine Rezepte in NEI.

**Comment by DerOliDE** [comment]
Habs gerade nicht vor Augen aber als ich drüber geguckt hatte waren es die colorierten und das Quantum Teil wo kein Rezept angezeigt wurde.

**Comment by krakel** [comment]
Ja, das 4097:3 ist das Basisrezept und auch vorhanden. Die farbigen und das Quantum werden anders hergestellt. Die ID für den Basispackpack ist etwas verwirrend, aber so ist dann alles in Ordnung.

**Comment by DerOliDE** [comment]
Das einfärben geht nicht via Crafting Rezept, dort muss man die gewünschte Farbe (geht scheinbar nur mit Vanilla Farbstoffen) in das Backpack legen und dann rechts klicken.

**Comment by krakel** [comment]
Warum du jetzt die letzte Änderung mit dem B:disable_item_restorers=true und B:disable_inventory_crafting_interface=true gemacht hast, erschließt sich mir nicht.

**Comment by DerOliDE** [comment]
Steht im commit
