### ISSUE TITLE
Absturz fehler gefunden

### ISSUE THREAD

**Issue by hellamie** [combak/ShatteredWorld#170]
Wenn ich im Ts spreche (STRG-Taste) und gleichzeitig wiederbelebe tötet sich mein Minecraft total...

Wenigstens wird ein Grab generiert.

**Comment by hellamie** [comment]
ähhh es geht auch ohne die taste zu drücken schief  dabei ist mir kein Grab generiert worden..so wie gestern beim ersten versuch...arg ist das nervig.

[B#328]  
[B#328]     Is Modded: Definitely; Client brand changed to 'fml,forge'
[B#328]     Type: Client (map_client.txt)
[B#328]     Resource Packs: []
[B#328]     Current Language: English (UK)
[B#328]     Profiler Position: N/A (disabled)
[B#328]     Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[B#328]     Anisotropic Filtering: Off (1)
[B#328]  [09:35:19] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Alex\AppData\Roaming.technic\modpacks\shattered-world\crash-reports\crash-2015-11-03_09.35.19-client.txt
[B#328]  [09:35:19] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[B#328]  [09:35:19] [pool-5-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to C:\Users\Alex\AppData\Roaming.technic\modpacks\shattered-world\saves\Alex 1_11_15\enderio\dimensionalTransceiver.json
[B#328]  [09:35:19] [Client thread/INFO] [FML]: Server terminated.  

hier das geschriebe aus dem Fenster.

**Comment by hellamie** [comment]
ahahah gerade bin ich einfach so abgestürzt ohne grund...grrummel.

Larson..ich darf deine Werkbank nicht abbauen mit er Flint-Hatchet. ist das richtig oder bug?

**Comment by krakel** [comment]
Habe das gerade mal getestet. Kann die Workbench sowohl mit Tinker Hatchet als auch mit Flit Hatchet abbauen. In jedem Fall zerstört das die Workbench, ohne das bei mir der Client abstürzt.
Aber!
Kann aktuell die Workbench mit keinem Werkzeug abbauen. Verschwindet immer.

@hellamie  Man kann jetzt beim Angeln alle Fische für den Quest benutzen.

**Comment by hellamie** [comment]
http://pastebin.com/VErgGBNb (der vorletzete)
http://pastebin.com/x3EfDSZa (der erste) 

Insgesammt 5 Berichte in 2 Tagen "erstellt"

**Comment by DerOliDE** [comment]
@hellamie Wäre noch interessant zu wissen was Du da gemacht hast als es abgestürzt ist und ob sich das reproduzieren lässt.

**Comment by hellamie** [comment]
ersten 4 gestorben an mobs und wollte nur wiederbeleben. 1 mal wollte ich Tinkertische wieder aufstellen

**Comment by DerOliDE** [comment]
Das passt irgendwie nicht mit den Fehlermeldungen zusammen, da findet er eine Texture (Ex Nihilo Barrel) nicht. :(

**Comment by hellamie** [comment]
barrel gerade laut larson abgerissen  mal sehen

**Comment by DerOliDE** [comment]
Werde in der nächsten Version mal Ex Nihilo und Ex Astris updaten.

**Comment by hellamie** [comment]
https://www.dropbox.com/s/ml05otzr39gtu20/crash-2015-11-03_21.09.19-client.txt?dl=0
https://www.dropbox.com/s/ljljc4joexq1rlj/crash-2015-11-03_09.35.19-client.txt?dl=0
https://www.dropbox.com/s/igkxrky4eq34y3h/crash-2015-11-03_09.14.35-client.txt?dl=0
https://www.dropbox.com/s/9uenghxxyh7qmx3/crash-2015-11-03_09.04.17-client.txt?dl=0
https://www.dropbox.com/s/cqm3xg90dxijzhy/crash-2015-11-02_19.48.01-client.txt?dl=0
