### ISSUE TITLE
Kleines Hilfmod für alle Thaumcraft Fans

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#171]
http://www.curse.com/mc-mods/minecraft/227328-thaumcraft-node-tracker
Dieser Mod führt eine Liste alles gescannten Nodes. Sehr harmlos und nur Clientseitig.

**Comment by Grambosch** [comment]
Harmlos ja aber eher weniger nützlich da a) eigene Dimension sehr beschränkt b) Overworld ist Adventure bleiben noch Farmwelt und Nether (End weiß ich grad nicht obs die da gibt) Kann man anbieten als optionalen Mod oder so

**Comment by DerOliDE** [comment]
Ich schmeiße es in die 0.7.2, da es nur clientseitig is tut es dem Server auch nicht weh. ^^
