### ISSUE TITLE
Teleporter NPC vergessen Zielpunkte

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#172]
Nach jedem Ausloggen vergessen die Teleporter NPC alle freigeschalteten Zielpunkte.

**Comment by Grambosch** [comment]
Welche Teleporter bitte?

**Comment by krakel** [comment]
Na die 4 Coniungo Jungs, die in jeder Location rumstehen. Da steht als Gruppenname sogar Teleporter dran. Wenn man in deren Nähe kommt, wird der Teleport untereinander freigeschalten und in eine Liste aufgenommen. Früher haben die sich das bis zum nächsten Login gemerkt. Jetzt habe die kollektiven Alzheimer.

**Comment by krakel** [comment]
Ich habe mal etwas gegooglet und diese Posts gefunden.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs?comment=3676
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs?comment=3690
Allerdings ist das alles aus 2012. Aber vielleicht hilft es bei uns weiter.

**Comment by DerOliDE** [comment]
Für CustomNPCs gibt es ein update, eventuell ist das Problem dort gelöst, ich konnte es noch nicht testen.

**Comment by DerOliDE** [comment]
Habe es mal grob getestet und die Teleporter scheinen jetzt gespeichert zu werden, bitte verifizieren.

**Comment by DerOliDE** [comment]
Zur Erinnerung, nach dem umbasteln der Welt, müssen die Teleporter neu eingestellt werden, da sie noch auf die Overworld anstatt DIM1000 verweisen.

**Comment by DerOliDE** [comment]
Sollte jetzt alles funktionieren, ich mach den Issue mal dicht.
