### ISSUE TITLE
Schlange die sich in Ar.. beist

### ISSUE THREAD

**Issue by hellamie** [combak/ShatteredWorld#174]
Um ein Machin Frame zu bauen brauche ich Kabel. Die stelle ich mit dem Asembly table her. Um den Laser herzustellen brauche ich einen Fluid Transposer. Dafür brauche ich einen Machin Frame..
Ahhh

**Comment by Grambosch** [comment]
Check ich gleich , wird dann behoben

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/commit/de4f9b20d320c091c8aa740b2595244da6557422

**Comment by hellamie** [comment]
soo...wenn mann nach 5 tagen/oder so, von seinen 2 Cruiceble, 1 cruiceble abbaut (weil umzug oder so) und wieder setzt, kann mann anschließend einen 2ten setzen. bzw ist JA  eigendlich dann der 3te .

ob das noch weiter reproduzierbar ist also 4-5-6 oder so muss ich noch testen.

**Comment by DerOliDE** [comment]
@hellamie Schreibt er das nur in den Chat oder kann man wirklich mehr als erlaubt setzen?

**Comment by hellamie** [comment]
kann mann wirklich setzten..aber bisher hat es nur im singelplayer auch gefunzt

**Comment by hellamie** [comment]
Eben neue Welt im Singelplayer erstellt und da ist der Bug nicht zu finden. Also ist nur das Testspiel im eimer...

**Comment by DerOliDE** [comment]
Dann schließe ich diesen Issue mal.
