### ISSUE TITLE
Natura entfernen? 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#176]
Nachdem bei Natura wieder ein Fehler\* aufgetaucht ist der mir erschreckend bekannt vorkommt, den hatten wir in Project Phoenix oder sogar schon in RETv7, stelle ich mir gerade die Frage, ob wir den Mod rauswerfen sollen.

Gründe:
- Der Fehler crasht den kompletten Server, ich weiß nicht mehr ob wir den fehlerhaften Block irgendwie rauseditieren konnten oder ob sogar die Map auf ein Backup zurückgesetzt wurde aber so etwas ist einfach nur unnotiger Streß.
- Die Mod wird sehr schleppend weiterentwickelt bzw. gepflegt. Letztes update vor einem halben Jahr und letztes stable release Ende 2014.
- Es ist überwiegend "nur" Kosmetik für die World Gen, eventuell durch eine andere Mod ersetzbar.

Was meint Ihr dazu?

*) http://bakermanlp.de/viewtopic.php?f=16&p=860#p860

**Comment by krakel** [comment]
nimm es raus

**Comment by BakermanLP** [comment]
Raus

Uwe Dörl notifications@github.com schrieb am Fr., 11. März 2016, 00:46:

**Comment by Grambosch** [comment]
Natura, heute habe ich leider kein Foto für dich. Du musst die Show leider verlassen

**Comment by DerOliDE** [comment]
Keine Einsprüche gegen das entfernen, wird gemacht.
