### ISSUE TITLE
Harvestcraft update

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#178]
Harvestcraft updatet haue ich nur rein wenn sich jemand findet der die Food Groups für die neuen Items noch einmal durchgeht.

**Comment by DerOliDE** [comment]
Zur Info: Die Food Groups befinden sich nicht mehr in den Scripts sondern hier:

https://github.com/combak/ShatteredWorld/tree/master/config/SpiceOfLife

**Comment by hellamie** [comment]
ich bin dran

**Comment by hellamie** [comment]
habe hoffentlich fertig

**Comment by DerOliDE** [comment]
In meat und fruits verstecken sich noch irgendwo Duplikate.

**Comment by DerOliDE** [comment]
Der Items abschnitt war doppelt, habe ich aber auch erst beim zweiten Blick gemerkt.

**Comment by hellamie** [comment]
habe noch ein paar Dinge geändert...Rechtschreibfehler und so

**Comment by DerOliDE** [comment]
Die folgenden scheinen noch zu fehlen, hauptsächlich Kuchen

OreDict:
foodCarrotcake
foodCherrycheesecake
foodPineappleupsidedowncake
foodChocolatesprinklecake
foodRedvelvetcake
foodLamington
foodPavlova
foodHolidaycake

Items:
harvestcraft:pumpkincheesecakeItem

**Comment by DerOliDE** [comment]
Die genannten Kuchen scheinen sich nicht via Spice of Life eintragen zu lassen, weil sie selbst kein Hunger wiederherstellen, sondern das Item was auf dem Boden platziert wurde.

Drin lassen oder deaktivieren?

**Comment by hellamie** [comment]
mir egal. drin stört ja nicht.

**Comment by DerOliDE** [comment]
Okay dann betrachte ich diese Thematik für 0.7.3 erst einmal für abgeschlossen. :)
