### ISSUE TITLE
ChickenChunks Chunk Loader und Dimensional Anchor aktiv

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#18]
Beide Anker sind erlaubt. Aber wer macht den zweiten, wenn der erste so viel billiger ist?

**Comment by combak** [comment]
Die ChickenChunks Mod wird im nächsten Release entfernt, da man die Dimensional Anchors sowohl Personal als auch als Server Variante laufen lassen kann. (Oli)
