### ISSUE TITLE
Botania update

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#180]
Gab zu viele Änderungen zwischen unserer Version und der aktuellsten, ich habe die Befürchtung das sich Botania zur Eierlegende Wollmilchsau entwickelt hat. Auch hier brauche ich jemanden der die Änderungen abschätzen und balancen kann.

http://botaniamod.net/changelog.php

**Comment by krakel** [comment]
Die letzte Version Botania r1.8-249 ist buggy. Der Runic Altar hat Dupbugs bei den Runes. Man bekommt nicht nur die Resultatrune zurück, auch die die Rezeptrunen.

**Comment by DerOliDE** [comment]
Wie schaut es bei vorherigen Versionen aus? Dann würde ich einfach nicht die aktuellste nehmen.

**Comment by krakel** [comment]
Weiß ich nicht, habe es nur gerade bei Ozone festgestellt.

**Comment by krakel** [comment]
Ups, die wollen das so https://github.com/Vazkii/Botania/issues/1830
Verhalten ist mit R1.8 238 eingeführt worden.

**Comment by DerOliDE** [comment]
Also ein Feature Bug ^^

**Comment by hellamie** [comment]
Ich spiele gerade mal mit Botania rum und schreibe hier einfach rein was mich stört.

Teru Teru Bozu: kleiner Geist. leicht zu bauen. Beeinflusst das Wetter.
Fel Pumkin: mit 2 Eisengittern spawnt ein Blase..ist einfach zu bauen.

Ansonsten habe ich nichts entdeckt was geändert werden muss. ggf noch 1 oder 2 Rezepte was ändern. Aber im großen und ganzen finde ich alle so gut.

**Comment by Grambosch** [comment]
Fel Pumpkin guck ich mir an . Die Blase ist btw ein Blaze.
Mana Spreader guck ich mir an

**Comment by Grambosch** [comment]
Fel Pumpkin kann so gehen.  Du brauchst nen Faden,Knochen,Gunpowder und ein Zombiefleisch zum Kürbis dazu 2 Iron Bars und kriegst einen Blaze.
Das Wetterding ist mir wurscht

**Comment by DerOliDE** [comment]
TODO:
- Rannuncarpus (Block Placer) deaktivieren.
- Mana Lens: Bore (Block Breaker) deaktiveren.
