### ISSUE TITLE
INpureCore wird nicht mehr gepflegt

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#181]
Zitat: "That would be because that aerver no longer exists and my mods are no longer supported because I quit modding like a year ago."

Quelle: https://github.com/INpureProjects/INpureCore/issues/21

Ich hab einen fix übernommen der im Pull liegt ( https://github.com/INpureProjects/INpureCore/pull/23 ), damit die libs wieder geladen werden aber sollten mehr Probleme kommen sollte die Mod rausfliegen.

**Comment by krakel** [comment]
Ist dir bekannt, ob es da Alternativen gibt oder ob sich jemand anderes um die Weiterführung bemüht. Ich finde diesen Mod sehr sinnvoll.

**Comment by DerOliDE** [comment]
Habe ich noch nicht weiter nach gesucht, ich wollte erst einmal den Fehler mit den libs aus der Welt schaffen bis dahin funktioniert die Mod ja noch.

**Comment by sunshinehunter** [comment]
Du kannst die Mod mit dem PR kompilieren, dann ist das Problem gelöst. Oder du kannst die fehlenden Bibliotheken beim Modpack mitliefern, damit diese nicht nachgeladen werden müssen.

**Comment by DerOliDE** [comment]
Ich habe es mir einfacher gemacht, einfach die jar-Datei geöffnet und in der resources.inpure die URL geändert, so wie es in dem hier verlinkten Pull Request gemacht wurde, damit ist das timeout Problem gelöst. :)

**Comment by BakermanLP** [comment]
Du kannst den Mod eigentlich rauswerfen. Wenn es um das Verbergen von Items in NEI geht, geht das auch über MineTweaker. Oder ist noch ein Mod drinnen, der darauf basiert?

**Comment by DerOliDE** [comment]
Wie geht das über MineTweaker?

**Comment by DerOliDE** [comment]
Keine essentielle Mod aber so kurz vor 12 will ich hier nichts mehr ändern, es läuft ja z.Z. rund. :)
