### ISSUE TITLE
[0.7.Der Nedeloskeffekt ist wieder da

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#184]
Wodden Pot Holder und Wooden Leggins nutzen das selbe Rezept.

BItte offenlassen für mehr

**Comment by Nedelosk** [comment]
Ist mir auch schon aufgefallen und wird in der nähsten Version gefixt.

**Comment by krakel** [comment]
Wooden Leggings kollidieren mit Wood Pot Holder.
Larsen kannst du da nicht mal ein universelle Lösung finden?
Edit: Auch bei Eisen dasselbe Problem.

**Comment by Nedelosk** [comment]
Liegt daran das in unserem modpack noch keine neue Version von forest mods ist.

**Comment by Grambosch** [comment]
Und wieder ein Treffer.Cobblestone Slabs geht nicht da kommt ein Rod Stone aus Mod Machines raus ^^.Wir sollten evtl Vanilla tweaken das geht schneller

**Comment by Grambosch** [comment]
Lieber Larson schau dir bitte mal in einem den Materialaufwand und den nutzen von deinen Kilns an. 2x3x3x8 Holz für 32 Charcoal halte ich für zu viel

**Comment by krakel** [comment]
Ein mit Wasser gefüllter Holzeimer verbraucht sich nicht. Unendlich Wasser!!! Angeblich soll das am Creativ liegen.

**Comment by Nedelosk** [comment]
@krakel Genauere Informationen bitte. Für was nutzt du den Eimer ?

**Comment by krakel** [comment]
Eimer hat sich erledigt. Im Creativmode leert sich kein Eimer!

**Comment by Grambosch** [comment]
Bitte schau dir den Durabilityverlust beim Plattenhämmern noch mal an. Mit dem "teuren" Eisenhammer kann ich nur 4 Platten klopfen. Das ist gefühlt zu wenig

**Comment by krakel** [comment]
Auch mit der Feile nur ein Zahnrad ist unrealistisch!

**Comment by DerOliDE** [comment]
Gibt es hier noch irgendein offenen Fehler oder etwas zu bemängeln? Wenn nicht kann der Issue auch erst einmal geschlossen werden.

**Comment by Grambosch** [comment]
Nix gefunden zZ. Evtl noch eine effizientere Lösung für die Plattenproduktion

**Comment by Grambosch** [comment]
Das Plattensystem hat Fehler. Habe gerade 4 Invaringots zu 2 Tinplates geklopft

**Comment by Grambosch** [comment]
Dasselbe gilt für Stahl Kupfer Aluminum usw alles Zinn ^^

**Comment by Grambosch** [comment]
Die sind auch in Rezepten gegeneinander austauschbar und Rezept geht trotzdem.

**Comment by DerOliDE** [comment]
@Nedelosk Deadline bis zum Wochenende, eine **verbindliche** Aussage bis wann die Fehler gefixt werden können und auch mal selbstständig die komplette Mod durchtesten, dass uns nicht noch mehr um die Ohren fliegt.

Kurz und knapp machbar ja/nein?

**Comment by Nedelosk** [comment]
Ich schau mal das ich das bis morgen gefixt habe.

**Comment by DerOliDE** [comment]
Nimm Dir lieber ein Tag mehr und check **alles** nochmal durch, vor Sonntag werde ich mit meinem Kram sowieso nicht fertig.

**Comment by DerOliDE** [comment]
Platen gieße und via Workbench hämmern scheint zu funktionieren. Ebenso scheinen die OreDict Einträge jetzt zu passen.

**Comment by DerOliDE** [comment]
Sehe im Moment keine Fehler mehr, daher zwecks Übersicht erst einmal geschlossen.
