### ISSUE TITLE
Sackgasse 2

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#185]
Um den Alloy Smelter zu bauen brauchts ne Basic Coil (BCA) Um die freizuschalten muss ich nen Heated Furnace bauen der aus Eisenplatten besteht die  erst ab Alloysmelter zu schmelzen sind (und bitte nicht schon wieder ne Halbierung im Furnace  die bei den Wires ist schon ätzend)

**Comment by Grambosch** [comment]
Selbes gilt für die einfachen Circiut plates. DIe sind Grunzutat für die ersten Maschinen und Generatoren gehen aber nicht zu craften ohne den Alloy Smelter , Selbst wenn der irgenwie gebaut werden kann geht halt ohne Generator nix der hat kein Redstone/Kohleeinwurf

**Comment by DerOliDE** [comment]
Würde ich beides über die Smeltery lösen, eventuell sogar die Wires, nur weiß ich da noch keine passende Form.

**Comment by Grambosch** [comment]
Die Plates in das Basin und ein zwei Nuggets drauf gießen?

**Comment by Grambosch** [comment]
Generatoren gehen zur Not die von Forestry die haben einen etwas anderen Grundaufbau
