### ISSUE TITLE
Hella testet

### ISSUE THREAD

**Issue by hellamie** [combak/ShatteredWorld#186]
Questbuch: 
Karate Tiger : Es ist kein Bild von der Axt zu sehen.

Gegenstände : 
Die Axt die man am Anfang baut kann kein Holz abschlagen.

es geht einfach nicht weiter  cheaten hilft leider auch nicht.

ich teste weiter

**Comment by DerOliDE** [comment]
Ich gehe mal davon aus das Du die Axt aus Forest Day meinst, dort haben sich mit dem Update die Item Namen geändert, habe das korrigiert aber ein Update schaffe ich zeitlich wahrscheinlich erst am Do. mal schauen was sich bis dahin noch ansammelt. ^^

Das fehlende Bild im Questbook hängt sehr wahrscheinlich auch mit dem geänderten Item Namen zusammen.

**Comment by krakel** [comment]
Habe alle Namen und fehlende Bilder korrigiert. Leider werden ein paar Icons von Draconic nicht sauber angezeigt.

**Comment by hellamie** [comment]
LARSOOOONNNN:

Ich kann dein Lagerfeuer nicht nicht befüllen..AHahAhah..jedes mal schließt sich minecraft.

**Comment by hellamie** [comment]
Dein Charcoal Pile gibt mir die Items wieder und die Charcoal..juhu unendliche Produktion ohne neu bau.....REPARIEREN bitte

**Comment by hellamie** [comment]
Ich kann im Inventar aus Terrasteel einfach Nuggets machen. Ohne gießen....

**Comment by DerOliDE** [comment]
- Im Questbook wird die Forest Day Axt bei Karte Tiger wieder korrekt angezeigt.
- Holz abbauen mit der Forest Day Axt ist auch wieder möglich.
- Lagerfeuer befüllen funktioniert, Lagerfeuer funktioniert jetzt auch bei Regen, wenn es überdacht ist.
- Charcoal Kiln gibt mir keine Kiln Items zurück und die Charcoal ausbeute war beim test bei 216.
- Terrasteel Nuggets habe ich bearbeitet.

Damit ist dieser Issue erst einmal abgearbeitet und zwecks Übersicht geschlossen.
