### ISSUE TITLE
Server crash bei Workbench

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#187]
Wenn man eine Workbench von ForestDay einfach plazieren will, stürzt der Server ab.

**Comment by krakel** [comment]
Workbench frist die Feile und startet den Prozess nicht. Nächste Feile startet dann den Prozess, um dann beim nächsten Schritt wieder zu verschwinden.

**Comment by DerOliDE** [comment]
Hier der Crash Report zum Server Absturtz: 
https://gist.github.com/DerOli82/cf6465e2432ae921123e7f596ffdf25f

**Comment by krakel** [comment]
Server crashed auch bei Feuerstelle füllen.

**Comment by Grambosch** [comment]
Echt? Ich war doch auf dem Server ? Dachte es wäre nur ein Clientcrash

**Comment by krakel** [comment]
Stimmt, nur der Client. Mein Fehler, sorry.

**Comment by Nedelosk** [comment]
Kann jemand mal einen Crash Report für den Crash mit der Feuerstelle verlinken ?

**Comment by krakel** [comment]
http://pastebin.com/Xdkynznq
Bitte sehr!

**Comment by Nedelosk** [comment]
Danke

**Comment by DerOliDE** [comment]
Ich gehe mal davon aus das die 0.4.2 das Problem behebt oder gibt es noch einen neueren Stand?

**Comment by DerOliDE** [comment]
Scheint alles gefixt zu sein.
