### ISSUE TITLE
Avaritia balancing

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#188]
Ich habe erst einmal alle Mod Vorschläge rein genommen, ob sie drin bleiben müssen wir schauen. Womit ich bei dieser Mod ein Problem habe, egal ob teuer oder nicht, ist:
- Infitity Sword, killt alles mit einem Schlag.
- World Breaker und Planet Eater, baut einen 16x16x16 Bereich mit einem Schlag ab.
- Nature's Ruin, baut Bäume im 16x16x16 Bereich ab und verwandelt Grass in Dirt. Weniger dramatisch aber will es erwähnt haben, da ich befürchte das dieses Item die Game Mechanik "umgeht" und damit wahrscheinlich auch im Adventure Mod alles wegholzt.
- Infinity Helm, kein Hunger mehr.
- Infinity Breatplate, immun gegen negative Effekte.
- Komplette Infinity Rüstung, man wird quasi unsterblich, sogar im Void stirbt man nicht.

Was weniger dramatisch ist:
- Longbow of the Heavens, macht 20Dmg und bei einem Schuss auf den Boden regnet in es in dem Bereich random Pfeile auf auf den Boden.
- Infinity Pants, immun gegen Feuer Effekt, man brennt nicht aber bekommt Schaden, solang man in Feuer oder Lava steht.
- Infinity Boots, Speed und Jump Boost.

Was man mit dieser Mod eventuell überlegen könnte wäre ein extrem teures Rezept für eine Creative Energy Cell (max 32kRF/tick)

**Comment by hellamie** [comment]
zu weniger Dramatisch : 
- So ein Bogen gibt es auch in Botania.. ABER der  ist nur ein Drop, heißt muss man erst mal finden
- Die Boots gibt es auch von Botania, dort ist es glaub ich ein Gürtel in 3 "Stärken"  zum bauen

zu Dramatisch :

aus Botania hast du auch alle Dinge disabeld die so mega abbauen. Also Gleichberechtigung.  Die Rüstung würde ich einfach Sperren, sonst mach spice of life kein Sinn

**Comment by krakel** [comment]
Habt ihr euch mal die Rezepte angesehen. Meiner Meinung nach sind die einfach überirdisch. Da kann man auch noch was drehen. Ich versuche mich in meinem aktuellen Modpack gerade dem zu nähern. Bin aber noch nicht an der ersten Komponente vom ersten Ingot dran, noch nicht mal annähernd. Und man braucht für jedes Teil Unmengen davon. Die Teile sind zwar gottähnlich, aber so gut wie unerreichbar. Eigentlich ist der Mod sinnlos und nur für absolut Verrückte geeignet.

**Comment by krakel** [comment]
Nur so mal als Beispiel der World Breaker

![2016-10-19_15 51 13](https://cloud.githubusercontent.com/assets/4434299/19522705/75b30a9a-9618-11e6-9aa3-0e5d9a5a089f.jpg)

Man braucht 19 Infinity Ingot, das macht 209 Infinty Crystals!

| Item | Menge |
| --- | --- |
| Iron Singularity | 1222650 Blöcke |
| Golden Singularity | 1222650 Blöcke |
| Lapis Singularity | 1222650 Blöcke |
| Redstone Singularity | 1285350 Blöcke |
| Nether Singularity | 1159950 Blöcke |
| Copper Singularity | 1222650 Blöcke |
| Tin Singularity | 1222650 Blöcke |
| Leaden Singularity | 1159950 Blöcke |
| Silver Singularity | 1159950 Blöcke |
| NickelSingularity | 1222650 Blöcke |
| Ultimate Stew | 209 (je 81 verschiedene Foot) |
| Cosmic Meatballs | 209 (je 12 Meat + 1 Pile of Neutrons) |
| Enderst Pearl | 209 |
| Extremely Primordial Perl | 209 |
| 16384k ME Storage Component | 209 |
| Singulairy ME | 209 |
| Block of Bedrockium | 209 |
| Unstable Ingot Block | 209 |
| Block of Terrasteel | 209 |
| Gaia Spirit | 209 |
| Crystal Cluster | 209 |
| Awakened Draconium Block | 209 |
| Block of Mannyullyn | 209 |
| Pure Essence | 209 |
| Sunstone | 209 |
| Record Fragment | 209 |
| Enderium Block | 209 |
| Block of Steel | 209 |
| Dark steel Block | 209 |
| Block of Emerald | 209 |

Da fehlen jetzt noch ca 300 Netherstars und die ganzen Neutrondinger, wo jedes Pile 6 min dauert (81 Pile -> 9 Nugget -> 1 Ingot).
Also nur für Verrückte!
![2016-10-19_15 51 06](https://cloud.githubusercontent.com/assets/4434299/19522734/87c21280-9618-11e6-8d96-b229848bf69d.jpg)
![2016-10-19_15 50 49](https://cloud.githubusercontent.com/assets/4434299/19522738/8c78497a-9618-11e6-90b8-baeaa3aaf565.jpg)

**Comment by DerOliDE** [comment]
Ja ich kenne die Rezepte, darum schrieb ich ja auch **egal ob teuer oder nicht**, die Items sind einfach zu stark und man muss immer davon ausgehen, dass es so _Verrückte_ gibt die das erreichen, sonst könnten wir ja auch die Mod draußen lassen. ;)

**Comment by krakel** [comment]
Ich werde sicher auch zu diesen Verrückten gehören und zumindest versuchen ein Teil davon herzustellen. Allerdings glaube ich auch, dass bis zum ersten Infinity Ingot wir schon lange an Shattered World 2 für 1.10 arbeiten werden. Deshalb sollten wir schon die Rüstung drin lassen und das eine oder andere Werkzeug. Der einzige Sinn dieses Mods sind ja diese Teile. Da ist ja sonst nichts.

**Comment by DerOliDE** [comment]
Bei der Rüstung könnte ich mich auf alles bis auf den Helm einigen. Zum einen damit die Unsterblichkeit nicht möglich wird, das ist ein absolutes nogo im SMP und zum anderen hebelt der Helm die ganze Arbeit, die wir uns mit dem Essen gemacht haben aus. Damit ist die Rüstung auch noch stark genug.

Zu den Tools, das Schwert ist für SMP genau so unzumutbar wie die komplette Rüstung, der Bogen ist in Ordnung und auf die anderen Tools lasse ich mich nur ein, wenn diese im Adventure Modus nicht funktionieren.

P.S.: Das Endest Pearl Ding ist auch ein Problem, da es auf den Boden geworfen schwarze Löcher erzeugt. Dummerweise ist das gleichzeitig ein Crafting Material....

**Comment by krakel** [comment]
Du wirst bei unseren ganzen Limitierungen bei der Rohstoffgewinnung keines dieser Teile je im Spiel sehen. Ok, vielleicht nach 2 Jahren Dauerbetrieb. Aber dann ist es auch egal wenn du es zu Anfang raus nimmst. Falls es doch einer schaffen sollte und wir am Ende die Welt beerdigen wollen, können wir diese Teile ja wieder einschalten.

**Comment by DerOliDE** [comment]
Mit dem Argument kann man die Mod auch draußen lassen....

**Comment by krakel** [comment]
Das stimmt! War von mir auch eher als Anreiz gedacht. Der eine oder andere wird es versuchen und muß sich mit Möglichkeiten der Massenproduktion in verschiedenen Mod beschäftigen. Und da sind einige Kandidaten, wo das fast unmöglich ist. Schon das ist Herausforderung genug. Ohne dem Mod hat man nicht den Ehrgeiz darüber nachzudenken.

**Comment by DerOliDE** [comment]
Darum kam von mir auch noch der Vorschlag eine Creative Energy Cell über diese Mod craftbar zu machen, dass sollte anreiz genug sein und entlastet den Server im Endgame.

Ggf. gibt es ja noch andere Creative Items die eventuell "Sinn" machen würden, um den Server zu entlasten.

**Comment by Grambosch** [comment]
Nur mal eingeworfen: Das Zeug mag mächtig sein und das Zeug ist mehr als nur teuer.Also hat derjenige der dahinwill auch wieder ein Ziel , spielt er auf dem Server wird das zu Gesprächen und handel führen weil er Zeug will...Was das Zeug bei den Kosten kann ist mir wurscht

**Comment by DerOliDE** [comment]
Wie im TS besprochen, bleibt der Mod unverändert drin. 

Wenn wir das so drin lassen, sollte vielleicht im Questbuch noch "frühzeitig" auf den Neutron Collector aufmerksam gemacht werden, da es ja ewig, in Zahlen ~400Min mit einem Collector, braucht um überhaupt mal ein Neutronium Ingot zusammen zu bekommen.

P.S.: Passender Name für den Questabschnitt wäre insanity/Irrsinn. ;-)
