### ISSUE TITLE
Gears kein Rezept

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#189]
Stone Gear und Iron Gear haben keine Rezepte mehr. Nicht getestet, ob nur nicht angezeigt.

**Comment by krakel** [comment]
Sehe gerade, das Iron Gear durch Chalcedony Gear aus Aplle&Milk&Tea überdeckt wird.

**Comment by krakel** [comment]
Dark Steel Block kann nicht gegossen werden. Wird für Infinty Catalyst gebraucht.

**Comment by DerOliDE** [comment]
Die Gears sollten alle nur via Tinkers gießbar sein, gab imho nur eine Ausnahme, muss ich mal schauen und bei den Blöcken gibt es noch ein paar die noch nicht gießbar sind.

**Comment by DerOliDE** [comment]
Das Basic Gear ist craftbar aus einem Wood Gear was via Forest Mods gebaut wird und Cobble und oreDict kompatible zum Stone Gear ist, sprich Stone Gear gibt es nur als Basic Gear.

**Comment by DerOliDE** [comment]
Die Gears werde ich wohl alle auf Thermal Expansion Gears "umbiegen", dann haben wir das wieder einheitlich.
