### ISSUE TITLE
Was muss noch per Minetweaker eingefügt werden!

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#190]
Bitte hier rein mit Sachen die noch rein müssen

**Comment by hellamie** [comment]
Es fehlen Pam Obstbäume, Appel&Milk&Tea fehlen die Clam und Yuzu Setzlinge. 

Erledigt 
https://github.com/combak/ShatteredWorld/commit/be394c7046740b80312c63a01c638a680e3d1198
https://github.com/combak/ShatteredWorld/commit/779e34505d81f68a972b19a9b378dd6ddf88ddca

**Comment by Grambosch** [comment]
Setzlinge zu den Mobdrops hinzufügen

**Comment by krakel** [comment]
Rezept für Mint Seeds (Appel&Milk&Tea)

Erledigt: https://github.com/combak/ShatteredWorld/commit/be394c7046740b80312c63a01c638a680e3d1198

**Comment by DerOliDE** [comment]
Die Heat Conducting Plates (BCA) fehlen noch.

**Comment by krakel** [comment]
Chalcedony Gear aus Appel&Milk&Tea ist zu nichts kompatibel und lässt sich auch nicht craften. Ok betrifft nur den Manual Charge Generator und die Rotary Dial Phones.

**Comment by krakel** [comment]
Advanced Disposable Battery aus Appel&Milk&Tea läßt sich nicht bauen. Ahh, soll laut Video ein Dungeon Chest Loot sein.

**Comment by krakel** [comment]
Das Black Onyx Sword (Appel&Milk&Tea) ist für nicht zu gebrauchen. Vielleich extra frei schalten. Ist eine Reflexionswaffe. Mal was neues.

**Comment by DerOliDE** [comment]
Alle Waffen und Tools müssen explizit über Iquana Tinkers Tweaks freigegeben werden.

**Comment by Grambosch** [comment]
Setzlinge abgehakt. Clams kriegen die Pelikane als Drop. Heat Conducting gehört wohin? Die Rezepte hat ja Oli entfernt Chalcedony guck ich heute Black Onyx schalte ich frei. Was fehlt noch?

**Comment by Grambosch** [comment]
Chalcedony Blocks sind in AMT wohl nur per Villager zu kriegen. Dementsprechend würde ich die Unrat aufs Auge drücken als Traderitem für die Essen/Landwirtschaftsfraktion

**Comment by krakel** [comment]
Ich habe euch mal alle Waffen und Werkzeuge rausgezogen (außer Tinker natürlich). Da kann sicher noch das eine oder andere freigeschalten werden, insbesondere wenn es schwer herzustellen ist. Alles mit der roten Kugel ist nicht benutzbar.

Waffen & Tools:
<details>
- DCsAppleMilk:defeatedcrow.fossilCannon,7343,0,Fossil Cannon
- DCsAppleMilk:defeatedcrow.chalcedonyKnife,7351,0,Chalcedony Knife,&#x1F534;
- DCsAppleMilk:defeatedcrow.chalcedonyStoneCutter,7379,0,Chalcedony Stone Cutter,&#x1F534;
- DCsAppleMilk:defeatedcrow.chalcedonyShears,7400,0,Pruning Shears,&#x1F534;
- DCsAppleMilk:defeatedcrow.yuzuGatling,7402,0,Yuzu Gatling Gun
- DCsAppleMilk:defeatedcrow.onixSword,7407,0,Black Onyx Sword,&#x1F534;
- appliedenergistics2:item.ToolCertusQuartzAxe,4102,0,Certus Quartz Axe,&#x1F534;
- appliedenergistics2:item.ToolCertusQuartzHoe,4103,0,Certus Quartz Hoe,&#x1F534;
- appliedenergistics2:item.ToolCertusQuartzSpade,4104,0,Certus Quartz Shovel,&#x1F534;
- appliedenergistics2:item.ToolCertusQuartzPickaxe,4105,0,Certus Quartz Pickaxe,&#x1F534;
- appliedenergistics2:item.ToolCertusQuartzSword,4106,0,Certus Quartz Sword,&#x1F534;
- appliedenergistics2:item.ToolNetherQuartzAxe,4109,0,Nether Quartz Axe,&#x1F534;
- appliedenergistics2:item.ToolNetherQuartzHoe,4110,0,Nether Quartz Hoe,&#x1F534;
- appliedenergistics2:item.ToolNetherQuartzSpade,4111,0,Nether Quartz Shovel,&#x1F534;
- appliedenergistics2:item.ToolNetherQuartzPickaxe,4112,0,Nether Quartz Pickaxe,&#x1F534;
- appliedenergistics2:item.ToolNetherQuartzSword,4113,0,Nether Quartz Sword,&#x1F534;
- arsmagica2:BoundHoeNor,4182,0,Bound Hoe,&#x1F534;
- arsmagica2:BoundShovelNor,4183,0,Bound Shovel,&#x1F534;
- arsmagica2:BoundAxeNor,4184,0,Bound Axe,&#x1F534;
- arsmagica2:BoundPickaxeNor,4185,0,Bound Pickaxe,&#x1F534;
- arsmagica2:BoundSwordNor,4186,0,Bound Sword
- arsmagica2:natureScythe,4194,0,Nature's Scythe
- arsmagica2:bindingCatalyst,4197,0,Binding Catalyst: Pickaxe
- arsmagica2:bindingCatalyst,4197,1,Binding Catalyst: Axe
- arsmagica2:bindingCatalyst,4197,3,Binding Catalyst: Shovel
- arsmagica2:bindingCatalyst,4197,2,Binding Catalyst: Sword
- arsmagica2:bindingCatalyst,4197,4,Binding Catalyst: Hoe
- Avaritia:Infinity_Axe,7336,0,Nature's Ruin
- Avaritia:Infinity_Shovel,7342,0,Planet Eater
- Avaritia:Skull_Sword,7371,0,Skullfire Sword
- Avaritia:Infinity_Sword,7412,0,Sword of the Cosmos
- Avaritia:Infinity_Pickaxe,7419,0,World Breaker
- Avaritia:Infinity_Bow,7422,0,Longbow of the Heavens
- AWWayofTime:energyBlaster,4782,0,Energy Blaster
- AWWayofTime:energySword,4783,0,Bound Blade
- AWWayofTime:sacrificialKnife,4790,0,Sacrificial Knife
- AWWayofTime:daggerOfSacrifice,4791,0,Dagger of Sacrifice
- AWWayofTime:boundPickaxe,4803,0,Bound Pickaxe
- AWWayofTime:boundAxe,4804,0,Bound Axe
- AWWayofTime:boundShovel,4805,0,Bound Shovel
- AWWayofTime:energyBazooka,4855,0,Energy Bazooka
- AWWayofTime:customTool,4862,0,Dynamic Mace
- Botania:manaGun,4905,0,Mana Blaster
- Botania:manasteelPick,4918,0,Manasteel Pickaxe,&#x1F534;
- Botania:manasteelShovel,4919,0,Manasteel Shovel,&#x1F534;
- Botania:manasteelAxe,4920,0,Manasteel Axe,&#x1F534;
- Botania:manasteelSword,4921,0,Manasteel Sword,&#x1F534;
- Botania:terraSword,4928,0,Terra Blade
- Botania:terraPick,4942,0,Terra Shatterer,&#x1F534;
- Botania:enderDagger,4945,0,Soulscribe,&#x1F534;
- Botania:elementiumPick,4953,0,Elementium Pickaxe
- Botania:elementiumShovel,4954,0,Elementium Shovel
- Botania:elementiumAxe,4955,0,Elementium Axe
- Botania:elementiumSword,4956,0,Elementium Sword
- Botania:glassPick,4975,0,Vitreous Pickaxe,&#x1F534;
- Botania:livingwoodBow,5002,0,Livingwood Bow
- Botania:crystalBow,5003,0,Crystal Bow
- Botania:terraAxe,5024,0,Terra Truncator,&#x1F534;
- Botania:starSword,7270,0,Starcaller,&#x1F534;
- Botania:thunderSword,7293,0,Thundercaller,&#x1F534;
- bcadditions:portableLaser,5108,0,Portable Laser
- customnpcs:npcWoodenGun,5162,0,Wooden Gun
- customnpcs:npcStoneGun,5164,0,Stone Gun
- customnpcs:npcIronGun,5166,0,Iron Gun
- customnpcs:npcGoldGun,5168,0,Golden Gun
- customnpcs:npcDiamondGun,5170,0,Diamond Gun
- customnpcs:npcBronzeGun,5172,0,Bronze Gun
- customnpcs:npcEmeraldGun,5174,0,Emerald Gun
- customnpcs:npcMachineGun,5176,0,Machine Gun
- customnpcs:npcShuriken,5201,0,Shuriken
- customnpcs:npcGiantShuriken,5202,0,Giant Shuriken
- customnpcs:npcSlingshot,5226,0,Slingshot
- customnpcs:npcMusket,5227,0,Musket
- DraconicEvolution:draconicPickaxe,5629,0,Draconic Pickaxe
- DraconicEvolution:draconicAxe,5630,0,Draconic Axe
- DraconicEvolution:draconicShovel,5631,0,Draconic Shovel
- DraconicEvolution:draconicHoe,5632,0,Draconic Hoe
- DraconicEvolution:draconicSword,5633,0,Draconic Sword
- DraconicEvolution:draconicBow,5634,0,Draconic Bow
- DraconicEvolution:wyvernPickaxe,5639,0,Pickaxe of the Wyvern
- DraconicEvolution:wyvernShovel,5640,0,Shovel of the Wyvern
- DraconicEvolution:wyvernSword,5641,0,Sword of the Wyvern
- DraconicEvolution:wyvernBow,5642,0,Bow of the Wyvern
- EnderIO:item.darkSteel_sword,5706,0,The Ender
- EnderIO:item.darkSteel_pickaxe,5707,0,Dark Pick,&#x1F534;
- EnderIO:item.darkSteel_axe,5708,0,Dark Axe,&#x1F534;
- exastrisrebirth:itemHammerMana,5875,0,Manasteel Hammer,&#x1F534;
- exastrisrebirth:itemHammerRF,5879,0,Flux-Infused Hammer
- exastrisrebirth:itemCrookRF,5880,0,Flux-Infused Crook,&#x1F534;
- exastrisrebirth:itemHammerThaumium,5885,0,Thaumium Hammer
- exastrisrebirth:itemHammerBound,5887,0,Bound Hammer
- exnihilo:hammer_wood,5711,0,Wooden Hammer
- exnihilo:hammer_stone,5712,0,Stone Hammer
- exnihilo:hammer_iron,5713,0,Iron Hammer
- exnihilo:hammer_gold,5714,0,Gold Hammer
- exnihilo:hammer_diamond,5715,0,Diamond Hammer
- ExtraUtilities:lawSword,5903,0,Kikoku
- ExtraUtilities:ethericsword,5910,0,Etheric Sword
- ExtraUtilities:erosionShovel,5911,0,Erosion Shovel
- ExtraUtilities:destructionpickaxe,5912,0,Destruction Pickaxe
- ExtraUtilities:defoliageAxe,5913,0,Healing Axe
- ExtraUtilities:temporalHoe,5914,0,Reversing Hoe
- ForbiddenMagic:TaintShovel,5923,0,Shovel of the Purifier
- ForbiddenMagic:TaintPickaxe,5924,0,Pickaxe of Distortion
- ForbiddenMagic:SkullAxe,5926,0,Axe of the Skulltaker
- ForbiddenMagic:MorphPickaxe,5927,0,Chameleon Pickaxe
- ForbiddenMagic:MorphSword,5928,0,Chameleon Sword
- ForbiddenMagic:MorphShovel,5929,0,Chameleon Shovel
- ForbiddenMagic:MorphAxe,5930,0,Chameleon Axe
- ForbiddenMagic:DiabolistFork,5932,0,Diabolist Fork
- ForbiddenMagic:BloodRapier,5939,0,Rapier of the Strix
- ForbiddenMagic:RidingCrop,5942,0,Riding Crop,&#x1F534;
- ForbiddenMagic:Dragonslayer,7172,0,Sword of the Dragonslayer,&#x1F534;
- ForestDay:tool.hammer,7306,0,Iron Hammer
- ForestDay:tool.knife,7324,0,Knife
- ForestDay:axe.flint,7325,0,Flint Axe
- Forestry:bronzePickaxe,4516,0,Survivalist's Pickaxe
- Forestry:bronzeShovel,4517,0,Survivalist's Shovel
- HardcoreEnderExpansion:schorching_pickaxe,4407,0,Scorching Pickaxe
- minecraft:iron_shovel,256,0,Iron Shovel,&#x1F534;
- minecraft:iron_pickaxe,257,0,Iron Pickaxe,&#x1F534;
- minecraft:iron_axe,258,0,Iron Axe,&#x1F534;
- minecraft:iron_sword,267,0,Iron Sword,&#x1F534;
- minecraft:wooden_sword,268,0,Wooden Sword,&#x1F534;
- minecraft:wooden_shovel,269,0,Wooden Shovel,&#x1F534;
- minecraft:wooden_pickaxe,270,0,Wooden Pickaxe,&#x1F534;
- minecraft:wooden_axe,271,0,Wooden Axe,&#x1F534;
- minecraft:stone_sword,272,0,Stone Sword,&#x1F534;
- minecraft:stone_shovel,273,0,Stone Shovel,&#x1F534;
- minecraft:stone_pickaxe,274,0,Stone Pickaxe,&#x1F534;
- minecraft:stone_axe,275,0,Stone Axe,&#x1F534;
- minecraft:diamond_sword,276,0,Diamond Sword,&#x1F534;
- minecraft:diamond_shovel,277,0,Diamond Shovel,&#x1F534;
- minecraft:diamond_pickaxe,278,0,Diamond Pickaxe,&#x1F534;
- minecraft:diamond_axe,279,0,Diamond Axe,&#x1F534;
- minecraft:golden_sword,283,0,Golden Sword,&#x1F534;
- minecraft:golden_shovel,284,0,Golden Shovel,&#x1F534;
- minecraft:golden_pickaxe,285,0,Golden Pickaxe,&#x1F534;
- minecraft:golden_axe,286,0,Golden Axe,&#x1F534;
- minecraft:wooden_hoe,290,0,Wooden Hoe,&#x1F534;
- minecraft:stone_hoe,291,0,Stone Hoe,&#x1F534;
- minecraft:iron_hoe,292,0,Iron Hoe,&#x1F534;
- minecraft:diamond_hoe,293,0,Diamond Hoe,&#x1F534;
- minecraft:golden_hoe,294,0,Golden Hoe,&#x1F534;
- RedstoneArsenal:tool.battleWrenchFlux,5745,0,Flux-Infused BattleWrench,&#x1F534;
- RedstoneArsenal:tool.swordFlux,5746,0,Flux-Infused Sword
- RedstoneArsenal:tool.shovelFlux,5747,0,Flux-Infused Shovel
- RedstoneArsenal:tool.pickaxeFlux,5748,0,Flux-Infused Pickaxe
- RedstoneArsenal:tool.axeFlux,5749,0,Flux-Infused Axe
- RedstoneArsenal:tool.sickleFlux,5751,0,Flux-Infused Sickle
- RedstoneArsenal:tool.bowFlux,5752,0,Flux-Infused Bow
- Sanguimancy:corruptedPickaxe,7345,0,Corrupted Pickaxe,&#x1F534;
- Sanguimancy:corruptedShovel,7377,0,Corrupted Shovel,&#x1F534;
- Sanguimancy:corruptedSword,7392,0,Corrupted Blade
- Sanguimancy:corruptedAxe,7416,0,Corrupted Axe,&#x1F534;
- Thaumcraft:ItemShovelThaumium,4249,0,Thaumium Shovel,&#x1F534;
- Thaumcraft:ItemPickThaumium,4250,0,Thaumium Pickaxe,&#x1F534;
- Thaumcraft:ItemAxeThaumium,4251,0,Thaumium Axe,&#x1F534;
- Thaumcraft:ItemSwordThaumium,4252,0,Thaumium Sword,&#x1F534;
- Thaumcraft:ItemHoeThaumium,4253,0,Thaumium Hoe,&#x1F534;
- Thaumcraft:ItemSwordElemental,4262,0,Sword of the Zephyr
- Thaumcraft:ItemShovelElemental,4263,0,Shovel of the Earthmover
- Thaumcraft:ItemPickaxeElemental,4264,0,Pickaxe of the Core
- Thaumcraft:ItemAxeElemental,4265,0,Axe of the Stream
- Thaumcraft:ItemHoeElemental,4266,0,Hoe of Growth
- Thaumcraft:ItemBowBone,4281,0,Bow of Bone
- Thaumcraft:ItemShovelVoid,4304,0,Void Shovel
- Thaumcraft:ItemPickVoid,4305,0,Void Pickaxe
- Thaumcraft:ItemAxeVoid,4306,0,Void Axe
- Thaumcraft:ItemSwordVoid,4307,0,Void Sword
- Thaumcraft:ItemHoeVoid,4308,0,Void Hoe
- Thaumcraft:ItemSwordCrimson,4325,0,Crimson Blade
- Thaumcraft:ItemPrimalCrusher,4328,0,Primal Crusher
- WitchingGadgets:item.WG_PrimordialHammer,5863,0,Primordial Warhammer - Aer,&#x1F534;
- WitchingGadgets:item.WG_PrimordialAxe,5864,0,Primordial Greataxe - Aer,&#x1F534;
- WitchingGadgets:item.WG_PrimordialSword,5865,0,Primordial Claymore - Aer,&#x1F534;
  </details>

**Comment by Grambosch** [comment]
^^ Wall of text . Und das soll ich nu abarbeiten ..grrr

**Comment by Grambosch** [comment]
Botania:starSword,7270,0,Starcaller,🔴
 Botania:thunderSword,7293,0,Thundercaller,🔴
 exastrisrebirth:itemHammerMana,5875,0,Manasteel Hammer
 ForbiddenMagic:RidingCrop,5942,0,Riding Crop,🔴
 ForbiddenMagic:Dragonslayer,7172,0,Sword of the Dragonslayer,🔴
 RedstoneArsenal:tool.battleWrenchFlux,5745,0,Flux-Infused BattleWrench,🔴 sowie alle anderen Bwrenches
 Sanguimancy:corruptedPickaxe,7345,0,Corrupted Pickaxe,🔴
 Sanguimancy:corruptedShovel,7377,0,Corrupted Shovel,🔴
 Sanguimancy:corruptedSword,7392,0,Corrupted Blade
 Sanguimancy:corruptedAxe,7416,0,Corrupted Axe,🔴
 WitchingGadgets:item.WG_PrimordialHammer,5863,0,Primordial Warhammer - Aer,🔴
 WitchingGadgets:item.WG_PrimordialAxe,5864,0,Primordial Greataxe - Aer,🔴
 WitchingGadgets:item.WG_PrimordialSword,5865,0,Primordial Claymore - Aer,🔴
Das bleibt übrig meiner Meinung nach wo man evtl was wieder aktivieren kann

**Comment by DerOliDE** [comment]
Ich war mal so frei die Textwall zu minimieren.

P.S.: Bei den ganzen Waffen und Tools die "extra" neben Tinkers dazu kommen sollten nur solche dabei sein die sich auch durch irgendein zusätzlichen Effekt lohnen ohne Tinkers total unnütz zu machen, da das imho ja noch immer unsere Haupt-Mod für diese Zwecke ist.

**Comment by Grambosch** [comment]
Jupp hab nach dem Aspekt sortiert ob es für eine Mod im Fortkommen wichtig , ob es eine besondere Funktion hat oder ob es ein Endgameitem des Mods ist das  kein Gamebreaker ist durchgeschaut und oben das bleibt über mMn

**Comment by Grambosch** [comment]
So , schreit wem noch was auffällt!

**Comment by DerOliDE** [comment]
Industriell hergestellte Kohle fehlt noch.

**Comment by Grambosch** [comment]
TSteelworks Ofen geht mir da durch den Kopf. Kümmer ich mich drum

**Comment by Grambosch** [comment]
Die BC additions Dusts müssen noch bearbeitet werden die fehlen fast überall zur verarbeitung

**Comment by Grambosch** [comment]
Clay Pan + Casting Basin+ 1 Ingot = 1 Plate forest mod

**Comment by Grambosch** [comment]
Charcoal kommt in den Indusmelter als herstellbare Ressource mit 5k RF kosten per Wood und ein Loam als 2te Zutat. Leider nimmt Minetweaker kein Oredict als input daher wird aus odWood ne ewige Liste :(.
Loam kriegt ein Rezept mit Sky Stone Dust  8 Dust + 1 Erde shaped wird zu 16 oder 32 Loam mal gucken das ist balancing

**Comment by DerOliDE** [comment]
Gegenvorschlag, ein Custom Item "Pile of Wood Logs" welches aus x \* odWood gecraftet und dann für das Induction Smelter Rezept verwendet wird, damit spamen wir nicht den Induction Smelter mit Rezepten zu und sparen uns zudem noch arbeit.

**Comment by Grambosch** [comment]
Gute Idee

**Comment by Grambosch** [comment]
Kann mir bitte wer helfen beim erstellen des Custom Items? Pile of Logs wäre ein guter Name und Texturen für sowas gibts in AMT.

**Comment by DerOliDE** [comment]
Hatte mir das die Tage schon mal angeguckt bzw. probiert aber auf Anhieb hatte es bei mir nicht funktioniert.

**Comment by Grambosch** [comment]
Wenn das dir Probleme macht hab ich ja noch Hoffnung das ich nicht ganz verkalkt bin ;)

**Comment by BakermanLP** [comment]
Schau dir die letzten commits von ProjectTETv8 an.  Da hatte ich items und Blöcke hinzugefügt

Edit... Ich hatte da den Mod Quadrum für Custom Blocks drinnen. Keine Ahnung was da hier so zur Verfügung steht?

**Comment by DerOliDE** [comment]
@BakermanLP Da kann ich kein ContentTweaker entdecken.

**Comment by BakermanLP** [comment]
Sorry, hatte Quadrum drinnen gehabt und nicht den Tweaker. Ich habe durch eine kurze Suche auf Github folgendes gefunden:
https://github.com/bigrice1018/AnotherWayToStart/blob/master/minecraft/contentScripts/Items.zs

Einzig unklar ist da noch, wie die Texturen dann im resources Ordner abgelegt werden müssen. Aber eventuell gibt es eine Fehlermeldung im Log beim Starten vom Client.

**Comment by Grambosch** [comment]
Grade wollte ich auf Quadrum verweisen , das kannte ich noch aus Regrowth glaub ich

**Comment by DerOli82** [comment]
Texturen sollten kein Problem sein, dass habe ich bei den Fluids schon einigermaßen gebacken bekommen, denke mal das die im selben Ordner liegen.

**Comment by DerOliDE** [comment]
Texturen sollten kein Problem sein, dass habe ich bei den Fluids schon einigermaßen gebacken bekommen, denke mal das die im selben Ordner liegen.

P.S.:Um bei dem Beispiel zu bleiben, hier liegen die Texturen: https://github.com/bigrice1018/AnotherWayToStart/tree/master/minecraft/config/contenttweaker/ContentTweaker-Resourcepack/assets/contenttweaker/textures

**Comment by DerOliDE** [comment]
Ich würde noch gern die Erze für die Seeds durch Custom Blöcke ersetzen, dann haben wir kein Problem mit den ganzen Erzen in den Inseln, die sich nicht wegkonfigurieren lassen. 

Wenn wir es uns einfacher machen wollen, nehmen wir nur einen Block als Katalysator für alle Erz Seeds und machen den dafür etwas teurer.

**Comment by Grambosch** [comment]
Block of Apatite ... passt thematisch wird für nix gebraucht und kann man ruhig auf 30-40 limitieren

**Comment by Grambosch** [comment]
Alheimer kommt da bitte noch die Woche der Customblock? Die Zeit rinnt

**Comment by DerOliDE** [comment]
erledigt...

**Comment by Grambosch** [comment]
Danke Hase

**Comment by Grambosch** [comment]
Custom Rezepte eingefügt für:
Loam,Dirt und Charcoal im Smelter. Vorerst Close
