### ISSUE TITLE
Limited Ressources löscht Limits erst nach relogg

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#191]
Wie im Milestones 0.7.3 schon erwähnt gibt es gelegentliche Aussetzer beim löschen des Limits von Limited Ressources , ging Meckerkopf eben genau so. Reloggen schaffte abhilfe

**Comment by DerOliDE** [comment]
Fehler auf dem Server beim Setzen
https://gist.github.com/DerOli82/0d75e2345eeb4e6afcc49dfd81ab7811

**Comment by DerOliDE** [comment]
Sollte ab 0.7.4 gefixt sein, bitte nochmal beobachten.

**Comment by Grambosch** [comment]
Hab gerade unter meinem Feld Redstone Erz mit dem TC Hammer und Silktouch abgebaut. Limits wurden erst resettet nach einem relog

**Comment by Grambosch** [comment]
Linksklicken und Erde abbauen mit einem Lapiserzblock hat meinen Counter für das Erz um 1 hochgesetzt bis ich reloggt hatte
