### ISSUE TITLE
Vein Miner

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#192]
Gedankenstütze für Oli!

**Comment by krakel** [comment]
Für was willst du diesen Mod einsetzen, wo es doch fast nichts zu minern gibt. Oder ist diese Gedankenstütze für was anderes gedacht?

**Comment by BakermanLP** [comment]
Veinminer kann eingesetzt werden für alle zu siebenden Produkte. Hammer auf
cobblestones usw

Uwe Dörl notifications@github.com schrieb am Do., 3. Nov. 2016, 15:58:

**Comment by Grambosch** [comment]
Gravel Sand... spart den Leuten nervige Hammertime!
