### ISSUE TITLE
Wechsel von MineTweaker zu CraftTweaker

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#193]
In der nächsten Version ( 0.7.4 ) tausche ich MineTweaker gegen CraftTweaker aus, da MineTweaker nicht mehr weiterentwickelt wird. Das Ganze ist eine _aus Raiders wird jetzt Twix_ Geschichte, weil CraftTweaker prinzipiell MineTweaker ist und nur von jemand anderes (jaredlll08) weiterentwickelt wird.

Warum erzähl ich das? 
Beim starten hatte ich jetzt keine Fehler aber bitte erhöhte Aufmerksamkeit, ob sich CraftTweaker unerwartet anders verhält.

**Comment by krakel** [comment]
Hatte mir vor einiger Zeit den Code mal angesehen. Das ist eine 1 zu 1 Übernahme mit nur minimalen Änderungen.

**Comment by DerOliDE** [comment]
Ist ja auch von MineTweaker geforkt ;-) Aber da sollte bspw. auch schon das script sorting drin sein und ich hoffe auch ein fix für das "nach Singleplayer geht kein Multiplayer mehr" Problem.

**Comment by krakel** [comment]
Das Scriptsorting habe ich bei denen vor 2 Monaten angestoßen (im Hypervolemia Forum). Darufhin haben die das im Github geändert. Allerdeing habe ich bei der Codeanalyse gemerkt, das das alles nichts nützt, da alles aus den Scripts in Javaklassen umgewandelt und dabei neu sortiert wird.

**Comment by DerOliDE** [comment]
Das habe ich schon vor einem Jahr (29.10.2015) bei MineTweaker "angestoßen", der Pull inkl Issue ist dort auch noch offen, an der Diskussion war auch Jaredlll08 beteiligt. ;-)

Ich hatte ja damals ein MineTweaker customized build mit Sortierung für uns gemacht, dass bis heute im Modpack ist und offensichtlich auch so funktioniert.

**Comment by DerOliDE** [comment]
Ich mach das mal dicht, wir müssen weiterhin ein custom build einsetzen. Siehe https://github.com/combak/ShatteredWorld/issues/195#issuecomment-259738066
