### ISSUE TITLE
Checkliste 0.8.0

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#194]
Ich habe den 0.8.0 Milestone jetzt für den 04.12.2016 terminiert, dass heißt für uns folgendes muss bis dann fertig sein:
- [x] World design inkl Quests etc.
- [x] Questbook.
- [x] Sämtliche offenen Issues.
- [x] Modliste, danach will ich keine neuen Mods hinzufügen und nur noch bei Bugs updaten.
- [x] Mod Konfigurationen inkl. Tweaker Gedöns.

Danach haben wir noch 1-2 Wochen fürs testing.

**Comment by Grambosch** [comment]
Questbuch: Quest "Universaltalent" kann ich nicht abschließen. Crafting Tast erfüllt  mit 100%  aber geht nicht weiter

**Comment by krakel** [comment]
Hast du Die Hüpfburg und Der Energiespeicher abgeschlossen?

**Comment by hellamie** [comment]
Oli du hast irgendwas gemacht..wenn mir ein Item runter fällt oder sonst wie auf den Boden kommt verschwindet das nach 3 sek. Löst sich einfach in Luft auf.

Bug oder soll das so?

**Comment by Grambosch** [comment]
Pay Attention for your Hopperhooks! Feature

**Comment by krakel** [comment]
Ich sehe in Project Ozone, das die dort den Autopacker durch den Compacter ausgetauscht haben. Gehe davon aus, das dieser Mod weniger Last produziert. Lizenz ist MMPL-1.0. Auch ist der etwas einfacher zu benutzen. Vielleicht eine Option?

**Comment by BakermanLP** [comment]
Hatte ich das nicht schon mal vorgeschlagen?

Uwe Dörl notifications@github.com schrieb am Do., 17. Nov. 2016, 20:57:

**Comment by DerOliDE** [comment]
Ja der war mal im Gespräch aber aus irgendeinem Grund hatte ich mich dagegen entschieden, ich schaue es mir aber nochmal an.

**Comment by Grambosch** [comment]
Ex Astris Erzausbeute (Ardite/Kobalt/Draconium) drastisch erhöht. Da kam ja gar nix raus

**Comment by BakermanLP** [comment]
Der alte githb issue vom compactor: https://github.com/combak/ShatteredWorld/issues/92

**Comment by hellamie** [comment]
geht es um den Autopacker?..da gibt es auch was von Botania ;)..benutze ich gerade beim testen..mus man aber Mana in der Tasche haben und vorher "Programmieren".

Helo Ring 2 der blaue

**Comment by Grambosch** [comment]
Leerenschiff wird zum WE fertig . Die Blood Magic Fraktion ist auch weit . Meinerseits sind die Questweltdesignsachen fertig dann

**Comment by krakel** [comment]
Dann will ich auch Vollzug melden. Das Questbuch ist fertig. Einleitungstext dazu auch fertig.

**Comment by Grambosch** [comment]
Mods hab ich abgehakt , 5 Tage vor Stichtag sollte da nix mehr rein oder raus

**Comment by DerOliDE** [comment]
Wie schaut es mitn Compator aus? ja, nein, vielleicht?

**Comment by Grambosch** [comment]
Nein , jetzt kurz vor knapp keine Änderungen mehr an der Liste.

**Comment by hellamie** [comment]
Creper und andere Monsterschäden müssen bitte noch in der Questwelt ausgeschaltet werden

**Comment by Grambosch** [comment]
So bautechnisch ist alles durch. Quest fehlt bei mir noch in der dunklen Festung. An den Brücken kann noch Deko gebaut werden damit es nicht so leer aussieht , muss aber nicht Issues sind eig. nur noch Olis und Alex´s offen

**Comment by hellamie** [comment]
pff,..nicht meine..nur weil es NPC sind...meine Questen sind fertig :)
