### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#195]
Bitte hier rein wenn was Crasht.

Gerade Client Crash beim Ind. Smelter setzen.
http://pastebin.com/nvPwFtpW

**Comment by Grambosch** [comment]
Das geht anscheinend bei allen TE Maschinen so ^^ Skriptfehler evtl?

**Comment by DerOliDE** [comment]
Liegt definitiv an den NBT Tags die man im minetweaker Script an die Maschine anhängt:
https://github.com/combak/ShatteredWorld/blob/master/scripts/ThermalExpansion.zs#L1122-L1126

Wollte mir jetzt mal anschauen wie MT das Rezept im default ausgibt um das zu vergleichen aber enttäuschenderweise kommt ein. **unknown recipe type for ThermalExpansion:Machine:3** raus. Wenn ich die Tags die dort angegeben sind versuche zu verwenden, bekommt MT das nicht geparst.

**Comment by DerOliDE** [comment]
Fehler gefunden, er erwartet bei SideCache ein Byte Array, nachdem ich das ändern wollte kam der nächste Fehler, dass im as byte[] nicht gefällt. 

Dazu habe ich mal bei CraftTweaker nachgefragt, ob Bug oder Feature: https://github.com/jaredlll08/CraftTweaker/issues/83

Es scheint auch ohne den SideCache Tag zu funktionieren aber kA was dann noch für Seiteneffekte auftreten können.

PS: Mit den Augments und der ID kann das aber auch nicht hinhauen, da sich die ID ja immer ändert.

**Comment by DerOliDE** [comment]
Von Jaredlll08 ist für die 1.7.10 keine Hilfe mehr zu erwarten, also wieder selbst Hand anlegen, als ob wir nicht schon genug zutun hätten....

**Comment by krakel** [comment]
Ich habe jetzt nicht in den Code geschaut. Hoffe aber das die nicht die Minecraft Rountinen zum Einlesen von NBT aus String Darstellung benutzen. Habe das beim neuen HQM gesehen. Meincraft kennt da kein byte[]. Die exportieren NBT Byte Array zu "byte[xy Bytes]" text und parsen alles zu einem Integer[] ein.

**Comment by krakel** [comment]
Ihhh, das sieht ja fast so aus.

```
Integer Array: name: [1, 2, 3, 4]
Byte Array:    name: [1b, 2b, 3b, 4b]
```

Minecraft NBT Parser wandelt beides zu Int[]!
Ob das hier so ist weiß ich nicht.

**Comment by DerOliDE** [comment]
`[1b, 2b, 3b, 4b]` Funktioniert jedenfalls nicht.
Da das ganze von MineTweaker geparst wird, wird das mit Sicherheit nicht 1:1 wie beim MC NBT Parser ablaufen.

**Comment by Grambosch** [comment]
BTW nach dem Crash steht die aufgebaute Maschine an der Wand und eine gedupte im Inventar

**Comment by DerOliDE** [comment]
So ich habe nen Backport vom 1.10.2 Fix für das Problem gemacht. Dann müssen wir halt wieder von CraftTweaker abschied nehmen und uns mit meinem custom build begnügen.

**Comment by jaredlll08** [comment]
Wenn du sagst "Von Jaredlll08 ist für die 1.7.10 keine Hilfe mehr zu erwarten, auch wieder selbst an ansprechen,
Dies ist meine Argumentation behing es, alles unter 1.10.2 ist einfach nicht mehr lebensfähig
http://www.blamejared.com/content/2016-11-10_15-08-04.png

Auch nur wissen, dass ich nicht unterstützen können benutzerdefinierte Versionen von Minetweaker, so dass, wenn irgendwelche Probleme auftauchen, stellen Sie sicher, sie mit einem offiziellen Build vor der Berichterstattung zu testen.

Auch ändern Sie bitte den Moddateinamen, also wissen die Leute nicht, um Probleme zu mir zu berichten

**Comment by DerOliDE** [comment]
Ich habe durchaus Verständnis dafür, dass man die Version 1.7.10 nicht länger supporten möchte, dennoch brauchte ich eine Lösungen für unser letztes 1.7.10 Modpack.

Den Custom Build, den ich jetzt für uns erstellt habe, werde ich selbst supporten bis das Modpack beendet ist.

**Comment by Grambosch** [comment]
We could also talk english if u want to. Your german translation doesnt work well .

**Comment by jaredlll08** [comment]
yea, sorry about that, didn't want to intrude by speaking english, and google translate is not the greatest :/
