### ISSUE TITLE
Feature Diskussion: Alternativer Launcher

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#196]
Ich weiß, dass ihr im Endstress seid (Oli, bitte mach langsam). Aber hier eine Feature Diskussion zu einem alternativem Launcher:

https://github.com/SKCraft/Launcher

Vorteile, die ich sehe:
- Komplett selbst konfigurierbar
- Komplett umgestaltbar
- Einfaches Modpack erstellen
- Einfache Struktur auf dem Webserver
- Deutlich vereinfachter Workflow bei Updates
- Verfügbar für Windows, Linux und MacOSx
- einzelne Mods optional kennzeichnen (langsame Rechner ohne Better Foilage z.B.)
- einzelne Mods von URL ladbar (Optifine)

Warum ich überlege einen alternativen Launcher zu verwenden:
- TechnicLauncher braucht "aufwendige" Struktur auf dem Webserver
- TechnicLauncher Bau Modpack komplexer
- CurseLauncher nur per Curselauncher konfigurierbar
- CurseLauncher nicht für Linux

Meine Idee war:
- Ein ProjectRET Launcher
- Design von uns
- Alle Modpacks (ab ProjectRETv1 oder noch davor)

Mehr Infos unter:
https://github.com/SKCraft/Launcher/wiki/Initial-Steps
https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks
https://github.com/SKCraft/Launcher/wiki/Optional-Features

**Comment by DerOliDE** [comment]
Der Gedanke einen anderen Launcher zu nutzen ist mir auch immer wieder gekommen, da ich mit dem Technic Launcher auch nicht wirklich zufrieden bin. Den SKCraft Launcher ist mir komplett neu aber die Features klingen wirklich vielversprechend.

P.S.: Keine Sorge ich Stress mich nicht und bin schon wieder auf dem besten Weg der Genesung. :)

**Comment by BakermanLP** [comment]
Freut mich zu hören

Dann kümmere ich mich mal um eine Testumgebung und den Launcher. Modpack
für PROJECTRET-AOT hatte 5 Minuten gedauert zu bauen aus dem laufenden
Client heraus. War super simpel.

Oliver notifications@github.com schrieb am Di., 22. Nov. 2016, 17:10:

**Comment by DJPTiger** [comment]
Der sieht auch schon ganz schick aus Baker. Vielleicht Schrift etwas zu klein.

Vielleicht kann man da auch die alten Maps mit Verknűfen so den Discort-Channel.

**Comment by Grambosch** [comment]
Da das ja fix kommt hat es sich ausdiskutiert : Close
