### ISSUE TITLE
Shortbow läßt sich ohne Large Plate bauen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#2]
Laut Tool Forge braucht man für den Shortbow auch ein Large Plate. Nur bietet das System den Bogen auch ohne dieses Teil an. Kann natürlich auch ein Bug in Tinker sein.

**Comment by krakel** [comment]
Oh sehe gerade, das es der Longbow ist, der diesen Fehler hat.

**Comment by combak** [comment]
Welches Material hast Du verwendet? Ich hab es gerade mit Iron Plate, Iron Bow Limb und Fiery Bowstring getestet und das hat funktioniert. (Oli)

**Comment by krakel** [comment]
Ja der Bow geht schon. Mit ist nur aufgefallen, das ein einfacher Bogen anbeboten wird, wenn man nur dessen Mats reinlegt. Aber das ist ja bei allen Tool Rezepten so. Man kann auch beim Hammer die Sachen für die Axt reinlegen und bekommt dann die Axt. Ich war nur etwas überrascht. Wir können das hier schließen.
