### ISSUE TITLE
Erklärungen eigene Dimension

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#200]
Mir fehlt irgendwie eine Erklärung aufm Lehrenschiff wie man mit jemanden zusammen in eine Dimension Bereisen kann bzw wie man Einladungen bzw Anfragen verschickt. Und der TP Befehl für die Eingeladenen fehlt auch noch als Erklärung.

**Comment by DerOliDE** [comment]
Zu den Commands, es gibt drei die für Spieler und Dimensionsbesitzer relevant sind:

**Whitelist:** 
Regelt wer in die Dimension darf.
```
/yadm manage whitelist add <spielername>
```
**Reisen via Border** 
Funktioniert z.Z, nicht, da gibt es irgendein Bug der erst außerhalb der Entwicklungsumgebung aufgetaucht ist.
```
/yadm manage travel set <abreise border north|east|south|west> <dimensionsname|id> [<ankunft border north|east|south|west>
```
**Teleport zu Dimensionsbesitzer** 
Teleportiert einen in die Dimension des Spielers, sofern man natürlich auf der Whitelist steht.
```
/yadm tpto <spielername>
```

Den ganzen Kram dazu werde ich sowohl ins Forum schreiben und dem NPC noch ein paar Zeilen dazu sagen lassen.

**Comment by DerOliDE** [comment]
Der tpto Befehl ist jetzt verfügbar, das Reisen via Border hat noch irgendein Bug :-S

**Comment by DerOliDE** [comment]
Mathilda <Meisterin der Welten> erzählt einen jetzt etwas über die Chat Befehle, wenn man den Dialog "Wie komme ich auf Inseln anderer Spieler?" auswählt.

**Comment by DerOliDE** [comment]
Ganz vergessen zu schreiben, es gibt jetzt eine Quest "Meine kleine Welt" die einen zu Mathilda führt. Damit ist der Issue imho erledigt.
