### ISSUE TITLE
Feature Diskussion: Server Start

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#201]
Ich wollte jetzt hier mal die Diskussion Anregen wie es mit dem Serverstart ablaufen wird.

Ich sehe schon die Bilder wie eine lange Schlange an Spielern durchs Lehrenschiff laufen wird und die Begrüßungsquest abläuft.

Ich weiß jetzt nicht wie stark der Server Belastet wird wenn da jeder so fast zur selben Zeit eine eigene Dimension erstellt?

Meine Gedanken sind zum Beispiel das alle die im Vorraus die Möglichkeit von uns haben schon mal eine Welt zu erstellen das auch schon mal machen sollten. Zwar noch nichts Bauen aber schon mal generieren lassen um eventuell Serverlast weg zu nehmen.

**Comment by hellamie** [comment]
es wurde mal von gestaffeltem einlass geredet...erst 10 dann wieder 10 dan wieder 10 oder so in der art

**Comment by DerOliDE** [comment]
Das gestaffelte würde nur funktionieren, wenn es die Möglichkeit gibt, die Spieler Anzahl ingame zu erhöhen, ob das geht weiß ich nicht, ansonsten fällt das flach.

Man könnte auch die Tage schon im Forum nachfragen, wer mitmacht, welche Teams etc. und die Dimensionen schon vorgenerieren.

**Comment by Grambosch** [comment]
Die Whitelist kann man ingame ändern , also evtl eine Anmeldeliste und die dann nach und nach abarbeiten?

**Comment by DJPTiger** [comment]
Apropos Welten vorgenerieren, gibt es da die Möglichkeit einen Wechselnden See zu verwenden?

So wie ich minecraft kenne ist ein Fester See drin der im Moment jede Spieler Insel gleich aussehen läßt.

**Comment by DerOliDE** [comment]
An der Generierung der Inseln kann ich nichts ändern.

**Comment by Grambosch** [comment]
Die Diskussion ist in Forum gewandert ergo close
