### ISSUE TITLE
Forest Day

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#203]
Ich versuche gerade ein Holzzahnrad zu machen aber die Werkbank Arbeitet nicht. Ein Holzbrett liegt links in der Mitte drin (Zieht sich alleine mit Shift dahin und ob Eiche oder Birke ist auch egal) und die Stonefeile ist recht drin.

Es wird aber nichts hergestellt.

**Comment by DerOliDE** [comment]
@Nedelosk Wie war das nochmal mit dem alles komplett durchtesten? .....

**Comment by Nedelosk** [comment]
Behoben und liegt im  Ordner
