### ISSUE TITLE
Forest Day

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#205]
Jetzt hängt die Zahnrad Produktion in 7303:5 fest Startprodukt=Endprodukt

**Comment by DJPTiger** [comment]
So habe jetzt mal weiter durch getestet. Egal welche Pfeile oder welcher Prozess (Einzelschritt oder Automatisch) immer kommt 7303:5 bei raus was das erstemal bearbeitete Holzbrett ist. Witziger Weise sogar wenn ich Pflasterstein rein Werfe.

Es ist sogar egal welche der Werkbänke oder sogar wie weit das Zahnrad von der Fertigung ist immer kommt 7303:5 raus.


Hier nöchmal der Hinweiß an Grayal, werde ich aber noch ein Beitrag auf machen. Holzkohle Quest zum einen sind es keine Holzblöcke die gestapelt werden müssen und zum anderen braucht man ein Feuerzeug, was man zu dem Zeitpunkt nicht Bauen kann.

Eimer Produktion Funktioniert.

Ausser das im Lagerfeuer auch ohne Treibstoff angefangen wird zu schmelzen (Von der Optik her und das man sich verbrennen kann.), ist soweit alles sonst kurz von mir gecraftet und getestet worden soweit ich die Funktionen Nachvollziehen konnte.

**Comment by DerOliDE** [comment]
@Nedelosk Langsam ist das nicht mehr lustig, die Grundfunktionalität muss gewährleistet und getestet werden, nicht erst nachdem ich es ins nächste Modpack Update gestopft habe, sondern bevor Du mir das Mod Update überhaupt erst hochlädst.

**Comment by krakel** [comment]
Das sollte eigentlich mit einer normale Fackel gehen. Ich glaube mich zu erinnern, das das Feuerzeug dazu nicht vorgesehen war. Werden das heute Abend testen.

**Comment by DJPTiger** [comment]
Was mir noch aufgefallen ist wo ich aber nicht weiß ob Bug oder gewollt oder nicht Lösbar. Das Holzzahnrad von Larson kann nicht dafür genutzt werden um eine Form zu Gießen.

**Comment by DJPTiger** [comment]
Ok Fackel geht doch. Sorry

**Comment by DJPTiger** [comment]
Mit der Werkbank lassen sich ja auch Eisenplatten machen da ist aber ein falscher Ausgabe Slot gewählt. Die Platte wird nach unten in die Schleife abgegeben und nicht nach rechts.

**Comment by DerOliDE** [comment]
Ist in der 0.4.12 bereits gefixt, kommt mit dem nächsten Update voraussichtlich heute.

**Comment by DerOliDE** [comment]
**Singleplayer:**
- Spiel crasht wenn aus dem Charcoal Pile die Ash wird: https://gist.github.com/DerOli82/ad913a10b83eced3d69c9ddcd4eaa7fb
- Der Charcoal Pile ist nach beenden und neustart nicht mehr sichtbar, sprich der Multiblock ist transparent.

Im Multiplayer treten diese Fehler nicht auf.

**Comment by Nedelosk** [comment]
Behoben in der neuen Version.

**Comment by DerOliDE** [comment]
Und 20 mal alles durchgetestet?
