### ISSUE TITLE
Quest-Book

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#206]
Hier der Hinweiß an Grayal.

Holzkohle Quest "Der Rauchende Berg" in "Aller Anfang ist schwer"
zum einen sind es keine Holzblöcke die gestapelt werden müssen und zum anderen braucht man ein Feuerzeug, was man zu dem Zeitpunkt nicht Bauen kann.

"Töpfern ist so schön" in "Aller Anfang ist schwer"
bitte das Rezept mit einbauen von der Barrel da NEI es nicht anzeigt. Links und Rechts senkrecht 3 Holzbretter und unten in der mitte eine Stufe aber alles eine Holzart.

**Comment by DerOliDE** [comment]
Zur Holzkohle, das Ding wird bzw. kann auch mit einer Torch (links Klick) angezündet, sofern das im Questbook nicht eindeutig ist ggf. mit in die Erklärung mit einbauen.

**Comment by krakel** [comment]
Schau ich mir an.
Wieso wird denn die Barrel im NEI nicht angezeigt? Aber dieses Rezept sollte unabhängig davon jeder kennen.

**Comment by DJPTiger** [comment]
Wieso sollte jeder das Rezept kennen? Selbst ich habe gesucht im Netz und nicht gefunden und dann auf Bakers SkyBlock Videos geschaut. Es gibt auch welche unter umständen die noch nie was mit ModPacks oder ExNehilo zu tun hatten.

Im NEI wird nur das Chisel Rezept angezeigt.

**Comment by DJPTiger** [comment]
Was mir noch aufgefallen ist wo ich aber nicht weiß ob Bug oder gewollt oder nicht Lösbar. Das Holzzahnrad von Larson kann nicht dafür genutzt werden um eine Form zu Gießen.

Ok Fackel geht doch. Sorry

**Comment by krakel** [comment]
Bei aller Liebe zu Gesangsverein, aber:
1. wer bis jetzt nur Vanilla gespielt hat, der sollte uns meiden; das Pack ist auf schwer getrimmt
2. das Questbuch ist kein Guide, eher eine Beigabe; man ist nicht genötigt dem Buch zu folgen

**Comment by Grambosch** [comment]
Das Holzzahnrad ist nicht als Vorlage für eine Form gedacht das geht erst mit dem EnderIO Steingear.Aprospos Ex Nihilo Rezepte Ex Astris disabled die und nimmt die in seinem Reiter identisch auf

**Comment by DJPTiger** [comment]
@Grambosch ok Verstanden

@krakel ich weiß wofür das Quest-Book ist und den Zweck, soviel zu Punkt 2 und zu Punkt 1 klar ist das Mod-Pack auf schwer getrimmt, nur ganz erlich man muß immer mit Neueinsteigern rechnen, aber das Thema hatten wir auch schon vor 1,5 Jahren. Deswegen mach wie Du meinst und fertig.

Meine Meinung dazu Schwer ok aber deswegen Neulingen die Tür vor der Nase zu zu Hauen wäre eine Frechheit.

**Comment by Grambosch** [comment]
Dann muss der Neueinsteiger mal beißen und vergiß nicht das das ein Comm Server ist da ist meist wer der weiterweiß

**Comment by krakel** [comment]
Alles korrigiert, auch das Rezept für den Barral.
