### ISSUE TITLE
Server Absturtz 12:23

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#208]
Server wurde geschlossen nachdem ich den Befehl "/yadm tp 1001" eingegeben habe welche ja für das Nether bzw. Innerer Kern ja steht.

Edit: War von meiner Welt aus das ich den Befehl eingegeben habe.

**Comment by Grambosch** [comment]
1001 ist der Nether da gibts noch Bugs Oli ist dran. Questwelt ist 1000 glaub ich und Lobby ist 0

**Comment by DerOliDE** [comment]
Server startet wieder und gewöhnt Euch zum testen den tp Befehl ab, den habt Ihr später nicht mehr. ;-)

**Comment by DJPTiger** [comment]
Wenn wir den Später nicht mehr haben, wie kommen wir dann von der eigene Welt weg?

**Comment by DerOliDE** [comment]
Über den südlichen WorldBorder kommt man zurück in die Lobby und vor da kommt man in den Nether und die Questwelt. Der tpto Befehl bleibt erhalten und die Möglichkeit den restlichen drei Himmelsrichtungen ein Reiseziel zu anderen Spielern zu zuweisen.

**Comment by DJPTiger** [comment]
Teste ich dann mal heute Abend.

**Comment by DerOliDE** [comment]
Bitte erst nach dem nächsten Update. :D
