### ISSUE TITLE
Informationstext

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#209]
Ideen, Vorschläge oder Anregungen was wir noch in diesen https://github.com/combak/ShatteredWorld#information Informationstext schreiben können, um das Modpack kurz und knackig zu beschreiben?

**Comment by DJPTiger** [comment]
Vielfältige Technische Magie mal anders. 

Test die Vielfältigkeit der Technischen Magie mal auf Realistische Art und Weise.

**Comment by Grambosch** [comment]
Survival , Magie und Technik!
Euch sind ander Modpacks zu einfach? Hier seid ihr richtig!
Alles will euch ans Fell, jede Maschine überlegt ihr euch 2 mal zu bauen da euer Material eingeschränkt ist.
Dies ist ein Multiplayer  optimiertes Modpack mit eigens erstellten Mods nur für Server (YADM und Limited Ressources!).
