### ISSUE TITLE
ForestDay arbeitet nicht mit Ore Dictionary zusammen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#21]

**Comment by DerOliDE** [comment]
Cross Ref: https://github.com/ForestDay/Forest-Day/issues/9

**Comment by Grambosch** [comment]
Closed bei Alheimer. Daher nehm ich mal an fixed und kommt bald

**Comment by DerOliDE** [comment]
Bitte erst schließen wenn es bei uns drin ist und auch getestet wurde das der Fehler weg ist, nicht das wir irgendetwas vergessen/übersehen.

**Comment by DerOliDE** [comment]
Fixed in 0.1.6beta
