### ISSUE TITLE
Goldzahnrad/Kompressionsdynamo

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#210]
Im Quest-Buch ist die Aufgabe bei den Maschinen das mal alle Dynamos aus Thermal Expansion Craften soll. Alles gehen bis auf den Kompressionsdynamo.

Grund:

In allen Rezepten bis auf Kompressionsdynamo werden die Zahnräder von Thermal Foundation verlangt.
Beim Kompressionsdynamo aber die von Buildcraft.

Die Zahnräder im Spiel sind alle auf Thermal Foundation ausgelegt.

**Comment by DerOliDE** [comment]
Im nächsten Update korrigiert.
