### ISSUE TITLE
Quest-Buch

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#211]
## **Bereich "Der Geist in der Maschine"**

Aufgaben:
"Der Basisspeicher"
"Die Kneifzange"
"Das Fass im Boden"
"Gebundene Sonne"
"Die Böse Seele"
"Die Verschränkung"
"Die Hilfskraft"
Die Aufgaben wurden von mir Erfüllt konnte sie aber nicht abgeben, aber FrauCreeper in meinem Team konnte sie abgeben.

Aufgabe:
"Der gelbe Blitz"
Die Aufgabe habe ich gemacht und er erkennt es nicht weder geladen noch ungeladen.

## **Bereich "Das Hologramm"**

Aufgaben:
"Der geladene Kristall"
"Der Mikrochip"
"Klein aber Fein"
"Der Mikrokomputer" <- Nicht mein Rechtschreibfehler sondern der im Buch
"Der Meister"
"Der Erbauer"
"Die Steckkarten"
"Der große Speicher"
Die Aufgaben wurden von mir Erfüllt konnte sie aber nicht abgeben, aber FrauCreeper in meinem Team konnte sie abgeben.

## **Die Zauberhafte Blume"**
"Das grüne Monster"
Die Aufgaben wurden von FrauCreeper Erfüllt konnte sie aber nicht abgeben, aber ich im Team konnte sie abgeben.

Edit: Erweitert 15:05 Uhr

**Comment by krakel** [comment]
```
# Allow every single player in a party to claim the reward for a quest. Setting this to false will give the party one set of rewards to share.
B:MultiReward=true
```
Eigentlich sollten alle die Quests abgeben können. 
Für Fehler im HQM Mod kann ich nichts, für die Rechtschreibfehler schon.
Von der Struktur der Quest und auch im JSON ist nichts auffälliges zu sehen.

**Comment by krakel** [comment]
"Der gelbe Blitz" korrigiert, NBT Eintrag mußte ignoriert werden. Bei den anderen Sachen habe ich keine Idee. An den Questitems sind auch keine Personalisierungen dran.

**Comment by DJPTiger** [comment]
Scheind dann wohl was intern im Quest-Book nicht zu stimmen weil bei Ars Magica auch schon viele Quest.

Ich werde dann aber nicht weiter Aufzählen, ausser Rechtschreibfehler oder sonstiges.

**Comment by hellamie** [comment]
Habe gerade mit Grayal alles druchgetestet...wir können die Fehler nicht reproduzieren.

**Comment by DJPTiger** [comment]
Ok dann weiß ich Bescheid.

**Comment by krakel** [comment]
Sag mal, hattest du auch genug Platz im Inventar um den Loot aufzunehmen. Wenn dein Inventar voll war, kannst du die Quests nicht abschließen!

**Comment by DJPTiger** [comment]
Der Button wird erst garnicht Angezeit zum Abschließen.

Auch in anderen Bereichen der selbe Fehler von Ars Magica, Thaumcraft und so weiter. Habe Neustart so verschiedene Modis versucht.

Aber jetzt zu einem anderen Bug:

Der grüne Daumen -> Der Braumeister
--------Wird das Ale Yeast nicht anerkannt.

**Comment by krakel** [comment]
Ah, Mist, das wird in den AppleMilkTea Maschinen hergestellt. Das wird nicht als craften erkannt.

**Comment by krakel** [comment]
Rezepte von AppleMilkTea kontrolliert.
