### ISSUE TITLE
Apple&Milk&Tea

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#212]
Von Apple&Milk&Tea läst sich das Manual Charge Generator herstellen, weil man kein Chalcedony Gear nicht zur Verfügung steht.

Aufgefallen durch die Quest:
Der grüne Daumen -> Das Experiment

**Comment by krakel** [comment]
Ich glaube das ist nur ein Anzeigproblem. Man muß hier ein anders Gear nehmen, glaub ich.

**Comment by krakel** [comment]
Das Gear muss noch korrigiert werden. Alle anderen Maschinen werden mit eine Iron Gear gemacht!

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/commit/386bc22f967d0b697dc365b92911b6682da790cc
