### ISSUE TITLE
VeinMiner

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#216]
Was aufgefallen ist.

Tinker Spitzhacke mit Hammer-Upgrade funktioniert nicht bei Bruchstein. Die Anderen Sachen wie Kies und Sand nicht getestet.

Auch nicht getestet aber was man Prüfen könnte:

Tinker Schaufel, Tinker Extruser, Tinker Hammer mit jeweils Hammer-Upgrade ob die Funktionieren.

**Comment by DerOliDE** [comment]
Soweit ich das beurteilen kann, wird das generell nicht mit VeinMiner funktionieren, da man nur explizit Items zuordnen kann und die Tinker Upgrades machen aus dem Tool kein neues Item. Ich kann via VeinMiner nicht feststellen was für Upgrades in einem Tinker Tool stecken.

**Comment by DerOliDE** [comment]
Lässt sich leider nicht ändern, wenn jemand doch eine zündende Idee hat bin ich ganz Ohr.
