### ISSUE TITLE
seltsames Kiln verhalten

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#217]
Wenn man einen Kiln stellt wird er als Oak angezeigt.
Wenn der Stapel noch nicht voll ist und man ihn wieder abbauen will, verschwinden die Blöcke einfach ohne zu droppen.

**Comment by DJPTiger** [comment]
Würde vorgestern und gestern auch schon von einem Spieler in Gegenwart von Oliver, Grayal, Hellamie, FrauCreeper und mir auch schon in Discord-Channel erwähnt. Ich glaube Lars war auch da.

**Comment by DerOliDE** [comment]
Gibt es hierzu schon was neues gefixtes?

**Comment by Nedelosk** [comment]
Liegt im Ordner

**Comment by DerOliDE** [comment]
Ausgezeichnet schaue ich mir an

**Comment by krakel** [comment]
Übrigens zum Verschwinden. Sie tun es nicht, sie tauchen nur als normales Oak im Inventar auf.

**Comment by Nedelosk** [comment]
Ok dann ist es doch nicht behoben

**Comment by Nedelosk** [comment]
Jetzt sollte es aber behoben sein
