### ISSUE TITLE
Appel,Milk,Tea

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#218]
Citrus Battery Rezept 1 (Eisennugget, Goldnugget und Yuzu) funktioniert nicht

**Comment by hellamie** [comment]
ich meine irgendwann mal gelesen zu haben das geht nur mit den AMT Nuggets...

keine Ahnung ob man da noch was ändern kann

**Comment by Grambosch** [comment]
Im Testbetrieb hab ich die aber gebaut.ich schau heut abend mal

**Comment by DerOliDE** [comment]
Ist schon gefixt, es gibt Varianten die Funktioniert haben, dazu gibt es 8 verschiedene Rezepte.
