### ISSUE TITLE
Copper Dust kann nicht in einer normalen Furnace zu Cupper gebrannt werden

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#22]
Iron Dust geht. Andere habe ich noch nicht getestet.

**Comment by DerOliDE** [comment]
Wenn es nach mir geht sollte überhaupt kein Erz im normalen Ofen zu schmelzen sein für was gibt es denn die Tinkers Schmelze. ^^

**Comment by krakel** [comment]
Ja du mußt aber mal Anfangen. Und es ist ja Verschwendung die Ore Verdopplung nicht zu nutzen.
Coppel Gravel und Coppen Sand gehen auch nicht. Aluminium, Gold, Nickel, Iron geht complett.

**Comment by DerOliDE** [comment]
Ich hab schon angefangen nur eben noch nicht alles fertig siehe Ore Processing Tabelle ;-) Ich kann die Ex Nihilo Sachen aber einfach mal vorziehen.

**Comment by krakel** [comment]
Tin und Copper läßt sich nicht schmelzen. Die anderen geht alle.

**Comment by DerOliDE** [comment]
Joa steht auch so exakt in der Ore Processing Tabelle weiter runter war ich noch nicht gekommen.

**Comment by BakermanLP** [comment]
Ich halte die Arbeit hier für vergebene Liebesmühe. Die Leute werden zwar ca. 2 Stunden aufgehalten, bis sie eine Tinkers Schmelze haben, aber dann bauen sie wahrscheinlich einen Pulverizer / SagMill (habe mir das Rezept noch nicht angesehen) und packen dann das Ergebnis in den Ofen (welchen auch immer). An der Stelle zu viel Arbeit für "zu wenig". Meine Meinung!

BTW ... wenn man das nicht in der Schmelze macht, sondern direkt in den Ofen packt, bekommt man nur halb so viel raus. Ist eigentlich schon Strage / Dummheit / Verschwendung genug.

**Comment by Grambosch** [comment]
Wenn ich es richtig verstanden hab geht es primär um eine Vereinheitlichung der Enprodukte das aus jeden Ofen das gleiche Kupfer rauskommt. TE modden per Mine/modtweaker ist zZ eh...doof

**Comment by DerOliDE** [comment]
Ich mach quasi das via Script was der GT Unificator via Mod macht. ;-) Ja das ist eine Heidenarbeit aber imho ist es dann für das Spiel angenehmer, wenn man nicht x Varianten vom selben hat, was einem das Inventar und Lager zumüllt.

Direkt im Furnace schmelzen wird nicht gehen, das werde ich alles deaktivieren, die Schmelze soll das erste sein was man benötigt um Erze zu verarbeiten.

**Comment by DerOliDE** [comment]
Ich fasse das der Übersicht halber auch mal zum Ore Processing ( https://github.com/combak/ShatteredWorld/issues/61 ) zusammen
