### ISSUE TITLE
Thaumcraft Inventory Scan

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#220]
Können wir mit dem nächsten Update diesen Mod aufnehmen?
https://minecraft.curseforge.com/projects/thaumcraft-inventory-scanning

**Comment by DerOliDE** [comment]
Zum nächsten nicht, das gibt es eventuell noch heute aber der Wunsch zu der Mod wurde auch schon von anderer Seite geäußert.

P.S.: Was neues aber auch erst, wenn wir die Probleme im Griff haben, ;)

**Comment by Grambosch** [comment]
Drauf damit in der 1.1 !
