### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Tr4pp3r** [combak/ShatteredWorld#222]
https://gist.github.com/DerOli82/0d1146eb3343525e1e37bf162cccf22a

/Edit DerOli82
Ich habe das mal in eine lesbarere Form gebracht.

**Comment by DerOliDE** [comment]
Soweit ich das recherchieren konnte ist das ein Minecraft/Forge Problem, darauf habe ich keinen Einfluss. 

Wenn das häufiger Auftritt mal auf die aktuellste Java 8 Version updaten.
