### ISSUE TITLE
Combustion Generator - Ender IO

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#223]
Der Combustion Generator von Ender IO hat bei Ethanol einen Treibstoff Verbrauch von 15 mb/t und ein Wasserverbrauch von -1 mb/t. Das Wasser verschwindet direkt und es wird keine Energie Produziert.

Das wurde auch bei Sharkuns beobachtet und bei mir an der Basis auch das Spielchen.

Zum Anschauen bei mir steht der an der Baumfarm.

Regulär sollten 40 RF/t auf 600kRF Gesamtmenge Produziert werden laut der Ender IO Wiki. Der Verbrauch von 15 mb/t an Ethanol stimmt auch. Wasserverbrauch steht leider nicht in der Wiki hier:
http://wiki.enderio.com/Combustion_Generator

**Comment by Grambosch** [comment]
Scheint am Forestry Sprit zu liegen mit Rocketfuel läuft der auf 160 RF

**Comment by DerOliDE** [comment]
Ich kann keine Möglichkeit entdecken bei EnderIO die Werte für den Generator zu verändern, alternative gibt es den Compression Dynamo aus Thermal Expansion, der auch mit Fuel und Coolant läuft.

**Comment by DerOliDE** [comment]
Es gibt kein neueres stable update für EnderIO, von unserer Seite ist da nichts machbar und es gibt brauchbare Alternativen für Bio Ethanol als Treibstoff, daher closed.
