### ISSUE TITLE
Pilze auch bei Licht

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#226]
Können wir das Wachstum von Pilzen auch bei Licht erlauben?
https://github.com/BakermanLP/ProjectPhoenix/issues/110#issuecomment-87644526
Der Link beschreibt das Licht für Netherwart, das will ich nicht verändern. Das Kreuzen funktioniert in Dunkelheit. Nur für eine Farm wäre es schöner die Pilze normal mit anderen Crops zu benutzen.

**Comment by DerOliDE** [comment]
Ist meiner Meinung nach nix was zwingend geändert werden müsste.

**Comment by Grambosch** [comment]
Wie immer gibts da was bei Pam... CLose und aus
