### ISSUE TITLE
Compacting Drawers

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#228]
Wie heute im Chat gelesen komprimieren die Glowstone zu Blöcken. Das war ja so nicht gewollt. Direkt mal gegenchecken was damit nocht geht

**Comment by DerOliDE** [comment]
Habe Stichprobenartig ein paar Ingots durchprobiert, die lassen sich nicht komprimieren. Das Glowstone habe ich unterbunden.
