### ISSUE TITLE
Netherquarzore

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#229]
Wird in 1001 nicht generiert womit die Agricraftpflanze nicht geht, was tun wir da?

**Comment by DerOliDE** [comment]
Im Zweifel wieder ein Rezept via Laser, wie bei den anderen Erz Blöcken, die wir mal drin hatten.

**Comment by DerOliDE** [comment]
Besser wäre eigentlich auch hier Apatite zu nutzen, damit es limitiert ist.

**Comment by Grambosch** [comment]
Gut mach ich

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/commit/45ca6bcaa3be8496caf783029d951cf999f4b5d3
