### ISSUE TITLE
Magma Crucible auch als Schmelze für Dusts

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#231]
Ist es eine Überlegung wert auch diese Maschine für das Schmelzen von Dusts zu erweitern. Gerade für das Late Game könnte eine höher Ausbeute beim Umschmelzen von Nuggets interessant sein.

**Comment by DerOliDE** [comment]
Mal in den Raum geworfen: Du weißt was für ne Heidenarbeit es war das ganze geschmelze allein für Tinkers zu konfigurieren?

**Comment by krakel** [comment]
Zumindest das Einschmelzen der Nuggets ist schon sehr Zeitaufwendig. Vielleicht gibt es da eine Beschleunigung ander Art. Allerdings kann man auch mehrere Schmelzen bauen. War nur so eine Idee. Kein Ding!

**Comment by DerOliDE** [comment]
Schon mit Pyrotheum versucht? Das ganze schmilzt ja je nach benötigter Schmelztemperatur und verfügbarer Hitze mehr oder weniger schnell ein. Man könnte noch ein Fuel mit mehr als 4000° hinzufügen, die Frage ist was soll das dann sein?

**Comment by hellamie** [comment]
Mann kann aber auchm einfach alles so lassen..und mal ein wenig chillen ;)

**Comment by Grambosch** [comment]
Gabs da nicht ne TE Maschine die eine Strombetriebene Smeltery war?

**Comment by DerOliDE** [comment]
Der Magma Crucible, so wie es im Titel steht :)

**Comment by krakel** [comment]
Nein Induction Smelter und Magma Cruicile arbeiten nicht mit ExAstris Zeugs und den Nuggets.

**Comment by Grambosch** [comment]
Thermal Smeltery geisterte da im HInterkopf rum

**Comment by DerOliDE** [comment]
War das nicht ne extra Mod?

**Comment by krakel** [comment]
du meinst das hier?
https://mods.curse.com/mc-mods/minecraft/227661-thermal-smeltery

**Comment by Grambosch** [comment]
Für meine Begriffe ist die Smelterz mit Aerotheum und ähnlichem schnell genug so:
Vote for Close
