### ISSUE TITLE
NPC für Tierprodukte

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#233]
Tiger hat vorgeschlagen für die deaktivierten Tiere als Alternative einen Händler mit Tierprodukten einzuführen. Das wäre primär für Milch und Eier aber die ganzen Fleischsorten der Standardviecher könnte man auch noch anbieten.

**Comment by hellamie** [comment]
Hühnchen und Eier bekommt man auch aus der Pam Falle für Tiere.  Ansonsten kann man bei vielen Rezepten die Milch durch Soja ersetzen. Leder bekommt man von Lycanit-Mobs. Wolle gibt es vom Feld in Form von Cotton. In der Theorie kann man alles umgehen.

Aber prinzipiell habe ich nichts dagegen.

**Comment by DerOliDE** [comment]
Milch wird noch für eine Quest benötigt, da gäbe es auch theoretisch den Weg über Bienen aber als Ersatz für die deaktivierten Tiere wäre es halt nett.

**Comment by Grambosch** [comment]
Dann lass die Farm halt "Tiere" verkaufen mit Spawneiern...

**Comment by DerOliDE** [comment]
Die Tiere sind deaktiviert, dass heißt alles was spawnt ist auch sofort wieder weg.

**Comment by Grambosch** [comment]
Hmpf diese Deaktivierung ist an mir vorbeigegangen...und ich such immer wieder mal Farmvieh...

**Comment by DerOliDE** [comment]
Hatte ich irgendwann mal deaktiviert weil wir laufend ~1300 Ocelots auf dem Server hatten bei gerade mal 10-15 Spielern, was wohl den komischen Temperatureinstellungen von FWG zu verdanken ist.

**Comment by DerOliDE** [comment]
1x Iron Coin für Milch und Ei
2x Iron Coin für Beef und Pork
3x Iron Coin für Leder und Wolle

Einwende?

**Comment by DerOliDE** [comment]
Steht.
