### ISSUE TITLE
Waterbee beim Händler

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#234]
Es würde gefragt, ob man auch die Waterbee beim Händler anbieten könnte. Da ich keine Ahnung von Bienen habe frage ich lieber mal, ob das ohne Nebeneffekte möglich ist.

**Comment by krakel** [comment]
Wieso ist das notwendig? Man kann sich doch alle Bee Hive herstellen.
Aber es wäre auch kein Problem. Wir bieten doch sowieso einige Sachen beim Händler an.

**Comment by hellamie** [comment]
habe ich die vergessen?. Dachte der Händler würde alle Standard Bienen anbieten.

Dann füg die doch bitte einfach ein.

**Comment by DerOliDE** [comment]
Gibs nun zu kaufen.
