### ISSUE TITLE
Client Absturz

### ISSUE THREAD

**Issue by DJPTiger** [combak/ShatteredWorld#235]
Ich hatte in Storage Draws geschaut etwas schnell gedreht und davor die Baumfarm ans Lager angeschlossen.

http://pastebin.com/fcWGUrbw

**Comment by DerOliDE** [comment]
Übeltäter gefunden sind die Backpacks.

/Edit 
Bekomme es lokal nicht reproduziert ggf. einfach mal die Mod auf verdacht updaten. ^^

**Comment by DerOliDE** [comment]
Im nächsten Patch wird die Mod geupdatet, mal im Auge behalten, ob der Fehler noch auftritt.
