### ISSUE TITLE
Botania Planze wurde gebonemealt

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#237]
Crash Report
https://gist.github.com/DerOli82/d5847b7ca731484e64cdfb8c5be7f82b

Scheint ausschließlich auf dem Server aufzutreten.

**Comment by DerOliDE** [comment]
see: https://github.com/squeek502/AppleCore/issues/48

**Comment by DJPTiger** [comment]
Oli Du hast das Falsch verstanden. Und zwar kannst Du wohl Normlerweise Blütenblätter auf den Boden werfen von Botania und so die Blumen wieder mit Knochenmehl Hochwachsen lassen.

AgriCraft und die Crops wären damit nicht mal im Spiel.

**Comment by hellamie** [comment]
ok..dan habe ich das auch falsch verstanden.

nehmt doch bitte dafür die Blume die die andern Wachsen lässt

**Comment by DerOliDE** [comment]
Und jetzt nochmal in Itemnamen (englisch) und Aktionen die auch mich den Fehler *einfach* reproduzieren lassen.

**Comment by DJPTiger** [comment]
Also es Handelt sich wohl um die Petal (ID:Botania:petal) die Farbe ist wohl egal. Die haben Sie auf den Boden geworfen oder gepflanzt (normaler Grasblock oder erde Block) und dann mit Knochenmehl versucht wachsen zu lassen. Soll wohl ein "normaler Weg" sein um die Botania Blumen zu vermehren. Da man aus einer Blume 2 Petal raus bekommt und man nur ein Petal zum Wachsen lassen braucht.

TripleEffecte hat diese Aussage Bestätigt weil Sie dann wohl für die Abstürzte davor verantwortlich ist.

**Comment by DerOliDE** [comment]
Okay damit kann ich es reproduzieren, ist weiterhin ein Server only Fehler und der von AppleCore verlinkte Issue ist auch weiterhin der identische Fehler.

**Comment by DerOliDE** [comment]
Backport des "Bugfix" auf 1.7.10 https://github.com/DerOli82/AppleCore/commit/8c7bb219619153cfe09c0a4a8f96cdd8d79f2e4c
