### ISSUE TITLE
Falsche Quest Geber Namen

### ISSUE THREAD

**Issue by Nedelosk** [combak/ShatteredWorld#238]
Die Quests des Meister des DN und des Bäckers im Zwergenhafen haben noch den Falschen NPC Namen als abgebe NPC angegeben.

**Comment by DerOliDE** [comment]
Wie sind die korrekten Namen? Einen Tyltran und Raven scheint es ja nicht mehr zu geben

**Comment by Nedelosk** [comment]
Der Bäcker heißt Lanosch und der Meister des DN Dirin Kristallherr.

**Comment by DerOliDE** [comment]
erledigt
