### ISSUE TITLE
Questbook - Die Verrückten - Neutronium Ingot wird nicht erkannt

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#239]
Weitergeleiteter Fehlerbericht von Streetdigger2:
sebi1112 in Questreihe 12. DIe Verrückten - Neutronium Ingot wird nicht erkannt
Hab schon eins gecheatet, hat aber nicht funktioniert. Auch neue Nuggets in die Schmelze packen und das Ingot gießen brachte nichts, das Ingot wird nicht erkannt.

**Comment by krakel** [comment]
ja weil wir das gießen und nicht craften, wird korrigiert

**Comment by krakel** [comment]
https://github.com/combak/ShatteredWorld/commit/0edd033132511640a48627ece764d4ee3a01ea19
