### ISSUE TITLE
Heftige CPU-Last

### ISSUE THREAD

**Issue by GrayPanther** [combak/ShatteredWorld#242]
Wärend des Spieles fängt es schlagartig an zu ruckeln und der Blick auf meine CPU-Last sagt mir das mein AMD 8-Kern mit 95- 100% Prozent Auslastung zu kämpfen hatt! Ich hatte das Problem jetzt schon 3 mal und andere Spieler scheinen das Problem auch zu haben! Man muss dann das Spiel mit Taskmanager beenden, da nix mehr reagiert! Fehlerlog gibt es scheinbar auch keine, daher ist die Ursache für mich unklar!

**Comment by DerOliDE** [comment]
Bitte nach dem aktuellen Update nochmal verifizieren.

Vielleicht ist es nur unglücklich von Dir formuliert aber Minecraft ist nicht in der Lage Deine komplette CPU auszulasten, es ist technisch nur in der Lage ein Kern zu belasten. Wenn wirklich die komplette CPU ausgelastet wird, liegt das nicht oder nicht allein an Minecraft.

P.S.: Tritt das im Single- oder Multiplayer auf?

**Comment by GrayPanther** [comment]
Laut meinem Prozessmanager war Minecraft die einzige Instanz die lief und die ganze Auslastung verursachte! Ich werde jetzt den Log im Hintergrund laufen lassen, vielleicht find ich so die Ursache! 
Und ich spiel nur auf dem Communityserver! Sollte es nochmal aufteten melde ich mich wieder!

**Comment by GrayPanther** [comment]
So der Fehler ist wieder aufgetreten! Scheint ein Problem mit dem Log zu sein! Hier zum Beweis!
![error 2](https://cloud.githubusercontent.com/assets/24848187/21644973/727aa414-d290-11e6-94bb-fdf545ec91c5.jpg)

**Comment by BakermanLP** [comment]
Ich bin mir nicht sicher, was du mit dem Log meinst. Du denkst, dass das geöffnete Log das Problem ist? Das Log ist nur ein Thread, sofern ich den Java Code richtig verstehe, der am Minecraft Prozess, hängt. Bietet dein Prozess Explorer hier auch eine Threaded Ansicht, bzw. die Sub Prozesse und Threads. Ich denke, dass die abgestürzte Instanz hier noch so lange irgendwie mit läuft, bis das Log Fenster geschlossen wird.

**Comment by GrayPanther** [comment]
Interresant war/ist, das Minrcraft geschlossen ist (auf dem Bild zu sehen und nur der Log (oben links) offen war! Nachdem ich ihn gewaltsam geschlossen hatte sackte die Auslastung sofort auf normal ab!

**Comment by BakermanLP** [comment]
Zum Vergleich, da ich hier mehr Tools habe dafür eine Liste der Prozesse unter Linux:
```
           |-mate-terminal(25163)-+-bash(18553)-+-less(32481)
           |                      |             `-pstree(32480)
           |                      |-bash(28118)
           |                      |-bash(32128)---java(32238)-+-java(32281)-+-{java}(32282)
           |                      |                           |             |-{java}(32283)
           |                      |                           |             |-{java}(32284)
           |                      |                           |             |-{java}(32286)
           |                      |                           |             |-{java}(32287)
           |                      |                           |             |-{java}(32288)
           |                      |                           |             |-{java}(32289)
           |                      |                           |             |-{java}(32290)
           |                      |                           |             |-{java}(32291)
           |                      |                           |             |-{java}(32292)
           |                      |                           |             |-{java}(32293)
           |                      |                           |             |-{java}(32294)
           |                      |                           |             |-{java}(32295)
           |                      |                           |             |-{java}(32296)
           |                      |                           |             |-{java}(32297)
           |                      |                           |             |-{java}(32298)
           |                      |                           |             |-{java}(32299)
           |                      |                           |             |-{java}(32300)
           |                      |                           |             |-{java}(32306)
           |                      |                           |             |-{java}(32307)
           |                      |                           |             |-{java}(32314)
           |                      |                           |             |-{java}(32315)
           |                      |                           |             |-{java}(32329)
           |                      |                           |             |-{java}(32416)
           |                      |                           |             |-{java}(32417)
           |                      |                           |             |-{java}(32419)
           |                      |                           |             |-{java}(32429)
           |                      |                           |             |-{java}(32430)
           |                      |                           |             |-{java}(32433)
           |                      |                           |             `-{threaded-ml}(32432)
           |                      |                           |-{java}(32239)
           |                      |                           |-{java}(32240)
           |                      |                           |-{java}(32241)
           |                      |                           |-{java}(32242)
           |                      |                           |-{java}(32243)
           |                      |                           |-{java}(32244)
           |                      |                           |-{java}(32245)
           |                      |                           |-{java}(32246)
           |                      |                           |-{java}(32247)
           |                      |                           |-{java}(32248)
           |                      |                           |-{java}(32249)
           |                      |                           |-{java}(32250)
           |                      |                           |-{java}(32251)
           |                      |                           |-{java}(32252)
           |                      |                           |-{java}(32253)
           |                      |                           |-{java}(32256)
           |                      |                           |-{java}(32258)
           |                      |                           |-{java}(32267)
           |                      |                           |-{java}(32285)
           |                      |                           |-{java}(32302)
           |                      |                           |-{java}(32303)
           |                      |                           `-{java}(32304)

```
Das ist die Ausgabe von pstree, also Prozesse, die Prozesse gestartet haben.

Laufen tun dann zwei Prozesse:
```
michael  32238 11.5  3.3 4550452 270156 pts/1  Sl+  15:21   0:19 java -jar ProjectRET-Launcher.jar
michael  32281  135 41.0 7801660 3295560 pts/1 Sl+  15:22   3:09 java -Djava.library.path=/opt/sklauncher/./temp/extract/1483539725434 
```

Wie die Prozessverwaltung unter Windows (in deinem Fall Windows 7) läuft, wie sie dargestellt wird usw. Keine Ahnung.

Aber das sind nur meine Beobachtungen unter Linux.

**Comment by GrayPanther** [comment]
Ich muss mal schauen, ob ich beim nächsten Auftreten des Fehlers mehr Infos bekomme! Ich war ersteinmal froh, das die Druck-Funktion klappte! Das Fenster zu schließen ist immer ein ziemliches rumgewürge!

**Comment by GrayPanther** [comment]
Das ist alles, was das Programm dazu sagt:
![error 3](https://cloud.githubusercontent.com/assets/24848187/21648763/666ef2e2-d29f-11e6-8e2e-259a1358b218.jpg)

**Comment by BakermanLP** [comment]
Command Line ist das was aufgerufen wurde, also der Launcher. Der wiederrum startet das Logfenster und das eigentliche Spiel als Kind Prozesse. Hier sieht man leider nur den Vater Prozess. Ich werde mal schauen, wie es daheim bei mir unter Windows aussieht.

**Comment by GrayPanther** [comment]
Ist ok! Ich hoffe wir finden den Fehler bedenk aber bitte, das ich nicht so die Ahnung von der Computerthermik habe! Das letzte was ich da hatte war DOS-Grundkenntenisse!

**Comment by hellamie** [comment]
mal ne ganz blöde frage..habt ihr einen Viren Scanner drauf? meiner macht gerne Echtzeit-Scann und da ist Minecraft fürn Popo. Gelöscht Problem weg.

**Comment by GrayPanther** [comment]
Virenscanner ist drauf ,aber soweit alles auf manuell gestellt! Echtzeitscan ist deaktiviert, eben wegen solcher Probleme!

**Comment by DerOliDE** [comment]
Besteht das Problem noch bzw. gibt es hier noch irgendwas zu besprechen oder Lösungsansätze? Wenn nicht dann schließe ich das hier.

**Comment by GrayPanther** [comment]
Ich Zwangschließe den Log beim Start und hab seit dem keine Probleme mehr! Wenn kein anderer das Problem hatt, kann man das schließen!
