### ISSUE TITLE
Inventory Tweaker optional im Launcher

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#243]
Wurde gewünscht ist kein Problem, daher bitte optional mit default aktiv.

Hatte ich ja schon im Discord gesagt, hier nur als kleiner Reminder damit es nicht untergeht.

**Comment by BakermanLP** [comment]
Kümmere mich darum .

Oliver <notifications@github.com> schrieb am Sa., 31. Dez. 2016, 10:25:

**Comment by DerOliDE** [comment]
Erledigt
