### ISSUE TITLE
Fehler inkl lag spike

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#248]
https://gist.github.com/DerOli82/0c1f60f175f23ad288c9cf4444d63312

**Comment by DerOliDE** [comment]
Lag Spitze verursacht von HQM (Detection Task)

![screenshot_20170125_181520](https://cloud.githubusercontent.com/assets/5699429/22301300/d99cc474-e32a-11e6-95ae-0f33b7478ef6.png)

**Comment by DerOliDE** [comment]
HQM ist die Tage auch im Stall Report aufgetaucht:
https://gist.github.com/DerOli82/59c071bb4d970d450d1b540232f88784

**Comment by Grambosch** [comment]
Auch nix mehr aufgefallen? Dann close
