### ISSUE TITLE
Maple Syrup /Pams Harvestcraft

### ISSUE THREAD

**Issue by LukeSkywaIker** [combak/ShatteredWorld#249]
Da ich keine Möglichkeit finde Maple Syrup automatisiert herzustellen, wäre ein neues Rezept hilfreich, z.B Forestry Maple(ExtraTrees) durch die saw/sagmill mit secondary output. Die Forestry Trees müssen auch erst erzüchtet werden, also nicht so einfach.  (Forestry macht Pams, aber nicht Maple da dieser im Stamm entsteht, farming station und golems[nicht verifiziert] bauen stämme ab, aber aus diesen lässt sich kein syrup herstellen). Auch wenn man Syrup gefülltes Holz mit der Axt abbaut, erhält man keine Syrup. Ausschließlich über Rechtsklick am Stamm. Dank und Gruß!

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/commit/6e26476866c67d37395acff9b0e1b69a49672071
