### ISSUE TITLE
Drawer können nur als oak drawer gebaut werden.

### ISSUE THREAD

**Issue by Teji85** [combak/ShatteredWorld#252]
Völlig egal welches Holz benutzt wird (getestet mit dark oak, spruce und birch) es kommt immer ein oak drawer dabei raus. Sowohl im vanilla crafting table als auch im tinkers. Dies ist ebenso bei den 1x2 und 2x2 drawern der Fall.
![2017-01-04_16 14 19](https://cloud.githubusercontent.com/assets/16488963/21647015/e9fad7e0-d298-11e6-96bc-d9ab25d7e353.png)

**Comment by Teji85** [comment]
Das Problem kann vorerst mit dem worktable von forestry umgangen werden. Dieser bietet eine Auswahlmöglichkeit an falls verschiedene Produkte möglich wären.

**Comment by DerOliDE** [comment]
An UniDict liegt es nicht, mit nem Update von StorageDrawers hat es sich auch nicht erledigt und die Oak Drawer haben alle Rezepte mit OreDict plankWood.

Die Suche geht weiter.
