### ISSUE TITLE
Keine Forbidden Magic Shards im Nether

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#253]
Die Shards von Forbidden Magic ( https://ftbwiki.org/Envy_Shard#See_Also ) tauchen nicht im Nether auf. Ich vermute die Mod prüft ob die DimensionsId -1 ist und führt dann die entsprechenden Aktionen für den Shard drop aus.

Wie lösen wir das Problem?

**Comment by Grambosch** [comment]
https://github.com/SpitefulFox/ForbiddenMagic/issues/103
Mal gucken was er sagt

**Comment by DerOliDE** [comment]
Zu mindestens ein Teil scheint auf die id zu prüfen
https://github.com/SpitefulFox/ForbiddenMagic/blob/master/src/main/java/fox/spiteful/forbidden/FMEventHandler.java#L163-L164

**Comment by DerOliDE** [comment]
Mit dem nächsten Update packe ich schon einmal meine customized Variante mit rein, bis der Mod Autor einen neue build macht.
