### ISSUE TITLE
Entity spawn limit

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#254]
Ich weiß zwar noch nicht *ob* es funktioniert aber mal so als Vorschlag, ein limitierte Spawn von Entitys pro Dimension bspw. 30-40 Monster und 10-20 Animals

**Comment by Grambosch** [comment]
Supported

**Comment by DerOliDE** [comment]
Soweit ich das bis jetzt überflogen habe, könnte man sogar droppende Items limitieren bspw. auf 200 pro Dimension, damit sollten so Probleme wie ein geplatzter Drawer dem Server schnuppe sein, nur der Spieler verliert halt sein Zeug. :D

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/issues/256 Ein Grund das mit den Limits zu forcieren

**Comment by DerOliDE** [comment]
Ja ich hoffe heute fertig zu werden, nur bestimmte Entities nicht spawnen zu lassen ist leider nicht ganz so trivial wie ich dachte. ;(

**Comment by DerOliDE** [comment]
Noch einmal ausgegraben für eine Diskussion welche Entites noch reglementiert werden müssen.

Im Gespräch waren noch:
- Villager
- Dryad (AM2)
- Blue Slime (Tinkers)
- King Slime (Tinkers)

Ich wäre auch gewillt bspw. dem Wither einen Freifahrschein zu spendieren, dass er immer spawnt egal wie viele Mobs auf der Map sind.

Eine Übersicht über alle vorhandenen Entites gibt es hier: https://github.com/combak/ShatteredWorld/blob/master/docs/ChoosableEntities.txt

P.S.: Eventuell den Mob spawn auch von 30 auf 50 erhöhen.

**Comment by krakel** [comment]
Der Wither ist ein gewollt gerufener Boss und sollte schon spawnen wenn man ihn ruft. Ich würde das begrüßen.
Das Limit auf 50 erhöhen wäre auch nicht schlecht, da aktuell der Blood Magic Altar schlecht wieder aufgefüllt werden kann. Wenn die Belastung für den Server passt, warum nicht.
Bei den anderen Entities habe ich keine Probleme/Erfahrungen.

**Comment by DerOliDE** [comment]
So sieht meine aktuelle Filterliste aus:
```json
{ "type": "entityspawn", "typeLimit": {
    "monster": 50
    },
    "entityLimit": {
    "Item": 300,
    "Bat": 5,
    "Chicken": 5,
    "Cow": 5,
    "MushroomCow": 5,
    "Pig": 5,
    "Sheep": 5,
    "Squid": 5,
    "EntityHorse" : 5,
    "Wolf" : 5,
    "Ozelot": 5,
    "Villager": 5,
    "arsmagica2.MobDryad": 2,
    "TConstruct.EdibleSlime": 5,
    "TConstruct.KingSlime": 2,
    "WitherBoss" : -1,
    "arsmagica2.BossEnderGuardian": -1,
    "arsmagica2.BossWaterGuardian": -1,
    "arsmagica2.BossArcaneGuardian": -1,
    "arsmagica2.BossNatureGuardian": -1,
    "arsmagica2.BossEarthGuardian": -1,
    "arsmagica2.BossFireGuardian": -1,
    "arsmagica2.BossAirGuardian": -1,
    "arsmagica2.BossLightningGuardian": -1,
    "arsmagica2.BossLifeGuardian": -1,
    "arsmagica2.BossWinterGuardian": -1
    }
}
```

-1 heißt das diese Entities von jeglicher Filterung ausgeschlossen werden. Habe ich irgendwas wichtiges vergessen?

**Comment by krakel** [comment]
Jetzt muß noch nachträglich meckern, sorry. Es fehlen die Blood Magic Elementare und Demons.

**Comment by DerOliDE** [comment]
Welche davon betrifft das und habe ich irgendwas vergessen?
AWWayofTime.MinorDemonGruntGuardian
AWWayofTime.BileDemon
AWWayofTime.MinorDemonGruntFire
AWWayofTime.MinorDemonGrunt
AWWayofTime.MinorDemonGruntIce
AWWayofTime.WingedFireDemon
AWWayofTime.MinorDemonGruntGuardianWind
AWWayofTime.MinorDemonGruntGuardianFire
AWWayofTime.MinorDemonGruntWind
AWWayofTime.MinorDemonGruntGuardianIce
AWWayofTime.MinorDemonGruntGuardianEarth
AWWayofTime.IceDemon'
AWWayofTime.MinorDemonGruntEarth

AWWayofTime.AirElemental
AWWayofTime.EarthElemental
AWWayofTime.WaterElemental
AWWayofTime.ShadeElemental
AWWayofTime.FireElemental
AWWayofTime.HolyElemental

/Edit
Hier sind alle Mobs die es gibt:
https://gist.github.com/DerOli82/45c45985f8d06fa94ce231b0dd3aee73

**Comment by krakel** [comment]
AWWayofTime.FallenAngel
AWWayofTime.BileDemon
AWWayofTime.BoulderFist
AWWayofTime.ShadeElemental
AWWayofTime.SmallEarthGolem
AWWayofTime.Shade
AWWayofTime.LowerGuardian

**Comment by DerOliDE** [comment]
mountainmobs.geonach
