### ISSUE TITLE
Forestry Sappling in Oak Barrel (Ex Astris)

### ISSUE THREAD

**Issue by LukeSkywaIker** [combak/ShatteredWorld#255]
Kann man es so einstellen das Apple Oak Sapplings (Oak wird zu Apple Oak in der Forestry Farm) im Oak Barrel zu Dirt werden?

**Comment by Grambosch** [comment]
Das ist per custom Rezept abgedeckt über Compost

**Comment by LukeSkywaIker** [comment]
oops, hab dank!
