### ISSUE TITLE
Blood Magic Mobs lassen sich nicht beschwören

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#256]
Habe jetzt 3 Versuche gemacht, die Blitzevent starten, aber die Mobs kommen nicht. Hängen die eventuell an der allgemeinen Mobsperre mit dran?

**Comment by Grambosch** [comment]
Welche Mobsperre?

**Comment by krakel** [comment]
Was weiß ich, Kühe spawnen ja auch nicht.

**Comment by Grambosch** [comment]
Creativ auf dem Server in der 0 aufgebaut erscheint kurz und verschwindet wieder. Auf der SP Welt gehts

**Comment by Grambosch** [comment]
Tierspawn ist nun mal testhalber an und siehe da Dämonen spawnen korrekt

**Comment by DerOliDE** [comment]
Sollte jetzt gegessen sein.
