### ISSUE TITLE
Keine Platten aus Schmelze

### ISSUE THREAD

**Issue by Blaxard** [combak/ShatteredWorld#257]
Seit ein paar Tagen bekomme ich keine Platten mehr aus der Schmelze, obwohl der ClayPan drin liegt.
Genug geschmolzene Erze sind auch in der Schmelze vorhanden. Vor einer Woche ging es noch.

**Comment by Grambosch** [comment]
Platten läuft bei mir ich geh mal lokal schauen

**Comment by DerOliDE** [comment]
Wäre noch interessant zu wissen, welche Platte Du gießen wolltest.

**Comment by Grambosch** [comment]
Reispfanne macht keine Platten :)
