### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#258]
Der Client stürtzt ab wenn ich auf dem Server joine oder eine Welt lade das ist die Fehlermeldung:

http://pastebin.com/u3zdkUNK

Ich habe maxPermSize schon auf alle möglichen Werte gesetzt und es ändert sich nichts. Ich denke es liegt daran das es in Java als feature entfernt wurde.

**Comment by Mateholiker** [comment]
http://pastebin.com/hAqaaKqE

Hier ist nochmal ein ander Absturzbericht

**Comment by DerOliDE** [comment]
Da läuft etwas beim rendern schief, benutzt Du das default Modpack oder hast Du noch Optifine mit drin? Bei Optifine kann die Multicore und Smooth Chunk Loading Option diesen Fehler verursachen.

**Comment by Mateholiker** [comment]
Ja Optifine zu entfernen scheint das problem zu lösen vielen dank
