### ISSUE TITLE
Bedrockiumingot

### ISSUE THREAD

**Issue by PeterFausB** [combak/ShatteredWorld#259]
Das Rezept für die Herstellung von Bedrockiumingots funktioniert nicht. Wenn man die Zutaten wie angegeben in den Inductionsmelter legt startet dieser nicht.

**Comment by DerOliDE** [comment]
Im Singleplayer funktioniert es bei mir ganz normal, die Brenndauer ist extrem lang, eventuell durch Lag stark verzögert? Bitte nochmal irgendwer im Multiplayer testen.

**Comment by Grambosch** [comment]
Basic Ind. Smelter geht tatsächlich nicht. Ich vermute da der nur 48k RF speichert das Rezept aber 50 verlangt. Geht dann erst ab nem aufgerüsteten

**Comment by DerOliDE** [comment]
Dann schließe ich das hier als Feature statt Bug, da nur die Maschine zu schwach dimensioniert ist aber das Rezept grundsätzlich funktioniert.
