### ISSUE TITLE
Tinkers einige Casts bieten keine Materialien im Tooltip

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#26]
folgende Casts haben keine erlaubten Materialien und können somit nicht benutzt werden:
- Tough Rod Cast
- Bow Limb Cast

**Comment by DerOliDE** [comment]
Über die restrictions in Iquana Tweaks muss ich nochmal drüber schauen da kamen neue Materialen rein und damit ggf. Probleme

**Comment by DerOliDE** [comment]
Bei den Tough Rods sind z.Z. nur Wood, Stone, Slime und BlueSlime vorgesehen und bei den Rods noch der Iron Rod.

Wieso er beim Limb Cast nichts macht is mir aber ein Rätsel, dafür ist noch Iron und Steel eingetragen. Selbes Problem beim Crossbow Limb Cast.

Die restlichen Iquana Tweaks Restrictions habe ich für die 0.5.3 überarbeitet.

**Comment by krakel** [comment]
Vergiss bitte Obsidian nicht bei den Rods. Reinforece 3 ist immer eine gute Wahl.

**Comment by DerOliDE** [comment]
Kannst Du als Binding nehmen, als Griff hatte ich nicht vor Obsidian zuzulassen

**Comment by krakel** [comment]
es gibt Werkzeuge und Waffen die kein Binding haben, als Binding nimmt man ja normal eher was aus Papier

**Comment by DerOliDE** [comment]
Papier gib es erst recht nicht. ;)

**Comment by BakermanLP** [comment]
Tooltips werden anscheinend richtig bei den Pattern angezeigt, aber bei den Casts nicht. Jedoch zeigt NEI bei den "USES" die möglichen Materialien an. Meiner Ansicht nach Close.

**Comment by DerOliDE** [comment]
Ref: https://github.com/combak/ShatteredWorld/issues/131#issuecomment-131110414

Closed zwecks Übersicht.
