### ISSUE TITLE
Rezeptfehler Extra Trees-Logs

### ISSUE THREAD

**Issue by GrayPanther** [combak/ShatteredWorld#260]
Wenn man die Stämme von Extra Trees in Bretter umwandeln will, bekommt man immer Pink Ivory Bretter raus, auch im Forestry Worktable! Nur in der Sagmill werden es die richtigen Bretter! Getestet mit Apple Wood und Cherry Wood!

**Comment by Grambosch** [comment]
Confirmed

**Comment by Grambosch** [comment]
Sieht erst man nach nem Scriptfehler aus aber in deinen Scripten rate ich nur :)

**Comment by DerOliDE** [comment]
Die Pinke Bedrohnung hat doch was xD

**Comment by Grambosch** [comment]
Da wird auf jeden fall der Pink Generator glücklich

**Comment by DerOliDE** [comment]
Da läuft irgendwas ganz eigenartiges, was ich noch nicht begreife. Wenn ich mir das Original Rezept via Minetweaker exportieren lasse, sieht das so aus:
```
recipes.addShapeless(<ExtraTrees:planks:14>.withTag({meta: 14}), [<ExtraTrees:log>.withTag({meta: 0})]);
```
Mal abgesehen von den unnötigen Tags heißt das Rezept das man ein Plank für ein Log bekommt, was ja so auch schon nicht stimmt, weil man original 4 Planks raus bekommt. Wenn ich mir nun die Original Rezepte schnappe und den Output mit * 2 angebe, bekomme ich wieder nur eine Sorte Planks raus. -.-

**Comment by Grambosch** [comment]
http://minetweaker3.powerofbytes.com/forum/viewtopic.php?f=4&t=585 evtl hilft da ja was weiter ...
