### ISSUE TITLE
Eventuell für die Zukunft, Binnie Genetics

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#261]
Habe mit mal die Genetics 2.0 angeschaut. Oh man, das ist übel erschwert worden.
1. braucht sehr viel Energie
2. dauert richtig lange, gutes Highend Feature
3. ist umständlicher, man muß jetzt Larven züchten um neue Bienen zu züchten

**Comment by Grambosch** [comment]
Guck ich mir an mit Pressure Pipes.

**Comment by Grambosch** [comment]
ging nicht wegen Flutterlyzerbug @Nedelosk gibts da nen Fix oder sonst close bitte

**Comment by Nedelosk** [comment]
Es gibt einen Fix, man müsste nur das Schmetterlings Plugin in Forestry wieder Aktivieren. Und dann einfach das spawn limit der Schmeterlinge auf 0 setzen.
