### ISSUE TITLE
gerade einen Crash gehabt

### ISSUE THREAD

**Issue by Bastian1991** [combak/ShatteredWorld#263]
https://gist.github.com/DerOli82/297d499b3b8cd33991039ba62841a40a

/Edit DerOli82
Text in lesbarere Form gebracht

**Comment by DerOliDE** [comment]
Habe gerade am Scroreboard rumgespielt nur eigenartig das es Dich abschießt.

**Comment by Bastian1991** [comment]
hmm ich weiß es nicht :-)

**Comment by DerOliDE** [comment]
Keinerlei Ansätze hierfür und scheinbar nicht mehr aufgetreten. Bei Bedarf wieder öffnen.
