### ISSUE TITLE
Eventuell für die Zukunft, AE2 rv3

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#264]
Ich weiß das es da nur die Beta gibt. Habe aber diese Version schon in anderen großen Packs gesehen. Hat ein paar nette Verbesserungen, aber nichts dramatisches.

**Comment by DerOliDE** [comment]
Auf eine Beta Version, egal was für eine Mod, werde ich nur updaten, wenn diese einen zwingend notwendigen Patch enthält.
