### ISSUE TITLE
Ein Anzeige bug bezogen auf ein Rezept

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#265]
Von TheSnowyChickens (http://www.bakermanlp.de/viewtopic.php?f=3&p=1592):
Bei NEI steht , das man im Induction Smelter (Thermal Exp.) aus 1x Sand + 1x Iron dust (Egal welcher) = 2x Eisen bekommt.

Das ist aber leider ne Lüge. :(

Ps : Beim erst aufploppen des Fensters mit dem Rezept werden mir nur schnell 2x Iron dusts angezeigt , dies verwandelt sich aber wieder zurück bei den anderen varianten der duste auf 1x.

**Comment by Grambosch** [comment]
Habs gerade im SP auf und da steht 1Sand + 2 Dust gleich 2 Barren insofern korrekt, Da gibts auch kein Script das da was dran dreht

**Comment by DerOliDE** [comment]
Bekomme ich auch nicht reproduziert, bei mir wird die korrekte Anzahl angezeigt, sowohl im SP als auch im MP.

![screenshot_20170115_124451](https://cloud.githubusercontent.com/assets/5699429/21962213/9dac09be-db20-11e6-8538-4f363dd50160.png)
