### ISSUE TITLE
Mob Events

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#266]
Welche wollen und können wir mal wieder einschalten?

**Comment by Grambosch** [comment]
Im Wechsel per Woche evtl so 1-2 , zu testen ist nur alles was mit Explodieren und Lava zu tun hat.
Hells Fury zB

**Comment by Grambosch** [comment]
Vorschlag für die ersten 2  :March of the Gorgomites und Winged Venom

**Comment by DerOliDE** [comment]
Coming next:
Poop Party.
The Swarm
