### ISSUE TITLE
Änderung Quests Ars Magica letzte Bosse

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#267]
Ich wollte über diese Bosse das Drachenherz vor dem Besuch im End zugänglich machen. Diese sind besonders schwer und nicht von jedermann schaffbar. Die Lootinformation wird erst sichbar, wenn man bis zu diesen Bossen vorstößt.
Dazu müßte der vorletzte Boss dieses droppen. Auch könnte er wiederholbar sein. Dieser Boss wird im Nether in der Lava beschworen.
Der letzte Boss kann nur im End beschworen werden. Braucht auch nicht wiederholbar sein. Als Drop hier was gutes aus Avariata.

Ein zweites Drachenherz bekommt man geschenkt, wenn im Nether der Drachen gekillt wird. Dazu muss man nur das Herz im Inventar haben. Dadurch können alle ein Herz bekommen, die am Kampf teilnehmen.

**Comment by Grambosch** [comment]
Aber bitte nicht täglich eher 5-7 Tage

**Comment by DerOliDE** [comment]
Genehmigt. ^^

**Comment by krakel** [comment]
Umgebaut. https://github.com/combak/ShatteredWorld/commit/f93074ae7c54d43181e26e1d2d1bf3b0014c195e
