### ISSUE TITLE
agri craft ernten

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#268]
Ich denke es wäre gut einen mod hinzuzufügen der es ergmöglicht agri craft crops automatisch erntet ohne die item dabei droppen wie es bei botania zum beispiel der Fall ist. Es gibt zwar robots aber die buggen öfter mal weg. Ein Mod wie progressiv automation würde das denke ich ganz gut lösen.

**Comment by krakel** [comment]
EnderIO die Farming Station macht das doch.

**Comment by Grambosch** [comment]
Vacuum Hopper oder so dann liegts nicht lange rum , EnderIO Station muss ich passen. Aber auch da gibts keine Probleme mit dem Stacklimit bei normalen Farmgrößen

**Comment by Mateholiker** [comment]
Die Ender IO farm baut die Pflanzen mit den cropsticks ab und es gibt keine Möglichkeit diese wieder automatisch anzubauen. Und das problem mit den farmen ist das wenn ich eine 9x9 Farm habe (von der ich noch nicht sagen würde das sie zu groß) und ich sie mit dem Drum of the Wild von Botania ernten lasse dann habe ich, da jede pflanze 4 items dropt, 9x9x4 =324 Items. egal wie schnell ich die aufsammle liegen sie mindestens 1 tick herum. Und in diesem Tick werden dann zum beispiel maschienen die ich abbaue einfach zerstört.

**Comment by krakel** [comment]
Es stimmt, die EnderIO Farming Station erntet alles ab und pflanzt dann die Seed auf leerem Boden an AgriCraft vorbei. Das auch noch unabhängig vom Boden. Natürlich wächst dann nicht. Muß feststellen das dieses Verhalten nur mit dem Mod EnderIOAddons https://minecraft.curseforge.com/projects/ender-io-addons abgestellt werden kann. :(

**Comment by Mateholiker** [comment]
also wie gesagt ich wäre für progressiv automation als lösung man kann die rezepte ja noch etwas schiriger machen als sie es normal sind und bis auf den harvester alles deaktivieren. Nebenbei gibt es für die spieler einen weg herrauszufinden wie viele stacks in ihrer dim grade liegen den ich habe bei mir große probleme mit dem item stacks und weiß einfach nicht wo so viele items liegen sollen.

**Comment by hellamie** [comment]
Golems ernten und Hopper aus diversen mods sammel ein.

Bei uns voll automatisch und ohne Probleme.

**Comment by Mateholiker** [comment]
also ich habe drum of the wild zum ernten und hopperhack zum einsammeln aber gestern hatte ich das Problem das gar keine items mehr gedroppt sind obwohl ich alle farmen deaktiviert hatte... der Neustart hat das Problem dann gelöst und ich werde das mal beobachten und gegebenenfalls ein issue aufmachen. Aber denoch fände ich es gut wenn es eine Möglichkeit gäbe zu ernten ohne das items droppen. Den selbst wenn es nur 300 stacks pro spieler sind so würde man dann doch server leistung einsparen.
