### ISSUE TITLE
Auluminium automatisch Verarbeiten

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#269]
Aluminium gravel, sand und dust von ex nihilo lässt sich nicht mit dem pulveriser weiterverarbeiten weil es in TE kein Aluminium gibt. Es wäre schön wenn man trozdem ein rezept hierfür hinzufügen könnte

**Comment by Grambosch** [comment]
Gravel und Sand hinzufügen vergessen
