### ISSUE TITLE
Itemduct lassen Items fallen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#27]
Seit wann lassen Itemducts Item fallen wie in in den guten alten Zeiten von Buildcraft?

**Comment by krakel** [comment]
Zuücklaufende Items werden nur gehalten, wenn ein Servo im System ist. Ein simples Duct hat wohl keinen Rücklaufspeicher.

**Comment by DerOliDE** [comment]
Ich denke das kann man mal als "Feature" schließen.
