### ISSUE TITLE
Crafting rezept für Fluix crystales

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#270]
Fluix Crystales werde immer noch gecraftet in dem man items auf den Boden wirft das ist aber insbesondere mit dem Stack limit nicht grade optimal und in großen mengen auch nicht server schonened. Daher schlage ich ein crafting rezept für Fluix vor bei dem ein Netherquarz, ein Redstone, ein Charged Certus quartz und ein Eimer Wasser zu zwei Fluix crystales wird. Der Eimer wird natürlich nicht verbraucht.

**Comment by Nedelosk** [comment]
Um Fluix crysteles in großen Mengen herzustellen  kann man die Crystal Growth Chamber nutzen.

**Comment by Grambosch** [comment]
300 Item Stacks sollte hierfür gerade reichen. Tritt der Fall dennoch auf gucken wir nochmal aber wird alles sauber aufgeräumt passiert das nicht

**Comment by Mateholiker** [comment]
sorry das wusste ich nicht danke für den tipp :)
