### ISSUE TITLE
Personal Chunk Loader

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#271]
Es wäre gut wenn es einen Personal Chunkloader gäbe der nur dann die Chunkes läd wenn der Spieler dem er gehört online ist. Den ansonsten bringen dinge wie der tesseract nichts da sobald ich im Nether zum beispiel Strom benötige meine Welt nicht mehr geladen ist.

**Comment by krakel** [comment]
Soweit ich weiß ist das so beabsichtigt! Wenn du im Nether Energie brauchst, mußt du sie dort erzeugen.

**Comment by Grambosch** [comment]
Chunk Loader wirds nicht geben

**Comment by Mateholiker** [comment]
Wenn ich im Nether ein paar Maschienen aufstelle um dort Energie zu erzeugen und sie dann jemand anderes mit nimmt gilt das den als klauen oder ist das ok weil es ist ja nicht meine Basis sondern der Nether?
Desweiteren wofür soll man dann den  transdimensional transiver von Ender IO craften soll? Den um Energie zuwischen dimensionen zu transportieren lässt er sich dann ja nicht nutzen da ich immer nur eine seite gleichzeitig geladen halten kann.

**Comment by hellamie** [comment]
In den Regel steht diesbezüglich etwas.

**Comment by Grambosch** [comment]
Alles außerhalb deiner Dimension werde ich persönlich weder ahnden noch verfolgen , und in deiner Dimension hast du hoffentlich nur vertrauenswürdige Leute erlaubt. Das mit den eigenen Dimensionen ist tatsächlich zum Teil genau diesem Aspekt geschuldet. In einem vergangenen Projekt hat das so viel Zeit in Anspruch genommen das man zu gar nix mehr kam.
