### ISSUE TITLE
doppeltes rezept

### ISSUE THREAD

**Issue by Mateholiker** [combak/ShatteredWorld#272]
Zwei Smokey quarz slabs werden zu einem Quarz Block und zu einem Chiseled Quarz Block laut NEI. Das erste Rezept überlagert dabei das zweite. Daher ist es unmöglich einen Chiseled Quarz Block zu craften.

**Comment by Grambosch** [comment]
Also für denjenigen der das Rezept unbedingt braucht (sowie jedes andere Rezept mit Doppelbelegung) nehmt den Forestrytisch (Worktable). Ansonsten ist das wohl ein Problem im Mod ansich und keins von unserer Seite

**Comment by DerOliDE** [comment]
Rezepte deaktiviert, die Auswahl via Chisel (Chisel2) bleibt.
