### ISSUE TITLE
AE2

### ISSUE THREAD

**Issue by m00nLP** [combak/ShatteredWorld#274]
Besteht die möglich das ihr im Source Code von AE2 Stuff bzw eine config erstellt für den Wireless Connector wegen dem Strom verbrauch?

Hier ein Post dazu
https://github.com/bdew/ae2stuff/issues/107

**Comment by Grambosch** [comment]
Warum?

**Comment by DerOliDE** [comment]
So um mal ein paar Fakten dazu zu nennen, ich habe mir das mal angeschaut und mir zwei mal Energy Cell, Energy Acceptor und Wireless Connector aufgebaut und verbunden. 

Von einem Insel Ende zum anderen gemessen 215 Blöcke hat das Ganze einen verbrauch von rund 95kRF/t pro Connector. Da der Basisverbrauch sehr gering ist, lässt sie die Formel auf Distanz^2 = verbrauch AE/t ( 1AE = 2RF) herunterbrechen.

Der Verbrauch ist für das was wir an Energieerzeugung im Modpack haben zu hoch und in Anbetracht das der Wireless Connector ähnlich wie der Tesseract Kabel einsparen kann, bin ich durchaus der Meinung, dass die Verwendung forciert werden sollte.

215 Blöcke ist das extrem Beispiel bei 100 Blöcken haben wir noch immer 20kRF/t pro Connector das würde ich gern auf 5-10% reduzieren, da sind wir bei 1k-2k RF/t pro Connector, was noch immer ein ordentlicher verbrauch ist, um vom Zentrum der Insel zu den äußeren Rändern eine Verbindung aufzubauen.

**Comment by Grambosch** [comment]
Na das ist ne Begründung . Gut Aber mit dem ersten Post konnt ich so nix anfangen

**Comment by DerOliDE** [comment]
Ja wurde im Discord angesprochen, die Begründung hier ist in der Tat zu spärlich damit jemand der nicht bei der Diskussion dabei war etwas damit anfangen könnte.

Also an alle schreibt ausführliche Issues sonst werden sie aufgrund von Missverständnissen geschlossen. :P
