### ISSUE TITLE
Mod Vorschlag Tinkers IO

### ISSUE THREAD

**Issue by m00nLP** [combak/ShatteredWorld#275]
Tinker i/o

Ist ein Mod womit man die Smeltery was beschleunigen könnte.
Da ja hier sehr viel mit der Smeltery gearbeitet werden muss

https://minecraft.curseforge.com/projects/tinker-i-o

**Comment by DerOliDE** [comment]
Die Beschleunigung finde ich zu extrem aber der Smart Output ist durchaus interessant.

**Comment by m00nLP** [comment]
Den inbound könnte man ja deaktevieren

**Comment by DerOliDE** [comment]
Ich muss mir das erstmal live anschauen, habe bis jetzt nur die Beschreibung + Video auf Curse zu 1.7.10 begutachtet.

**Comment by Lutze53** [comment]
Hab noch ein Modvorschlag fürs Kochen, da es ja doch viele Rezepte gibt :)
Cooking for Blockheads - https://minecraft.curseforge.com/projects/cooking-for-blockheads

**Comment by Grambosch** [comment]
Eins nach dem anderen außerdem ist das alles auch über Worktables und später AE lösbar

**Comment by DerOliDE** [comment]
Bitte nicht zwei unterschiedliche Dinge in einem Issue diskutieren

**Comment by Lutze53** [comment]
Sry war nur weil der Titel Allgemein klang ( jetzt ja nicht mehr ;) )

**Comment by DerOliDE** [comment]
Hab es gesplittet.  https://github.com/combak/ShatteredWorld/issues/280
