### ISSUE TITLE
Kinetic Energy Buffer Rezept funktioniert nicht

### ISSUE THREAD

**Issue by arlos200** [combak/ShatteredWorld#276]
Hallo, 
ich hab festgestellt beim herstellen eines Lasers von BC Silicon, dass das Rezept vom Kinetic Energy Buffer (4 Iron, 3 Kinetic Capsule Tier 1 und 2 Flux Disperser) nicht funktioniert.

**Comment by Grambosch** [comment]
Da auf dem Server ne Menge Laser rumschwirren bezweifle ich diese Aussage so erst mal . Schau bitte mal genau nach woran das liegt und ob du auch in Eureka die passenden Inventions hast

**Comment by DerOliDE** [comment]
Eureka greift erst bei der Verwendung/Platzierung, das Rezept funktioniert, der Fehler liegt daran, dass es nicht 2 Flux Disperser sind sondern **1 Flux Disperser und 1 Flux Conductor.**
