### ISSUE TITLE
Forestrymaschinen nerviger Fehler

### ISSUE THREAD

**Issue by GrayPanther** [combak/ShatteredWorld#279]
Jetzt schon zum 3. mal ist meine Energie zusammengebrochen, weil die Forestrymaschinen sich von den Itemleitungen gelöst haben! Egal welche Itemleitung ich probiere, es ist immer das selbe! Ich muss die Maschinen komplett abbauen und neu setzen, da sie selbst mit einem Hopper nicht mehr befüllt werden können!

**Comment by DerOliDE** [comment]
Forestry bekommt ein Update, wenn der Fehler danach weiterhin auftritt diesen Issue bitte wieder öffnen.
