### ISSUE TITLE
Servo wird zerstört, wenn mit Cresent Hammer entferrnt

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#28]
Man kann einen Servo entfernen ohne das Duct abzubauen. Leider wird in der aktuellen Version dann auch das Servo zerstört.

**Comment by DerOliDE** [comment]
In 0.5.3 mit allen Servo Typen mit Hardened Fluidcut und Itemduct getestet, dieser Fehler wurde wohl im aktuellen Thermal Dynamics behoben.
