### ISSUE TITLE
Mod Vorschlag - Cooking for Blockheads 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#280]
Von Lutze53 gesplittet aus https://github.com/combak/ShatteredWorld/issues/275

Hab noch ein Modvorschlag fürs Kochen, da es ja doch viele Rezepte gibt :)
Cooking for Blockheads - https://minecraft.curseforge.com/projects/cooking-for-blockheads

**Comment by DerOliDE** [comment]
Ich sehe keine Notwendigkeit für diese Mod, wie Grambosch schon sagte, prinzipiell via Workbench/-table und AE realisierbar, der einzige unterschied ist, dass man halt selbst wissen muss, was man aus den Zutaten machen kann.

**Comment by hellamie** [comment]
überflüssig..das hatte ich schon...man kann keine kiste oder so an das "Crafting feld " anschließen. Ich mag es nicht. Und deko haben wir schon mit Dekocraft

**Comment by Grambosch** [comment]
Da schließe ich mich an
