### ISSUE TITLE
Unsichtbare Mobs in Lycanites

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#281]
Bin heute hierrüber gestolpert, Zitat:
_"Encountered in FTB Monster Version 1.1.1: After several days of playing on a localhost server it was noticed that the hostile mobs were few and far between, and eventually stopped spawning altogether. The issue was that this mod was creating invisible, undetectable entities in each chunk and slowly overloading the creature cap and even /cofh killall would not clear them. These mobs can be removed using /xu_killliving, this will, however, remove all living entities, including tamed ones."_
Quelle: https://ftbwiki.org/Lycanites_Mobs#Known_Bug

**Comment by krakel** [comment]
Wenn man wüßte, wo das im Source Code steht, könnten wir dieses Verhalten sogar abschalten.

**Comment by DerOliDE** [comment]
Ich glaube wenn die Entwickler das wüssten hätten sie es schon abgeschaltet. :D

**Comment by krakel** [comment]
So wie ich das aktuell verstehe, lassen die normale Vanilla Mobs spawnen und ändern die dann zu Lycanite Varianten. Hier ein Post aus deren Issues.

> Lycanites Mobs does adjust where some vanilla mobs spawn, for example Skeletons don't spawn in Deserts as Clinks are kind of their replacement. However you can turn this off in each of the general configs such as desertmobs-general.cfg, in there is a setting called something like Control Vanilla Spawns, search for something like that and set it to false. Let me know if you're still having problems

**Comment by DerOliDE** [comment]
das klingt schon irgendwie "eklig", ich vermute mal es handelt sich um diese Config:
https://github.com/combak/ShatteredWorld/blob/master/config/lycanitesmobs/arcticmobs-general.cfg#L143-L146

Da steht allerdings nur "vanilla spawn will be removed".

**Comment by Grambosch** [comment]
Da wäre mir nix mehr zugetragen worden. Close ende nächster Woche wenn niemand hier schreit

**Comment by Grambosch** [comment]
So close
