### ISSUE TITLE
Problem mit ae2

### ISSUE THREAD

**Issue by m00nLP** [combak/ShatteredWorld#283]
Und zwar da es ja keinen Chunkloader gibt setzt sich da AE ja bei jedem neuen einloggen (wenn die Insel offline war) zurück.

Das Problem an der Sache ist jetzt nur das sich auch der Security Table auch zurücksetzt sprich keiner kann mehr aufs AE zugreifen.

Ich mein aber das dieses Problem in der Aktuellen Version von AE behoben wurde.

**Comment by Mateholiker** [comment]
Bei mir tritt das problem auch auf ein abbauen und neu setzen des Security Tables behebt das problem bis die insel entladen wird.

**Comment by DerOliDE** [comment]
Sollte mit dem nächsten update gefixt sein, falls nicht Issue wieder aufmachen.
