### ISSUE TITLE
Mod Vorschlag Progressive Automation (Farm only)

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#284]
Hatte es ja kurz im Discord angeschnitten, wir haben keine Farm die mit den Agricraft Crops umgehen kann. Progressive Automation könnte es und wäre damit eine Alternative zu den Entity-lastigen Golems/Robots.

Problem wäre die Rezepte auf eine vernünftige Schwierigkeit anzuheben.

**Comment by DerOliDE** [comment]
Passend zum Thema
https://www.reddit.com/r/feedthebeast/comments/3wi9rc/agricraft_and_forestry_multifarm/
https://github.com/InfinityRaider/AgriCraft/issues/92

**Comment by Grambosch** [comment]
ingame getestet. Forestry kann das

**Comment by DerOliDE** [comment]
Damit ist die Thematik schon wieder für mich beendet. ^^

**Comment by krakel** [comment]
Was noch beachtet werden sollte, das mit Forestry nur Seeds gehen, die keine Block unter dem Soil brauchen. Forstry lässt das nicht zu! An dieser Stelle ist immer die Grundfläche der Fram.

**Comment by hellamie** [comment]
Wohle...habe statt der Bricks den Block und oben drauf ein Eisen nuggets werden geerntet..wenn du es nicht glaubst ge schauen

**Comment by krakel** [comment]
Habe es kontrolliert und mit eigenen Augen gesehen. Es lebt, ähh, funktioniert. Forestry wird ja wieder interessant. :)
