### ISSUE TITLE
Forestry kein Hellish in Aleary im Nether moglich mit aktueller Version

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#286]
bin dei diesem Problem angekommen:
https://github.com/ForestryMC/ForestryMC/issues/1366
wir haben forestry-1.7.10-4.2.5.53.jar, letzte ist forestry_1.7.10-4.2.16.64.jar

**Comment by DerOliDE** [comment]
Laut Larson in 63er Build gefixt, die aktuellere Version wird beim nächsten update übernommen.

**Comment by DerOliDE** [comment]
Falls Fehler trotz Forestry update weiterhin auftritt, diesen Issue bitte wieder aufmachen.
