### ISSUE TITLE
Forestry Sapling und Leaves lassen sich nicht kompostieren

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#289]
Forestry Sapling und Leaves werden im Wooden Barrel nicht akzeptiert. Eventuell müsste folgendes in den Scripts funktionieren:

```
#Ex Nilho Composting Additions
mods.exnihilo.Composting.addRecipe(<Forestry:sapling>, 0.125);
mods.exnihilo.Composting.addRecipe(<Forestry:leaves>, 0.125);
```

Hatte aber leider keine Zeit zum testen.

**Comment by DerOliDE** [comment]
Funktionieren dafür aber im Composter, der bei Anpassung des Barrel obsolet werden würde, weil das Dirt Rezept dort schwieriger ist.

**Comment by DerOliDE** [comment]
Im Discord besprochen, wir wollen es nicht ändern bzw. den Composter als erste Wahl lassen.
