### ISSUE TITLE
Questbook AM2 Boss

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#294]
Aus dem Forum von Thor:
haben den lightning guardian jetzt 3 mal getöten und bekommen aber ihm im questbuch leider nicht anerkannt

mfg Thor

http://www.bakermanlp.de/viewtopic.php?f=3&t=253

**Comment by krakel** [comment]
mist, falscher Boss
https://github.com/combak/ShatteredWorld/commit/4bba5facca5f656de505581845ad7e6c7e107450
