### ISSUE TITLE
Gedankengang zu Minechem

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#30]
Diskussion aus Docs:
Wenn wir die Mod reinnehmen sollten und prinzepiell finde ich sie gut, sollten wir alle Materialen die zu Ernergieerzeugung dienen rausnehmen, damit es kein Konflikt zwischen benötigter Energie zum erzeugen des Materials und der Energiemenge die das Material beim verbrennen erzeugt gibt. Dann muss man auch den Energiebedarf der Minechem Maschinen nicht ins exorbitante treiben. Die Rezepte für die Maschinen würde ich trotzdem erschweren damit es ins Late Game kommt.

**Comment by DerOliDE** [comment]
Diskussion aus Docs - Grambosch dazu: Guter Gedankengang. Da müssen wir aber höllisch auf die Extrautils generatoren achten.Erschweren war sowieso der Gedanke. Sprich um ein komplettes Re-Balancing kommen wir nicht rum.

**Comment by krakel** [comment]
Ich bin komplett gegegn Minechem. Die aktuelle Zusammenstellung ist schon schon harmonisch genug.

**Comment by DerOliDE** [comment]
Ist das Thema Minechem noch aktuell? Wenn ich mir die Möglichkeiten anschaue die wir z.Z. zur Resourcegewinnung haben ( Ex Nihilo, Resource Crops und Bienen ) ist das imho ausreichend.

**Comment by DerOliDE** [comment]
Da sich hierum keiner mehr bemüht hat denke ich mal das Thema ist abgeschlossen.
