### ISSUE TITLE
Client Crash Report Thaumcraft GUI

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#300]
https://gist.github.com/DerOli82/8116ad0d6153b8b5d42907b39a05fe5b

**Comment by Grambosch** [comment]
Renderfehler seh ich öfter von diversen Mods.

**Comment by m00nLP** [comment]
Der fehler wurde von Optifine ausgelöst
Optifine und Resorcen Packs arbeiten nicht oft zusammen
