### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bastian1991** [combak/ShatteredWorld#302]
http://paste.ee/p/IvIQz

**Comment by DerOliDE** [comment]
Werde ExtraCells mal auf die aktuellste Version updaten, eventuell ein Problem das durch den wechsel von AE2 rv2 auf rv3 auftritt.

**Comment by DerOliDE** [comment]
Sollte der Fehler nach dem nächsten Update weiterhin auftreten, diesen Issue bitte wieder aufmachen.
