### ISSUE TITLE
Ars Magica 2 

### ISSUE THREAD

**Issue by gaxthor** [combak/ShatteredWorld#303]
gibt ein problem mit dem fire guardian das wir ihn nicht beschören können 

im singleplayer getestet geht ohne probleme nur auf em server will er nicht

Mfg Thor

**Comment by DerOliDE** [comment]
Vermutlich checkt die Mod auch auf dimId == -1

**Comment by Grambosch** [comment]
Kannst du da bitte mal schauen Grayal?

**Comment by krakel** [comment]
Soll ein Problem mit Thermos sein. Bestimmte Bosse müssen da frei geschalten werden.

**Comment by Grambosch** [comment]
Passiert hier noch was ? ISt das evtl wieder so ein Providergeraffel?

**Comment by DerOliDE** [comment]
Hatten den Source Code mal überflogen aber nix Richtung dimId == -1 gefunden. Wäre fast dafür den Nether wieder auf die -1 zu legen für einen Worldborder und der gleichen brauchen wir ja nicht mehr zwingend eine YADM Dimension.

**Comment by DerOliDE** [comment]
Nether befindet sich wieder in Dim -1 damit sollte sich das erledigt haben.
