### ISSUE TITLE
SAG Mil macht aus Sand Wood Pulp

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#304]
Sollte eigentlich Silicon bei raus kommen.

**Comment by DerOliDE** [comment]
Passiert nur aufm Server

**Comment by Lutze53** [comment]
ja kann ich bestätigen :(
hab noch roten Sand getestet, da geht es
![2017-02-09_19 40 04](https://cloud.githubusercontent.com/assets/25138667/22797741/bf55dffc-eeff-11e6-95af-ffa25a890a99.png)

**Comment by DerOliDE** [comment]
Updaten von EnderIO auf die letzte 1.7.10er beta Version hat leider nichts gebracht, auch scheint er jegliche Änderungen in der SAGMil user.xml zu ignorieren, das Problem ( https://github.com/combak/ShatteredWorld/issues/105 ) hatten wir werden der dev Phase auch aber da konnten wir es vernachlässigen.

**Comment by DerOliDE** [comment]
https://github.com/CyberdyneCC/Thermos/issues/512

**Comment by BakermanLP** [comment]
Die Änderung in config/enderio/OreDictionaryPreferences_User.xml brachte keinen Erfolg.
Einen Schritt zurück zu https://github.com/CyberdyneCC/Thermos/releases/tag/57 brachte den gewünschten Erfolg. SagMill produzierte wieder Silicon aus Sand.

**Comment by DerOliDE** [comment]
Nach Thermos downgrade gelöst.
