### ISSUE TITLE
Verwenden des Sleeping Bag fürrt zu Absturtz ins Void

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#306]
Beim Schlafsack bitte mal verifizieren ob das nur bei einer Höhe über 100 passiert, der Fehler kommt mir irgendwie bekannt vor.

**Comment by Lutze53** [comment]
schlafe immer über Höhe 100 und hatte bis jetzt noch nicht das Problem

**Comment by hellamie** [comment]
gestern mal mit Absicht auf Höhe 90 gepennt..nichts passiert..

sonst schlafe ich immer oben irgendwo..zumindest auf meiner Insel..werde das Nahcher mal in den Inneren Ländern testen.

**Comment by DerOliDE** [comment]
Hatte am Do. auch verschiedene Höhen ausprobiert und den Fehler nicht mehr reproduziert bekommen.

**Comment by DerOliDE** [comment]
Mit dem Schlafsack aus der Welt fallen konnte ich jetzt mehrmals ab einer Höhe von 130+ reproduzieren. Kann das mal irgendwer verifizieren?

**Comment by hellamie** [comment]
bestätigt

**Comment by Lutze53** [comment]
Mir selber auch passiert. :(

**Comment by DerOliDE** [comment]
Sehe keine Möglichkeit das Problem in den Griff zu bekommen, da es keine Extra Utilities Updates mehr gibt und das Problem wahrscheinlich eh im Zusammenhang mit Thermos steht, bei dem wir auch mit einer bestimmten Version feststecken.
