### ISSUE TITLE
Hinlegen ins Bett fügt Schaden zu und unterbricht den Schlaf 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#307]
Ist mir gestern auch passiert nach ein paar mal hartnäckig hinlegen ging es aber normal ist es nicht.

**Comment by DerOli82** [comment]
Mit dem Schlafsack aus der Welt fallen konnte ich jetzt mehrmals ab einer Höhe von 130 reproduzieren. Kann das mal irgendwer verifizieren?

**Comment by DerOliDE** [comment]
Siehe https://github.com/combak/ShatteredWorld/issues/306
