### ISSUE TITLE
Tinker Schwert und XP-Boostverzauberung

### ISSUE THREAD

**Issue by GrayPanther** [combak/ShatteredWorld#309]
Ich wollte mein Langschwert mit XP-Boost III ausstatten und wenn ich sie Sachen im Anvil reinlege, bekommt das Schwert auch die Verzauberung drauf! Doch beim schließen der GUI ploppen Buch und Schwert(unverzaubert) auf den Boden! Aus anderen Packs weiß ich, das diese Verzauberung mgl. ist!

**Comment by hellamie** [comment]
nimm botania und versuch es mal damit

**Comment by GrayPanther** [comment]
Botania ist nicht mein Mod! Benötigt Platz den ich nicht hab und ein Haufen Mana, den ich nicht generieren kann/will! Botania hatt außer den Magnetring nix von Interesse und wegen einer Verzauberung bau ich nicht meine komplette Insel um! Aber danke für den Vorschlag!

**Comment by hellamie** [comment]
auf meiner steht alles :) komm rüber

**Comment by Grambosch** [comment]
Welches Langschwert?

**Comment by GrayPanther** [comment]
Das von Tinker! Zusammensetzung: Schleimgriff, Obsidianhandschützer und Netroniumklinge! Wenn es weiterhilft!

**Comment by GrayPanther** [comment]
Ok! Umbenennen des Schwertes behebt scheinbar das Problem! Somit schließe ich das hier mal!
