### ISSUE TITLE
Mod: Nether Ores

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#31]
Hatten wir im TS schon einmal angesprochen, da der Nether Bock schwer ist ggf. eine reduzierte Nether Ore Gen zulassen.

**Comment by Grambosch** [comment]
Dafür. Zumindest in ner Testphase damit Picken wieder was sinnvoller werden

**Comment by DerOliDE** [comment]
Wird in 0.5.3 testweise mit reduzierten Spawn rein genommen.

**Comment by Grambosch** [comment]
Wir müssen dringend an die Mobconfig für den Nether ran... Ich stand da mit ner vollen Endgamethaumcraftrüstung und gecheateten 10er Resis für alles nicht wirklich lange. Da sollte evtl was runtergeschraubt werden

**Comment by DerOliDE** [comment]
Wäre es schlimm wenn die Mobs so hart wären, das man in den Nether nicht allein rein sollte? ^^

**Comment by Grambosch** [comment]
Naja ob ich nu allein sterbe oder zu 3t macht keinen Unterschied Das Problem ist die Masse mit der härte. Zumindest die Nethersouls da müssen wir ran

**Comment by DerOliDE** [comment]
Also die Verteilung der Erze im Nether mit Nether Ores gefällt mir, wenn es keine einwende gibt würde ich das so lassen.

**Comment by DerOliDE** [comment]
Da derzeit wohl keine Einwende -> closed. ^^
