### ISSUE TITLE
Waila Plugins updaten.

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#314]
Zeigt irgendwas in Bloodmagic nicht an Zitat aus dem Discord von TheSnowyChickens: 
"Das is jez ne blöde Frage , aber darf ich verstehen ,warum so ne alte Version von Waila plugins standartmäßig installiert ist? Ich wollt nämlich nachschauen ,warum Bloodmagic nix in Waila anzeigt und dann sah ich das."

**Comment by Grambosch** [comment]
Das ist äußerst ungenau dargestellt...

**Comment by DerOliDE** [comment]
In der Tat aber die Mod lässt sich problemlos updaten, da wird kein sonstiger Kram hinzugefügt auf den man ein Auge werfen müsste, also update ich das einfach mal.

**Comment by DerOliDE** [comment]
Lässt sich nur updaten wenn ich auch EnderIO update, daher erst einmal gestrichten.
