### ISSUE TITLE
Könnte die Eldritch Dim resetet werden bitte

### ISSUE THREAD

**Issue by Deathskylp** [combak/ShatteredWorld#317]
Ich und mein Kumpel Puma waren im Eldritch und haben bemerkt das die Dimension aus geleert wurde
deswegen wollte ich  um einen Reset der Dimension fragen wenn es geht .

**Comment by Grambosch** [comment]
http://www.brierieserver.co.uk/mobile/forum/viewthread/m/8987880/id/26070136-eldritch-dimension-did-generate/viewthread/5345922-banned-charizardmaster ,letzter Eintrag . 1 x googlen zur Not falls noch ne Distanzkomponente drin ist geht in die Farmwelt und geht 3000 Blocks

**Comment by DerOliDE** [comment]
Wurde einmal resetet anderenfalls siehe Gramboschs Link.
