### ISSUE TITLE
[Request] Thaumcraft Gold Coins

### ISSUE THREAD

**Issue by TheSnowyChickens** [combak/ShatteredWorld#320]
Hallo
In vielen anderen Modpacks zählen die Thaumcraft Gold Coins als normale Nuggets , somit gehen die dann auch fürs Crafting. Es wäre schön ,wenn ihr das eventuell noch ändern könntet , wenns ok ist , denn es ist umständlich und Zeit raubend die extra noch in die schmelze zulegen und dann in Nuggets zuformen. :)

Thx

**Comment by hellamie** [comment]
Ich glaube kaum das wir das jetzt noch ändern. Außerdem ist das mit einer Autoschmelze schnell erledigt
 :)

**Comment by DerOliDE** [comment]
Die Coins stehen im OreDict als nuggetGold, also sofern die Rezepte das OreDict verwenden, kann man die Coins als Gold Nugget verwenden. Bei nur grob 20 Rezepte von 120 wird kein OreDict verwendet.
