### ISSUE TITLE
Quest: "Larger Liste von Grasem"

### ISSUE THREAD

**Issue by SlashZooka** [combak/ShatteredWorld#321]
Mal abgesehen von den etlichen Schreibfehlern in der Quest :P, funktioniert diese nicht :c habe die Quest wie verlangt abgegeben und auch das Questitem (die Schriftrolle bzw. Lagerliste) erhalten, doch im Questlog steht, dass ich sie noch nicht besitze und beim abzugebendem NPC findet auch keine Reaktion bezüglich der Beendigung der Quest statt. 

Ich hatte das Item auch mal auf den Boden gedroppt und wieder aufgehoben, in den inneren Ländern sowie in meiner eigenen Welt, relog etc. hat ebenfalls nicht geholfen :/

**Comment by Nedelosk** [comment]
fixed
