### ISSUE TITLE
"Die Malstifte" Blood Magic Quest

### ISSUE THREAD

**Issue by TheSnowyChickens** [combak/ShatteredWorld#322]
![request](https://user-images.githubusercontent.com/29357962/28756582-8c3ba130-7571-11e7-946a-3a16728b30f7.png)
Hallo
Bei der ,wie im Title, stehenden Quest braucht man ja die Stifte von Blood Magic und in der Quest ist das ja ein "Detection Task" , jedoch werden schon benutzte Stifte nicht erkannt . Es kann natürlich sein , das es gewollt ist von euch , das man neue braucht ,aber es wäre besser , wenn auch Benutzte gehen würden , denn wenn man unbeabsichtigs die schonmal nutzte , befor man die Quest erledigt hat , ist das extrem blöd. :/

Also wenns nicht gewollt ist , könntet ihr das dann bitte ändern wenns geht ? :)#
Thx

**Comment by TheSnowyChickens** [comment]
![nun voll](https://user-images.githubusercontent.com/29357962/29297923-98fdc912-8164-11e7-9a1f-7eab3406bae0.png)

Nun , jez wirds noch seltsammer. Die dinger hab ich jez gefüllt und den Detect button tot geklickt jedoch passiert da immer noch nix. Nur so als zweiten Hinweiss bzw. Beweissmittel :)

**Comment by krakel** [comment]
Hier muß wohl nur das precision Flag auf FUZZY gesetzt werden.

**Comment by DerOliDE** [comment]
Korrektur kommt ins nächste update.

**Comment by TheSnowyChickens** [comment]
Sehr gut , danke dir. :)

**Comment by krakel** [comment]
Da ich das nicht getestet habe, kann es auch sein das die Bedingung noch etwas schwammiger sein muß. Es gibt da noch NBT_FUZZY. Wenn ihr das vor dem Update noch testen könntet, kann ich das noch weiter entschärfen.

**Comment by DerOliDE** [comment]
Funktioniert, habe ich bereits gestern getestet. :)
