### ISSUE TITLE
[Suggestion] Magnum Torch

### ISSUE THREAD

**Issue by TheSnowyChickens** [combak/ShatteredWorld#324]
Hallo
Wir kennen ja alle das Ozelot überschuss problem und da frage ich mich , ob ihr in die Magnum Torch die Ozelots eintragen könntet (wenns überhaupt geht) ,damit die ,die die nicht mehr haben wollen einfach eine Torch platzieren können , sowas die nemmer spawnen.
Ka. ob das geht ,aber wenn ja wäre das extrem praktisch.

Schönen Tag noch^^

**Comment by DerOliDE** [comment]
Dafür gibt es keine Konfiguration und eine Mod mit der das möglich wäre (Torch Master) gibt es erst ab 1.10.2, die könnte sogar mit den Lycanites umgehen.

**Comment by TheSnowyChickens** [comment]
Hmmm schade ;/
