### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#33]
Da wir ja Cross Mod Rezepte verwenden, sollten wir uns mal Gedanken über einen Workflow machen, nicht das es zu Deadlocks kommt.

**Comment by DerOliDE** [comment]
Einige Maschinen Rezepte würde ich gern mit BC Chips bestücken

**Comment by Grambosch** [comment]
Low Tech BC CHips High Tech Draconic Ev. Cores. Und vor allem billigsachen raus wie ein Redstonedust für die Stromaufnahme etc da haben wir ja Coils etc für

**Comment by Grambosch** [comment]
zZ handhabe ich es so das ich trenne zwischen Magie und Technikmods und ein paar sind irgendwo dazwischen  aus den beiden Gruppen würfle ich dann Rezepte zusammen und mach mir nen Kopf drum was man ohne Probleme bauen kann  (Also min 1 generator baubar ohne Teile die ne Maschine mit Strom bauen zB).

**Comment by DerOliDE** [comment]
Gehört mit hierzu https://github.com/combak/ShatteredWorld/issues/63

Zwecks Übersicht closed
