### ISSUE TITLE
Ex-Nihilo Lava zulassen und alle Lava Energie Produktion abschalten

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#34]
Wir diskutieren gerade die Idee, Lava duch Ex-Nihilo wieder zu zulassen und dafür in allen Generatoren das Lava zur Energiegewinnung heraus zu nehmen.

**Comment by DerOliDE** [comment]
Ich habe noch immer den Gedanken im Kopf eine Mod notfalls selbst zu schreiben die das platzieren bestimmter Blöcke auf ein Limit pro Spieler zu begrenzen, dann könnte man pro Spieler ein Crucible zulassen.

**Comment by krakel** [comment]
Ja aber wenn du die Energiegewinnung über Lava deaktivierst, ist das Produzieren von Lava sinnlos.

**Comment by DerOliDE** [comment]
Dann ist Lava allgemein recht sinnlos und man müsste konsequenterweise auch Botania Mana via Lava beschneiden und alles andere was von Lava "profitiert".

**Comment by DerOliDE** [comment]
Für die 0.5.3 habe ich mal den Ex Nihilo Crucible aktiviert und Lava als Heat Source deaktiviert. Mit Torch dauert es dann ~ 8 Min pro Lava Bucket, was man ggf auch noch anpassen könnte.

**Comment by Grambosch** [comment]
Netherrackfeuer ist ein *3 Multiplikator

**Comment by Grambosch** [comment]
Lava ist halt nur ein Problem solange man sich im Nether nicht halbwegs sicher vorwärts bewegen kann.
Und dann ist da natürlich auch noch der Magmatic Crucible von TE. Der kostet zwar einiges an Strom aber das kriegt man über verbesserte Magmatic Dynamos wieder kompensiert. Lava soll ja nicht als Energieträger raus aber andere sollten evtl attraktiver werden.

**Comment by DerOliDE** [comment]
So der Ex Nihilo Crucible wird in 0.5.8 erst einmal auf 2 pro Spieler limitiert, was im Endeffekt heißt alle ca 8 Min 2 Buckets Lava.

See Limited Resources: https://github.com/combak/ShatteredWorld/commit/ca61864abec38ecd5cf6dc30eac482f7ac3bd658

**Comment by DerOliDE** [comment]
Mache ich erst einmal dicht, da die Anzahl an Crucibiles jetzt limitiert sind.
