### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#35]
Ich hab in der Bearbeitung bei Buildcraft erst Mod dann Material/Name dann Form(Ingot, Block etc)
für die Values gewählt. Das ist schön einfach für mich. 
Nu zu den Fragen:
Erst alles entfernen und dann nach der letzten Entfernung alles wieder hinzufügen ?
Sollen wir die Mods in Gruppen gliedern und dann kann man zur Bearbeitung der Rezepte Mats aus der Gruppe wählen? (Also zB Magie/Technik/undefiniert) (ok das ist weniger Codestyle interessiert mich aber doch)
Machen wir ne Liste für Modnamenskürzel oder schreiben wir aus (TC kann ja nu Tinkers Construct oder Thaumcraft sein)
 Bleiben wir bei den Rautenrahmen( Die find ich gut erkennbar)
was fällt euch sonst so ein?

**Comment by DerOliDE** [comment]
Ich habe mal mit einem Wiki Eintrag dazu begonnen und werde nach und nach die Scripts entsprechend anpassen.
https://github.com/combak/ShatteredWorld/wiki/Scripts-Code-Style

**Comment by DerOliDE** [comment]
5 Scripts habe ich schon entsprechend angepasst, wenn es keine einwende oder bessere Vorschläge gibt werde ich ab morgen den Rest angehen.

https://github.com/combak/ShatteredWorld/blob/master/scripts/AppliedEnergistics2.zs
https://github.com/combak/ShatteredWorld/blob/master/scripts/Forestry.zs
https://github.com/combak/ShatteredWorld/blob/master/scripts/Vanilla.zs
https://github.com/combak/ShatteredWorld/blob/master/scripts/chisel2.zs
https://github.com/combak/ShatteredWorld/blob/master/scripts/ThermalExpansion.zs

**Comment by DerOliDE** [comment]
Ich habe mich gerade mal durch alle vorhandenen Scripts gequält und sie nach den Wiki Vorgaben abgeändert. Damit betrachte ich erst einmal diese Diskussion als beendet.
