### ISSUE TITLE
Stone Slab wird von Forest Day überlagert

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#36]
Muß den alles von Forest Day überschrieben werden? Geht das nicht anders zu machen?

**Comment by DerOliDE** [comment]
Wäre es nicht sinnvoller den Fehler bei Forest Day zu posten?

**Comment by DerOliDE** [comment]
Cross Ref: https://github.com/ForestDay/Forest-Day/issues/11

**Comment by jkauven** [comment]
Hat GitHub Schluckauf oder hat @Alheimerjung das Projekt offline genommen? Unter ForestDay ist auf GitHub nix mehr zu finden.

Da sich bisher nix getan hat, wäre es nicht sinnvoll den Konflikt von ShatteredWorld Seite aus zu beseitigen?

**Comment by Nedelosk** [comment]
https://github.com/Nedelosk/Forest-Mods/tree/1.7.10-Dev Das Problem ist schon gelöst, muss nur noch ein update fahren.

**Comment by jkauven** [comment]
top

**Comment by DerOliDE** [comment]
Wo ist die neuste Version versteckt? auf Curse steht noch die 1.4.0i als aktuellste.

**Comment by DerOliDE** [comment]
Workaround kommt in die nächste Version.

**Comment by DerOliDE** [comment]
Item in aktueller Version nicht mehr vorhanden.
