### ISSUE TITLE
für Sky Stone Dust gibt es jetzt keine Rezepte mehr

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#38]

**Comment by DerOliDE** [comment]
Schein ein generelles Problem mit der aktuellen ModTweaker & Thermal Expansion Version zu sein, da kein Änderung mit dem Pulverizer oder Induction Smelter funktioniert.

Cross Ref: https://github.com/jaredlll08/ModTweaker2/issues/132

**Comment by krakel** [comment]
Dadurch kann der Sky Stone Block nicht hergestellt werden. Es würde ein Rezept für den Sky Stone Block ausreichen. Dann kann das Furnace Rezept Sky Stone und auch das Sieben von Sky Stone Dust weg.

**Comment by DerOliDE** [comment]
Wurde in ModTweaker gefixt, wir müssen nur noch auf eine neue Version warten.

**Comment by BakermanLP** [comment]
Ich sehe das als temporären Fix

**Comment by DerOliDE** [comment]
Workaround kommt in die nächste Version.

**Comment by DerOliDE** [comment]
Mit der neuen ModTweaker Version funktionieren die Custom TE Rezepte wieder.

**Comment by DerOliDE** [comment]
Workaround auskommentiert und Induction Smelter läuft.

**Comment by krakel** [comment]
Ist zwar schon geschlossen. Habe durch ein Video gesehen, das ExNihilo ein Rezept ähnlich zu Obsidian drin hat. Lava in ein Stonebarrel und mit Sky Stone Dust drauf klicken erzeugt den Sky Stone Block. Damit brauch man zwar nur noch ein Dust, aber dafür Lava. Der Titel diese Issues stimmt also nicht.
