### ISSUE TITLE
Forbidden Magic die Diabolist Fork

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#39]
Mit dieser Fork muß man Mobs killen. Seltsamer Weise funktioniert das auch, nur der Tooltip sagt was anderes. Komisch

**Comment by krakel** [comment]
Nemax hat das im Cretiv nur erzeugt. Dieser Fork muß schaden machen, sonst kann man die Crystals nicht bauen und der Mod ist sinnlos.

**Comment by Grambosch** [comment]
Fixed. Lasse ich aber offen für Nachzügler

**Comment by DerOliDE** [comment]
Da das vor 27 Tagen als fixed markiert wurde -> closed
