### ISSUE TITLE
das Anfertigen eines Nugget Cast ist ein Problem

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#4]
Man braucht dafür mindestens ein Nugget. Ich habe es über den Umweg: Fuxduct -> Pulverizer erhalten. Später ist auch ein Guldnugget bei einem Mod gedroppt. Man könnte das also so lassen.

**Comment by combak** [comment]
Es gibt da mit Lycanite tatsächlich noch andere Mobs die Nuggets droppen.
Ansonsten gibts ja noch andere Wege. Questbelohnung zB. G,

**Comment by combak** [comment]
Spätestens im Nether bekommt man relativ einfach über die Pigman ein Gold Nugget um sich ein Cast anfertigen zu können mir persönlich gefällt diese Hürde. Das Pulverizer Rezept wird noch abgeschaltet, das funktioniert zZ aus mir unbekannten Gründen nicht. (Oli)

**Comment by krakel** [comment]
Im Nether ist das etwas spät. Man braucht die Nuggets für die Servos. Da aber die Mobs hin und wieder Nuggets droppen, ist das schon ok. Und der Umweg über andere Items ist auch nicht so übel. Da muß man mal etwas Nachdenken. :)

**Comment by combak** [comment]
Ich denke mal das Thema ist gegessen :)
