### ISSUE TITLE
Pulsating Iron Nuggets wie herstellen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#41]
Kann man Pulsation Iron schmelzen und in Nuggets gießen? Kein Rezept dafür im NEI
Das selbe Problem auch bei Vibration Alloy Nuggets.

**Comment by Grambosch** [comment]
Kommt noch. Dafür müssen dann erst liquids erstellt werden. Gut zu wissen

**Comment by DerOliDE** [comment]
Die zwei kommen in die 0.5.4
fixed: https://github.com/combak/ShatteredWorld/commit/d1487e79308e254f3451fd707bd9ada8b79621c1 https://github.com/combak/ShatteredWorld/commit/7a0bb2fc2b38ea257ae3edafcf482c5e874426d1
