### ISSUE TITLE
[Custom Items] Fluid Textures 

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#42]
- <strike>Molten Manasteel (Botania)</strike>
- <strike>Molten Terrasteel (Botania)</strike>
- <strike>Molten Elementium (Botania)</strike>
- Molten Wrought Iron (Garden Stuff)
- Molten Fluxed Electrum (Redstone Arsenal)
- Thaumium (Thaumcraft)
- Pulsating Iron (EnderIO)
- Vibrant Alloy (EnderIO)
- Molten Void Metal (Thaumcraft)
- Molten Electrical Steel (EnderIO)

**Comment by Grambosch** [comment]
Ich hab mir dazu was angeguckt Tutorials und so und versteh immer noch nicht mehr...

**Comment by Nedelosk** [comment]
Ich mach das am Wochenende im Moment habe ich nicht genügend Zeit dar führ, dann aber wirklich.

**Comment by DerOliDE** [comment]
Hab mal eine Test Texture eingefügt, in den "resources/customitems/textures/blocks" Ordner sollen dann die ganzen fertigen Texturen, dort werden sie automatisch geladen. Die Test Texture kann dann ersetzt werden sieht eh scheiße aus. ^^

**Comment by DerOliDE** [comment]
Molten Void Metal wandert noch auf die Liste

**Comment by DerOliDE** [comment]
Und noch eins Molten Electrical Steel. :)

**Comment by DerOliDE** [comment]
Restliche Texturen aus vorhandenen Texturen umgefärbt, sind zwar keine Meisterwerke aber Texturen. ^^ closed
