### ISSUE TITLE
Phased Iron Dust -> Pulsating Iron Ingot

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#43]
der Phased Iron Dust aus BC Additions wird durch schmelzen zu Pulsating Iron aus EnderIO.

**Comment by DerOliDE** [comment]
Selbe Spiel:
Phased Gold Dust (BC Additions) wird durch schmelzen zum Vibrant Alloy Ingot (EnderIO)

**Comment by Grambosch** [comment]
Hab grad geschaut: Selbe Zutaten selbes Product anderer Name. Wenns im OD ist kein Problem

**Comment by DerOliDE** [comment]
Also Feature. ^^
