### ISSUE TITLE
Aktueller Status alle Bee Hives

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#44]
Habe mir mal die Bee Hives angeschaut und wie man die bekommen kann:

Forestry findet alle in der Welt. Außer End Hive habe ich noch nicht geschaut. Außerdem kann man alle über Ex Nihilo herstellen.
Scented Artifical Hive = Artifical Hive + Barrel + Seed Oil
Artifical Hive = Hay Bale + Silk Mesh
- Forest Hive = Induction Smelter + Scented + Oak Leaves x8
- Swamp Hive = Induction Smelter + Scented + Mycelium x8
- Meadows Hive = Induction Smelter + Scented + Grass Block x8
- Desert Hive = Induction Smelter + Scented + Sand x8
- Jungle Hive = Induction Smelter + Scented + Vines x8
- Snow Hive = Induction Smelter + Scented + Ice x8

Extra Bees ist halb und halb
- Rock Hive überall im Stein
- Marble Hive im Twilight Forest
- Nether Hive = Fluid Transposer + Scented + Restone x8000
- Water Hive = Fluid Transposer + Scented + Water x8000

Magic Bees findet man wohl auch überall. Habe bis jetzt nur Curios und Unusual Hive gefunden. Außerdem gibt es zwei Arten diese herzustellen
Ex Nihilo in den Biomen mit Scented Artifical Hive
- Deep Hive = Scented + Mountain Biom
- Infernal Hive = Scented + Nether Biom
- Curious Hive = Scented + Forest Biom
- Oblivion Hive = Scented + End Biom
- Resonating Hive = Scented + Desert Biom
- Unusual Hive = Scented + Jungle Biom

Ex Astris (weiß nicht, ob das aktiv ist)
- Mana Infused Artificial Hive in einem Barrel mit Wichwater oder sowas herstellen
- Dann mit verschiedenen Rezepten in der Arcane Workbench bauen.
  siehe https://github.com/LoveHoly/Ex-Astris/wiki/Mana-Infused-Artificial-Hive

**Comment by krakel** [comment]
Ich habe mal alle Bienen aufgenommen, etwas vorsortiert und in eine Tabelle aufgenommen.
https://docs.google.com/spreadsheets/d/1bm-IT8f4NWGQekFisXKkUxYYGjOnBzI0MAHONr-8TUY/edit#gid=0
Wirklich Problematisch ist da eigentlich kaum was. Man muß auch bedenken, dass das Züchten sehr schwer sein wird.

**Comment by krakel** [comment]
Liste der Bienen sind in der Tabelle überarbeitet. Wirklich traurig was aus den Bienen geworden ist, kaum was nützliches dabei. Ich meine von den Mods aus.

**Comment by Grambosch** [comment]
Ist halt ne alternative Ressourcengenerierung und da auch nur begrenzt. Nichts desto trotz werden die mit Gendustry/genetics wieder zu einfach. Aber die Mutatoren aus Extrabees können bleiben. Einzig die Ingredienzen muss man mal drüberschauen

**Comment by krakel** [comment]
Wir haben drüber gesprochen und es werden Begrenzungen für Apiary und Alvery eingebaut. Das reicht, weil sich das am Ende sowieso keiner antut.
