### ISSUE TITLE
Draconic Staff of Power -> Zu mächtig

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#45]
Auch wenn der Stab extrem teuer ist, kann er einfach zuviel und vor allem der 25x25 Flächenschaden mit 60 Dmg ist meiner Meinung nach viel zu viel.

Ich wäre für deaktivieren.

**Comment by Grambosch** [comment]
Extrem teuer halte ich für untertrieben. Mächtig ist der sicher aber wenn den wer im erstenquartal bis halben Jahr  baut (RL) dann Respekt. Mir ist es em Endeffekt wurscht werde mein Draconium nicht auf so was verschwenden. Allein das Aktivierungsritual für das Awakened Draconium..._würg_

**Comment by DerOliDE** [comment]
Könnte man den Flächenschaden via Config auf 3x3 einschränken würde ich Dir zustimmen aber 25x25 bei 60 Dmg ist einfach übertrieben egal wie unwahrscheinlich es ist das jemand das Teil baut. Noch dazu  könnte man im PvP eine ganze Versammlung damit wortwörtlich sprengen.

**Comment by Grambosch** [comment]
Ich werf morgen mal den Taschenrechner an . Ich vermute stark das es nicht nur unwahrscheinlich sondern fast unmöglich ist den zu bauen. Aber wie gesagt mir wurscht sollen andere was zu sagen.

**Comment by krakel** [comment]
Dann will ich das tun. Da es so schwer ist das zu bekommen würde ich es drin lassen. Damit hat man ein fast unmögliches Ziel.

**Comment by DerOliDE** [comment]
Nach der letzten Diskussion im TS habe ich das Ding erst einmal deaktiviert.
