### ISSUE TITLE
Elevator mit Treibstoff

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#47]
Höre gerade im Direwolf, das der Elevator von OpenBlocks auf Experience als Treibstoff umgestellt werden kann. Ist zwar nicht die Welt, aber immerhin eine Bedingung für die Benutzung.

**Comment by Grambosch** [comment]
Muss ich sagen bin ich kein Fan von. Der "Treibstoff" ist nicht ohne und falls der leer ist ist auch doof.
Ich hab damit schon gespielt und die NAchteile überwogen deutlich

**Comment by DerOliDE** [comment]
Finde XP als Treibstoff auch etwas suboptimal, eventuell kann man ja drüber nachdenken einfach das Rezept etwas teurer zu gestallten.

**Comment by BakermanLP** [comment]
Lieber nicht, da gab es immer jede Menge gemecker aus der Community.

**Comment by DerOliDE** [comment]
Treibstoff allgemein abgelehnt -> closed :)
