### ISSUE TITLE
Gedankengänge zum Serverbetrieb

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#52]
Da wir jetzt Custom NPCs drin haben und die auch als Command Block "missbraucht" werden können, wächst bei mir der Gedanke wieder eine Lobby zu verwenden und via MultiWorld jedem Spieler eine eigene Dimension (Sky Island) zu erstellen. 

Könnte man dann via Quest realsieren mit der man sich eine Welt erstellen und ggf. danach eine Quest um diese bei nicht gefallen wieder zu reseten.

Vorteil:
- Künstliche Limitierung, die Spieler haben "nur" eine ca 256x256 große Insel.
- Wenn Spieler/Dimensionen sagen wir mal 1 Monat nicht mehr aktiv sind könnte man sie in einen inaktiv Ordner verschieben, was den Server entlastet. Müsste man schauen wo dann der Spieler spawnt, wenn seine Dimension nicht mehr da ist.
- Bei Server Problemen kann man durch abschalten einzelner Dimensionen das Problem ggf. schneller eingrenzen bzw. finden.

Nachteil:
- Teamplay in größeren Teams wird erschwert aber für größere Teams könnte man eventuell eine Sky Dimension mit World Border arrangieren.
- Handeln zwischen den Spielern wird erschwert. Lässt sich das ggf. mit der Forestry Trading Station abfedern?
- Eingeschränkte Biom-Vielfalt (Default, Snow, Jungle)

**Comment by DerOliDE** [comment]
Was ich auch für eine gute Maßnahme halten würde, ist das man nur via Forum/Website Registrierung an die Serverdaten gelangt. Ich würde da sogar soweit gehen und sagen Forum-Name muss gleich Minecraft-Name sein und das dann via Whitelist regeln.

**Comment by krakel** [comment]
Das erschreckt mich jetzt schon. Jeder Spieler eine eigene Dimension???
Ich verstehe den Sinn dahinter nicht wirklich.

**Comment by DerOliDE** [comment]
Zunächst sind das einfach erst einmal ein paar Gedanken zu dem Thema die ich hier niederschreibe, um darüber zu diskutieren.

Sinn dahinter ist mehr Kontrolle über das was auf dem Server abläuft (siehe Vorteile), wenn Dir daran etwas nicht passt oder Dich "erschreckt" dann ergänze es zu den nachteilen.

**Comment by BakermanLP** [comment]
Die Dimensionen brauchst du, sofern keine chunloader aktiv sind,
normalerweise nicht "löschen". Und ja, er hat Recht, man kann manches
besser debuggen. Siehe z.B. /cofh tps ... Und manche Fehlermeldungen.

Uwe Dörl notifications@github.com schrieb am Fr., 15. Mai 2015 18:03:

**Comment by DerOliDE** [comment]
Beim rauskopieren nach Zeitraum x hatte ich eher im Kopf das Backup schrumpfen zu lassen und kA wie oder ob Dimensionen auch bei Inaktivität nicht irgendwie vom Servercode durchlaufen werden.

**Comment by BakermanLP** [comment]
Da gibt es viele alternative Methoden. Ich kann da gerne, ebenso beim
Serverbetrieb helfen, sofern gewünscht.

Oliver notifications@github.com schrieb am Fr., 15. Mai 2015 18:43:

**Comment by krakel** [comment]
Ich habe sicherlich etwas falsch verstanden. Für mich hört sich das aktuell danach an, das jeder in seiner eigenen Dimension für sich allein spielt. Korrigiert mich bitte, wenn es so ist.

**Comment by DerOliDE** [comment]
Eigene Dimension oder als Team inkl hin un her wechseln mit bspw. tpa (teleport zu spieler) befehl.

**Comment by Grambosch** [comment]
Also seh ich das richtig: Jeder kriegt ne Baudimension wo er machen kann was er will und alle kriegen ne Adventure/Quest World wo wir Fraktionshanseln und Questreihen einsetzen können?

**Comment by DerOliDE** [comment]
Jeder Spieler oder mehrere Spieler als Team bekommen eine Dimension (eine fliegende Insel oder bei größeren Teams Sky Dimension mit World Border) zum bauen.

Dann soll es noch eine Lobby-Welt geben (Overworld aber auch nur eine fliegende Insel), da kann man dann den Questpart/CustomNPC rein werfen und ich würde wieder eine Mining Welt (Sky Dimension) zum erforschen mit rein nehmen.

**Comment by DerOliDE** [comment]
Was ich noch vermisse ist etwas zum Handeln wie bspw. der Trade-O-Mat aus IC2, das ist leider so nicht mit den CustomNPCs möglich, da kann man zwar auch handeln aber es greift auf kein vorhandenes Material zurück bis es leer ist, sondern man kann immer tauschen.

**Comment by Grambosch** [comment]
Ich verstehe den Gedankengang. Mach dir mal Gedanken ob wir ne "Quest-World machen" Da würd ich dann wirklich mit den Custom NPC arbeiten. Auf einer Lobbyinsel wäre es evtl zu klein und in der "Mining Welt" zu viel Arbeit.

**Comment by DerOliDE** [comment]
Dann nehmen wir halt die Lobby/Overworld als Sky Dimension statt nur ne Insel und machen da auch die Quests mit rein, wenn möglich würde ich die Overworld dann eh im Adventure Mode laufen lassen, damit dort keiner etwas abbauen kann.

Oder wir stopfen die Lobby ins Deep Dark wie in Sieged als Zuflucht nach der Katastrophe und die Overworld wird die Questwelt.

**Comment by Grambosch** [comment]
@BakermanLP  Danke für dein Angebot das nehmen wir gerne an ( Ich lehn mich da mal aus dem Fenster) Wäre auch erst mal nett wenn wir , für die GIthubfaulen, dein Forum mitbenützen dürften?

**Comment by DerOliDE** [comment]
Mal ein konkreter Vorschlag für die Welten:
- Deep Dark -> Lobby/Anfang mit World Border ( Deep Dark Portal crafting deaktivieren )
- Overworld (Sky Dimension) -> Questing Welt mit World Border 
- Player World (Survival Skyland)  -> Die benötigten generator-settings stehen nun auf dem TODO (https://github.com/combak/ShatteredWorld/issues/78) Ggf. auch mit World Border.
- Vanilla Nether -> deaktivieren, damit es keine Nether Portal Probleme (https://github.com/combak/ShatteredWorld/issues/78) gibt
- Custom Nether -> Nur wie Teleport NPC erreichbar mit verschiedenen Einstiegspunkten im Nether bspw Nord, Ost, Süd und West mit je 1000 Blöcken Abstand von Nullpunkt.

**Comment by BakermanLP** [comment]
Nachdem der Oli bisher nicht dazu kam, die Foren einzurichten, habe ich das mal kurzerhand gemacht. Es gibt 2 Foren, einmal im öffentlichen Bereich (alle Lesen, registrierte Schreiben). Zusätzlich gibt es noch einen internen Bereich, der nur von einem ausgewählten Personenkreis gelesen und beschrieben werden kann.

**Comment by DerOliDE** [comment]
Danke bin gestern so spät nachhause gekommen hatte keine Lust mehr das zu machen. ^^

**Comment by BakermanLP** [comment]
Bezüglich Trading sollte man sich mal, da es ja hier relativ fest gesetzt ist, die Funktionen aus ForgeEssentials mal ansehen. Keine Ahnung, ob die eventuell schon reichen.

Ich fände es auch nicht schlimm, wenn:
Player World (Survival Skyland) -> Die benötigten generator-settings stehen nun auf dem TODO (#78) Ggf. auch mit World Border.
Das einfach eine SkyDimension wäre, mit aktiviertem Worldborder

Das geht nämlich bereits.

**Comment by DerOliDE** [comment]
Wenn Du das Economy Module meinst, da muss ich sagen gefällt mir die harte Währung (https://github.com/combak/ShatteredWorld/issues/68) etwas besser als mit Commands zu hantieren.

**Comment by Grambosch** [comment]
Bzgl Lobbywelt: Wir könnten das "Last Millenium" nehmen . Das ist eine Voiddimension  da kann man was drumherum basteln als "Start/Tutorial/wasweiß ich" Gebäude

**Comment by BakermanLP** [comment]
Ich bin gerade noch über folgendes gestolpert:
https://gitlab.prok.pw/Prototik/KCauldron/blob/master/README.md
Keine Ahnung wie Legal oder Illegal das ist. Laufen tut er natürlich.
Fertige Builds findet man hier: http://tcpr.ca/cauldron

**Comment by DerOliDE** [comment]
@BakermanLP Riskieren würde ich es nicht, das Cauldron Projekt hat ja auch ein DMCA Takedown kassiert und solange die problematischen Code Passagen nicht umgeschrieben wurden, kann jedes andere darauf passierende Projekte das selbe Schicksal ereilen.

**Comment by BakermanLP** [comment]
Ich stelle hier mal einen weiteren Punkt zur Diskussion, da er hier wunderbar rein passt. Wollen wir vielleicht komplett auf Chunkloader verzichten? Butze, Oli und ich spielen ja zur Zeit Agrarianskies2 und dabei haben wir keine Chunkloader im Einsatz. Das funktioniert auch so ganz gut. Dadurch würden weniger Server Resourcen verbraucht, da nur das geladen ist, bei dem auch der Spieler Online ist.

**Comment by DerOliDE** [comment]
Wäre denkbar, da sofern man online ist die komplette Insel geladen wird und man nicht mehr den Spagat zwischen Basis und Quarry/Pumpe benötigt. 

Wobei der ChunkLoader auch nur 9 Chunks pro Spieler läd und das auch nur wenn der Spieler online ist, das dürfte auch nicht so die Welt sein.

**Comment by BakermanLP** [comment]
Chunk geladen oder nicht geladen, wenn der Spieler Online ist. Man könnte damit zumindest die Probleme, die wir zum Teil schon mal hatten, komplett ausschalten.

**Comment by krakel** [comment]
Ich hatte bis jetzt auf dem Testserver keine Notwendigkeit für einen Chunkloader. Außerdem wird bei einer höheren Aufbaudichte von diversen Maschienen das Minecraft System sowieso Probleme beim Chunk enladen haben. Der Aufbau in separaten Welten ist Chunkloading genug.

**Comment by krakel** [comment]
In der Version 1.7.10d von Costum NPCs soll das falsche json-Format gefixed sein.
http://minecraft.curseforge.com/mc-mods/221826-custom-npcs/issues/1520

**Comment by DerOliDE** [comment]
Lustig die Version die ich drauf habe heißt auch 1.7.10d ist aber aus dem Mai... tolle Versionierung

**Comment by Grambosch** [comment]
So hat hier noch wer was? Sonst Close
