### ISSUE TITLE
Null Pointer beim NetherOreAbbau mit TC Hammer

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#53]
http://pastebin.com/PXYtgB3s

**Comment by DerOliDE** [comment]
Nether Ores allein ist es nicht, da gibt es irgendein Cross Mod Problem.

**Comment by Grambosch** [comment]
Fakt ist mit dem overwrite=false ist das Problem gelöst...warten wir ab was uns die neuen Versionen bringen

**Comment by DerOliDE** [comment]
Wurde scheinbar gefixt, ich kann es nicht mehr reproduzieren sowohl mit Hammer als auch Pickaxe mit oder ohne Silk Touch.
