### ISSUE TITLE
Bekomm ich eine OP only TARDIS? ^^

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#54]

**Comment by Grambosch** [comment]
Mach was du willst.. ist unser Modpack...

**Comment by krakel** [comment]
Was kann man damit, bzw. mit dem Mod, anstellen?

**Comment by DerOliDE** [comment]
@Grambosch Eben >unser< Modpack und nicht meins darum frage ich. ;)

@krakel Man kann mit der TARDIS damit durch Raum und Zeit reisen, wobei Zeit bei Minecraft natürlich nicht funktioniert, sprich man kann zu jeder beliebigen Koordinate und Dimension reisen, das kostet Energie die sich sehr langsam auflädt. 

Die TARDIS sammelt mit jeder reise Erfahrung und lässt sich leveln bspw. ist ein Sprung in andere Dimensionen anfangs nicht möglich, da man nur über max. 1000 Energie verfügt und der Sprung min. 2000 kostet.

Dann bietet die TARDIS noch die Möglichkeit ihre inneren Räume modular zu erweitern, was auch je nach Level beschränkt ist.

Mir geht es dabei auch weniger um die Funktion als einfach darum eine TARDIS zu haben. Doctor Who Fan und so. ;-)

In der neuen Project Phoenix Version ist die Mod enthalten, da kannst Du Dir das Ganze auch mal anschauen.

**Comment by Grambosch** [comment]
mach mal rein schauen wir uns an.

**Comment by DerOliDE** [comment]
Dann nehme ich die Mod mal in die 0.5.7 auf.

**Comment by DerOliDE** [comment]
Gimmick geschlossen. ^^
