### ISSUE TITLE
Compact Machines

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#55]
Wenn wir nun alle Spieler in eine eigene Dimension packen, dann wäre Compact Machines für die Fehlersuche und sonstige Analysen etwas kontraproduktiv, da ein Teil aller Maschinen wieder zusammen in der Compact Machines Dimension landet.

Mod entfernen ja/nein?

**Comment by krakel** [comment]
Ich würde den Mod rausnehmen. Wenn man alles in einem Block klatschen kann, wo bleibt da noch der Sinn von Minecraft.

**Comment by DerOliDE** [comment]
Bei Phoenix war es halt dazu gedacht die Maschinen außer Sicht zu bekommen damit es nicht gerendert werden muss, weil wir in RETv7 die Erfahrung mit viel Maschinen auf einen Fleck -> FPS Einbruch hatten.

**Comment by DerOliDE** [comment]
Entfernt in 0.5.8
