### ISSUE TITLE
Woher kommt der Infernal Blast Furnace?

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#57]
Und was sind Native Erze bspw Native Iron Cluster? Brauch man das?

Pfuscht mir etwas in mein Ore Processing rein und ich hab kA ob oder wie ich das manipulieren kann.

**Comment by krakel** [comment]
Infernal Blast Furnace ist glaub ich Thaumcraft. Sollte sicher der http://ftbwiki.org/Infernal_Furnace sein.

**Comment by BakermanLP** [comment]
Beides Thaumcraft

Uwe Dörl notifications@github.com schrieb am Sa., 23. Mai 2015 15:12:

**Comment by DerOliDE** [comment]
Ist es der Infernal Furnace oder ist das noch irgendein anderer? Das Blast dazwischen irritiert mich, den Infernal Furnace kenne ich auch.

**Comment by krakel** [comment]
Der gehört zu WitchingGadgets, ein Zusatz zu Thaumcraft.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2371563-thaumcraft-addon-witching-gadgets
im Spoiler "Cross-Mod Compatibility" ist der zu sehen; da sind auch die Native Cluster, was immer das auch ist

**Comment by Grambosch** [comment]
Native Cluster waren mal ein Bonus zum Erz der rauskommen konnte wenn man die Pickaxe of the Core von Thaumcraft verwendet. Mittlerweile ist es ein "Erz kann beim Abbau zu einem Cluster werden" der ist dann 2 Barren wert. Also die Verdopplung bei Thaumcraft. DIe Blast furnaces sind nicht weiter wild

**Comment by DerOliDE** [comment]
Das Ganze ist geklärt und die Native Cluster wurden ans Ore Processing angepasst.
