### ISSUE TITLE
Rezept Konflikt Custom NPC AgriCraft

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#58]
Diamond - Diamond Nugget AgriCraft
Diamond - Diamond Bullet Custom NPC 

Die Rezepte sind gleich und es wird das Custom NPC genommen

**Comment by DerOliDE** [comment]
Tendenziell würde ich sagen Custom NPC Rezept abschalten.

**Comment by Grambosch** [comment]
Wer schießt schon mit Diamanten. Script ist schon da

**Comment by DerOliDE** [comment]
http://richtigteuer.de/2010/11/15/mit-diamanten-besetzte-kalaschnikow-patronen-als-gurtelschnalle/

:D
