### ISSUE TITLE
Forest Day Files gehen nicht kaputt

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#59]
https://github.com/ForestDay/Forest-Day/issues/12

**Comment by krakel** [comment]
Wenn man mal mit der File ein Shift-Click probiert geht das nicht. Wenn aber danach die File mit Hand in die Workbench legt, behält man ein zweite im Inventar (Dup Bug).

**Comment by DerOliDE** [comment]
Fixed in 0.1.6beta
