### ISSUE TITLE
Exception durch FluidRegistry

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#6]
Ich bekomme immer mal wieder Exception durch net.minecraftforge.fluids.FluidRegistry.isFluidRegistered mit anschließendem Absturz des Clients.
Diese Problem wurde vom Forgeteam in https://github.com/MinecraftForge/MinecraftForge/issues/1794 gefixt. Wir sollten so schnell wie möglich auf ein entsprechendes Forges wechseln.

**Comment by krakel** [comment]
Tinker Schmelze stolpert hin und wieder darüber. Forestry Thermionic Fabricator scheiter reproduzierbar und damit aktuell nicht nutzbar. Wenn man Fluiducts neu setzt passiert der Absturz auch.

**Comment by combak** [comment]
Eine höhere Forge Version zieht z.Z. leider massig Probleme mit anderen Mods mit sich, da Forge irgendwas an dem Fluid Registry Zeug verändert hat und noch nicht alle Mods mitgezogen haben. Ich fürchte da werden wir noch 2-3 Wochen warten müssen. (Oli)

**Comment by DerOliDE** [comment]
Fixed in 0.5.2 für:
- Tinker's Construct
- Forestry
- Thermal Dynamics
