### ISSUE TITLE
Custom Recipe für Nugget Cast

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#60]
Ich habe seit Samstag versucht einen Goldnugget zu farmen. Das ging nach hinten los. Kein Nugget aber zig Mumienfrauen weinen um ihre Männer.
Sollen wir evtl nen Nuggetcast hinzufügen aus der Schmelze? Dianugget gibts ja als Vorlage

**Comment by DerOliDE** [comment]
Gibt doch noch die Möglichkeit über den Pulverizer an diverse Nuggets zu kommen aber können auch gern noch eine Vorlage hinzufügen.

**Comment by DerOliDE** [comment]
Added in 0.5.8
