### ISSUE TITLE
Ore Processing

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#61]
Im Skript sind zB Iron Nuggets noch auskommentiert. Soll das so?

**Comment by DerOliDE** [comment]
Beispiel?

Manche Dinge zicken nach dem ModTweaker und Thermal Expansion update rum.

**Comment by Grambosch** [comment]
zB Iron Nuggets sO (:

**Comment by DerOliDE** [comment]
Bei Beispiel dachte ich eher an welche Mod oder welcher Verarbeitungsprozess. ^^ aber egal die Teile über Tinkers Construct habe ich wieder mit rein genommen, das habe ich nachdem testen vergessen.

https://github.com/combak/ShatteredWorld/commit/a3664483ffbfc4e0bf1c23a04052824a36d600da

**Comment by DerOliDE** [comment]
Sollte jetzt alles wieder drin sein

**Comment by krakel** [comment]
Da ist noch ein Rezept für Thaumium Nuggets drin !!!
Edit: auch für Void metal Nuggets
Edit2: ganz Thaumcraft hat noch Rezepte für alle Nuggets !!!

**Comment by DerOliDE** [comment]
Geht es auch genauer? Ich muss den ganzen Mist eh nochmal genau durchgehen, das macht nur keinen Sinn solange Thermal Expansion sich mit dem ModTweaker querstellt.

**Comment by krakel** [comment]
Mir ist klar das das eine heiden Arbeit ist. Bin auch nur beim Analysieren der Quests drauf gestoßen. Wir sollten den Bug offen halten.
Hier nochmal eine aktuelle Liste aller Nuggets:
(außer diesem Phytogenetic Insolator der das aus einigen Seeds zuläßt)
- Gold (Vanilla): Infernal Blast Furnace vom Ingot, Furnace von Coin und Oreberry
- Diamond (AgriCraft): Crafting
- Electrical Steel (Ex Astris): Crafting
  rr- Manasteel (Botania): Crafting
- Elementium (Botania): Crafting
- Iron (Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Copper (Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Tin (Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Aluminium(Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Cobalt (Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Ardite (Tinker): Infernal Blast Furnace vom Ingot, Furnace von Oreberry
- Silver (Tinker): Infernal Blast Furnace vom Ingot
- Lead (Tinker): Infernal Blast Furnace vom Ingot, Pulverizer von Fluiduct
- Thaumium (Thaumcraft): Crafting
- Void metal (Thaumcraft): Crafting
- Copper (Thaumcraft): Crafting
- Copper (Thermal Fundation): Pulverizer von Fluiduct
- Ferrous (Thermal Fundation): Infernal Blast Furnace vom Ingot
- Shiny (Thermal Fundation): Infernal Blast Furnace vom Ingot
- Mana Infused (Thermal Fundation): Infernal Blast Furnace vom Ingot
- Invar (Thermal Fundation): Pulverizer von Fluxduct

In dem Zusammenhang müssen dann auch nochmal alle Cast Möglichkeiten kontrolliert werden. Nicht alle Nuggets sind aktuell möglich, aber wohl auch nicht notwendig.
Was war eigentlich nochmal der Weg um zu einem Nugget Cast zu kommen?

**Comment by DerOliDE** [comment]
Wenn Du mit den Infernal Blast Furnace das meinst was als Beiprodukt aus den Native Cluster rauskommt das ist so gewollt, da habe ich nur dafür gesorgt das auch die Nuggets rauskommen ( Vanilla > Tinkers > TE > rest ) die ich will. ( see: https://github.com/combak/ShatteredWorld/commit/01ba81ac22f19fba42da17467b4d28eff5379663 )

Die Oreberries gehen noch im Redstone Furnace und TE ist z.Z. nicht Mine-/ModTweaker fähig, ebenso der Pulverizer.

Das Thaumium und Void Metal habe ich gestern schon geändert, siehe Reference zu den Commits über Deinem Post.

Du kannst Dir aus einem Diamond ein Diamond Nugget craften und damit den Nugget Cast machen, der Weg ist so gewollt, eventuell kann man noch irgendein Tool in das Crafting Rezept einbauen.

Den Rest schaue ich mir morgen an, da habe ich heute keine Zeit für der Grill ruft ;-) Ich werde den Issue mal wieder aufmachen und in Ore Processing umbenennen.

**Comment by Grambosch** [comment]
Also allesamt vom Infernal Blast furnace kannst du ausblenden. Du brauchst a) den Infernal Blast Furnace b) ne Thaumcraft Pickaxe (die aus dem Infusionaltar Name fehlt gerade) c) ein Erz das du mit der Picke abbaust und da kommt dann noch ein Cluster raus. Die Cluster sind im Prinzip die Erzverdopplung von Thaumcraft während der Infernal Blast Furnace die Verdreifachung mit Chance auf nen Bonusnugget ist... Wichtig ist halt das überall das gleiche rauskommt.
Zum Tool fürs Dianuggetrezept: Es gibt bei Wiotching Gadgets ein Gemcutting Tool allerdings weiß ich da grad nicht ob das ohne Forschung baubar ist

**Comment by DerOliDE** [comment]
Der Gemcutter gefällt mir :)

**Comment by DerOliDE** [comment]
Todo Glowstone via Smeltery

**Comment by Nedelosk** [comment]
Für meinen Mod MineTweaker3 Rezepte:

Rezept Hizufügen:
mods.nedelosk.mm.modular.add(IIngredient[] inputs, IIngredient[] outputs, int speedModifier, int energy, String recipeName);

Rezept entfernen:
mods.nedelosk.mm.modular.remove(IIngredient result, String recipeName);

Rezept Name:
Alloy Smelter = "AlloySmelter"
Centrifuge = "Centrifuge"
Pulverizer = "Pulverizer"
Saw Mill = "SawMill"

**Comment by DerOliDE** [comment]
Fluid zum schmelzen hinzufügen:
- Dark Steel (EnderIO)
- Awakened Draconium (Draconic Evolution)

Optional (schmelzen->block wird nicht fürs crafting benötigt):
- Redstone Alloy
- Conductive Iron
- Energetic Alloy
- Soularium

**Comment by DerOliDE** [comment]
OreDict Aluminium (Forest Day) <-> Aluminum (Tinkers Construct)

Cross-Ref.: https://github.com/Nedelosk/Forest-Mods/issues/9

**Comment by krakel** [comment]
Sehe gerade, das sich aus den Metall Grains der Bienen nur Metall Dust von BuildCraft Additions gemacht werden kann. Dieser Dust kann nicht in normales Erz geschmolzen werden, sondern nur innerhalb BuildCraft Additions weiter benutzt werden.

**Comment by krakel** [comment]
Ah, ein Test zeigt, das es doch geht. NEI zeigt wie immer nicht alles an. Also Entwarnung.

**Comment by DerOliDE** [comment]
Erst testen dann meckern. ^^

**Comment by DerOliDE** [comment]
Nach 0.7.2 update komplett durchchecken.

**Comment by DerOliDE** [comment]
- Energetic Alloy Ingot & Block nicht gießbar
- Redstone Alloy Ingot & Block nicht gießbar
- Conductive Iron Ingot & Block nicht gießbar
- Soularium Ingot & Block nicht gießbar

**Comment by DerOliDE** [comment]
Schmelz Temperaturen beim Dust überprüfen. (siehe Dark Steel)

**Comment by krakel** [comment]
Habe mal alles so durch gesehen. Einziges schweres Problem, Manasteel Nuggets werden gecrafted. Ansonsten habe ich nur unglückliche Überdeckungen von Mods gesehen. Einige Blöcke lassen sich nicht herstellen, werden aber auch nicht gebraucht laut NEI.

**Comment by DerOliDE** [comment]
Alle Erz Items oder Blöcke die nicht herstellbar sind, sollten zu irgendwelchen anderen OreDict kompatible sein die herstellbar sind bspw. ThermalFoundation Copper Block nicht herstellbar aber dafür der Copper Block aus Tinkers Construct.

**Comment by krakel** [comment]
Das ist es auch. Nur ist der OreDict Mod, der als default auftaucht nicht immer optimal und auch nicht einheitlich. z.B. krallt sich AppleMilkTea meist dir Krone im OreDict und das sieht dann komisch aus.

**Comment by DerOliDE** [comment]
AppleMilk&Tea ist ja noch neu und quasi unbearbeitet :)
