### ISSUE TITLE
Fast Leave Decay

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#62]
Ist zwar schon in Custom NPCs, warum auch immer, enthalten aber ist doch etwas langsamer als die entsprechende Mod.

Reicht uns das oder soll noch eine extra Fast Leave Decay Mod mit rein?

**Comment by Grambosch** [comment]
mir persönlich reicht das so wie es ist

**Comment by DerOliDE** [comment]
Keine weitere einwende -> closed
