### ISSUE TITLE
Tiers of Technic

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#63]
Also wie bereits angesprochen sollten die Technischen Gerätschaften in bis zu drei Tiers unterteilen, 
und den Tiers einen Teilepool zuteilen. Bei den Generatoren ist das zB schon grob geschehen.
Vorschlagsliste
Tier 1 Maschinen:

```
             Ender IO
                              Sag Mill
                      Basic Capacitor Bank
    Thermal Expansion
                              Redstone Furnace
                              Pulverizer
                              Sawmill
                              Igneous Extruder
                             Glacial Precipitator
                             Aqueos Accumulator
                             Leadstone Energy Cell
                             Hardened Energy Cell                     
                     Portable Tank
                  Hardened Portable Tank
```

Tier 2 Maschinen:

```
             Ender IO
                      Alloy Smelter
                      Capcitor Bank
                      Painting Machine
                      Slice N Splice
                      The Vat
                      Farming Station
                      Wireless Charger
    Thermal Expansion
                      Induction Smelter
                      Fluid Transposer
                      Redstone Energy Cell
                      Reinforced Portable Tank
```

Tier 3 Maschinen:

```
             Ender IO
                      Vibrant Capacitor Bank
                      Dimensional Transceiver
                      Travel Anchor
                      Powered Spawner
                      Killer Joe
    Thermal Expansion
                      Cyclic Assembler
                      Energetic Infuser
                      Phytogenic Insolator
                      Resonant Energy Cell
                      Resonant Portable Tank
                      Tesseract                       
```

**Comment by BakermanLP** [comment]
Tier 2 Maschinen -> Ender IO -> Alloy Smelter ist schwierig, würde für mich eher zu Tier 1 gehören, hat aber leider dafür etwas mehr Möglichkeiten. Eventuell den Alloy Smelter + ThermalExpansion Induction Smelter in Tier 1 übernehmen. Die meisten der Rezepte, die man in beiden Maschinen herstellen kann, kann man auch in einem Tinkers Construct Offen Schmelzen. Ich denke, dass hier keine Nachteile entstehen würden.

Zu den Tier 2 Maschinen gehören für mich die automatischen Maschinen von ExAstris dazu (AutoSieve, AutoHammer).

**Comment by DerOliDE** [comment]
Alle Maschinen die zur Produktion von Flüssigtreibstoff dienen sollten vom Aufwand klar nach der Kohleproduktion ( Baumfarm ) liegen. Der Vat ( Rocket Fuel ) aus EnderIO wäre schon vorher eine Option und dürfte effizienter als Kohle sein.

**Comment by Grambosch** [comment]
Forestry muss also auch noch was rein evtl noch ein paar Maschinen aus "kleineren" Mods

**Comment by DerOli82** [comment]
Cross-Ref.: https://github.com/combak/ShatteredWorld/commit/f1155f19643610bfc72292592256c30a196d1dd3 für Feedback

**Comment by Grambosch** [comment]
Gemeint war ob die Rezepte so in Ordnung sind (oder zuschwer/leicht/Unsinn :) Aber schön das du wenig korrigieren musstest

**Comment by DerOliDE** [comment]
@Grambosch Ich hab es mir noch überhaupt nicht angeguckt, ich habe nur Deine Änderung hier verlinkt, damit man die Änderungen in Übersicht hat. :)

**Comment by DerOliDE** [comment]
Ein paar Fehler im Script korrigiert aber irgendwas passt noch immer nicht, es werden keine Rezepte für die Maschinen angezeigt.

**Comment by Nedelosk** [comment]
Einige gehen andere nicht komisch.

**Comment by Nedelosk** [comment]
Es liegt daran das es die Items nicht gibt wie ore:plateInvar.Muss Oli mit dem nächsten Patch nach patchen habe ich eben hinzugefügt.
PS: Liegt im Dropbox

**Comment by DerOliDE** [comment]
@Nedelosk Brauch Dein Mod Invar Plates? Wenn ja okay, wenn nein füg nix hinzu was Du nicht brauchst, das mache ich dann via Contenttweaker.

**Comment by Nedelosk** [comment]
@DerOli82 Später für die Rezepte brauche ich sie dann.

**Comment by DerOliDE** [comment]
Okay schaue ich mir dann morgen an heute Abend habe ich keine Zeit.

**Comment by DerOliDE** [comment]
Rezepte funktionieren jetzt alle mache ich später noch eine Version draus

**Comment by Nedelosk** [comment]
Habe gerade noch mal eine neue Version hochgeladen habe noch einen Bug gefixt.

**Comment by Grambosch** [comment]
So , was fehlt hier noch? Außer AE ein kleines bißchen?

**Comment by Grambosch** [comment]
Keine Kommentare also close
