### ISSUE TITLE
Infernal Blast Furnace Iron -> Steel

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#67]
Der Infernal Blast Furnace kann aus Eisen Stahl machen ohne irgendeine weitere Ingredienz wie Coal, Charcoal oder dergleichen.

So lassen oder ändern?

**Comment by Grambosch** [comment]
Lassen. Die Ingredienz ist Essentia...

**Comment by DerOliDE** [comment]
Sicher? Mal abgesehen von initialen Zeug was ich reinstecke, um die Struktur mit dem Zauberstab in den Ofen zu verwandeln, kann ich das weder dem Rezept für Stahl entnehmen, noch zeigt es mir mein Testaufbau.

Es dauert halt nur lang ( 1 Min pro Ingot ) aber hab hier schon 14 Ingots raus ohne etwas anderes als Eisen in den Ofen geschmissen zu haben und ich habe hier nichts weiter als den Ofen und ne Hungry Chest stehen.

**Comment by Grambosch** [comment]
Ich such mal mein Zauberbuch

**Comment by Grambosch** [comment]
Also. Sowohl der Infernal Furnace als auch der Blast Furnace brennen prinzipiell "umsonst".
Durch die Lavaquelle die eingebaut ist. Das ganze ist zu beschleunigen mit Essentia.
Der Aufwand , wie schon öfter erwähnt , kommt bei Thaumcraft etc vor dem Aufstellen.
Forschung, Forschungspunkte,Vis, Nodes Essentia das alles fällt auch nicht vom Himmel.

Und vergiß nicht : Das ist Forbidden Knowledge. Das gibt nen ganz fiesen Nachteil gegenüber den "Technikern"

**Comment by DerOliDE** [comment]
Okay reicht mir, das Forbidden Knowledge überzeugt mich mehr als alle andere. ;-)
