### ISSUE TITLE
Münzhändler für CustomNPC coins

### ISSUE THREAD

**Issue by hellamie** [combak/ShatteredWorld#68]
ich habe mal gedacht.

Wenn wir einen Händler aufstellen (steht schon mal auf dem Server), kann mann bei ihm die Coins kaufen.
ABER, dafür muss mann erst mal den ruf auf freundlich bei der Münzfraktion bekommen.

Dann kann man bei ihm einkaufen.

Irgendwas = 1 Holzmünze, 64 holzmünzen = 1 Steinmünze etc.

Holz-Stein-Bronze-Eisen-Gold-Diamanten-Emerald ist die Monentane reihenfolge.

Wenn mann sich dann genug Münzen beschafft hat, kann man dan bei anderen Händlern und dem entsprechenden Ruf Items kaufen (zb. Botania Endluftflaschen).

So nun eure Meinungen.

**Comment by DerOliDE** [comment]
Ich glaub ich würde die Münzen auf Bronze, Eisen und Gold beschränken, sonst wird das glaube ich zuviel Kleinkram.

**Comment by Grambosch** [comment]
Dann lass uns Bronze Gold Diamünzen nehmen.

**Comment by krakel** [comment]
Wollte keinen neuen Thread aufmachen. Habe gerade gesehen wie so ein Händler fast von einem Lobber gekillt wurde. Die Eventmobs werden von den CostumNPC angegriffen und umgekehrt. Das sollte beim Platzieren beachtet werden. Oder können die NPC auf Neutral zu allen Mobs eingestellt werden?

**Comment by DerOliDE** [comment]
Die NPCs respawnen nach einer Weile wieder, das wäre kein Beinbruch wenn einer mal umfällt.

**Comment by hellamie** [comment]
https://docs.google.com/document/d/1MS8uH15rpmbWnwSenqy-5nlkTroMEj3cUFyOoFVhjOQ/edit

hier bitte mithelfen
