### ISSUE TITLE
Crash bei der Welterstellung

### ISSUE THREAD

**Issue by jkauven** [combak/ShatteredWorld#69]
Wenn ich versuche eine SP-Welt zu erstellen, dann stürzt der Client ab.

Ähnlich wie hier
https://github.com/Lycanite/LycanitesMobs/issues/79
https://github.com/Lycanite/LycanitesMobs/issues/81

Update von Lycanite auf die Version 1.11.0.0 soll es wohl beheben, Configs werden wohl überschrieben.

**Comment by DerOliDE** [comment]
Eine normale Welt oder eine "Fun World Gen" - Welt?

**Comment by jkauven** [comment]
Bei einer normalen Welt, mit der neuen Version konnte ich die Welt dann starten. Fun World Gen hab ich mit der alten Versioin jetzt gar nicht ausprobiert. Bei der neuen Version klappt sie auf alle Fälle.

**Comment by DerOliDE** [comment]
Okay ist für die Version 0.5.8 vorgesehen.
