### ISSUE TITLE
Vitreous Pickaxe kann nicht zum Glass minen benutzt werden

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#7]
Ist wie jeder andere Axt gesperrt beim Benutzen.

**Comment by combak** [comment]
Ich hab damit noch nicht gearbeitet weiß aber das die Glas wie mit Silk touch abbaut.
Wo liegt die sonst so mining level technisch etc? G.

**Comment by krakel** [comment]
Die ist garnicht mehr benutzbar. Dient nur noch als angeblich Maske, wie ein gesperrtes Tinker Werkzeug.

**Comment by combak** [comment]
Alle Werkzeuge sind per Default erst einmal deaktiviert (crafting only), da ich die Iquana Tweaks von Black- auf Whitelist umgestellt habe. (Oli)

**Comment by DerOliDE** [comment]
Diverse Waffen/Werkzeuge in 0.5.1 freigeben falls noch etwas _wichtiges_ fehlt neuen Issue aufmachen ;-)
