### ISSUE TITLE
Limited Resources durchtesten

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#70]
Mal bitte auf Herz und Nieren checken, ein mir noch bekanntes Problem ist, das man nachdem man ein limitierten Block entfernt hat, ihn nicht wieder an die gleiche Stelle setzen kann, bevor man nicht wo anders den Block bzw ein Block des gleichen Typs platziert hat.

**Comment by Grambosch** [comment]
Thaumic Stone Extruder auf 0 oder 1 setzen. (Die magische alternative zum Igneous)

**Comment by DerOliDE** [comment]
Wie viele Steine schmeißt der so um sich? Ich hätte ja schon noch gern eine Alternative zu Thermal Expansion und selbst wenn beide gebaut sind gibt es noch den Automatic Sieve Flaschenhals.

**Comment by DerOliDE** [comment]
Okay wenn man den nicht noch pimpen kann kommt da wirklich wenig bei rum den setz ich mal auf 1

**Comment by Grambosch** [comment]
Ist ja nur dr vollständigkeit halber und der geht bestimmt mit CentiVis oder so zu beschleunigen

**Comment by Grambosch** [comment]
Vanillaerze  Gold,Iron,Lapis,Diamond,Redstone,Emerald
Forestry Copper TIn
Tinker Aluminum
Thermal Foundation Silver Ferrous Shiny

**Comment by Grambosch** [comment]
Je auf 3 bitte

**Comment by BakermanLP** [comment]
Doofe Frage, wenn zwei Leute auf der gleichen Insel arbeiten, können diese doch doppelt so viele Maschinen aufstellen, oder?

**Comment by Grambosch** [comment]
Sicher

**Comment by Grambosch** [comment]
Thermal Foundation Lead vergessen

**Comment by DerOliDE** [comment]
Es ist Block of Iron statt Iron Ore in den Limited Resources gelandet.

**Comment by DerOliDE** [comment]
In 0.7.0 kommt eine neue Version rein, dort wird es den Block Owner geben und das sollte im Serverbetrieb noch einmal durchgetestet werden.

**Comment by Grambosch** [comment]
https://github.com/combak/ShatteredWorld/issues/191

**Comment by DerOliDE** [comment]
Den Fehler aus https://github.com/combak/ShatteredWorld/issues/191 bekomme ich beim besten willen nicht reproduziert, da ich bis zum nächsten WE generell noch etwas an der Funktionsweise der Mod ändern will, schließe ich den Issue erst einmal.
