### ISSUE TITLE
Das Questbuch

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#71]
So, ich habe mit dem Questbuch angefangen. Die meisten Ideen stammen aktuell von AS2.
https://docs.google.com/document/d/12PDfoBuJ26JLlXf3ic3FeJk1ztzXRyHPdOlZzvys73c/edit
Ist aktelle mehr eine Ideensammlung. Das werden am Ende so viele Quests.

**Comment by krakel** [comment]
Damit ihr euch diese json Daeti auch anschauen könnt, habe ich an einem kleinen Offlineprogramm gearbeitet. Es ist nicht perfekt und auch noch nicht fertig. Ob ich es jemals fertig mache, weiß ich auch nicht. 
http://doerl.de/zip/hqm_convert.zip auspacken und bat oder sh starten.
Man kann json lesen und schreiben, als auch die original hqm's lesen und schreiben.
Damit könnt ihr also auch in die Questbücher andere Pakete schauen.

**Comment by BakermanLP** [comment]
Im aktuellen Questbuch aus dem GitHub stehen eigentlich nur die Questnamen drinnen. Gibt es da was Neueres?
Auf das Google Docs Dokument kann ich nicht zugreifen.

**Comment by krakel** [comment]
Im Questbuch bin ich erst am Anfang. Zu Anfang wollte ich nur ein Tool machen mit dem man ein JSON erstellen kann. Daraus ist dann immer mehr geworden. Den Rücktransport in das hqm Format habe ich auch schon positiv getestet. Dabei sein mir nur Fehler wie ASCII Zeichensatz und Textlängen aufgefallen. Eine Nachbearbeitung im Spiel ist sowieso notwendig, weil die Items und Liquids nur da endgültig korrekt erfasst werden können.

Vorbereitet sind Botania und Blood Magic mit Questfolgen und Task. Bei allen anderen sind nur mögliche Quests vorbereitet. Ich wollte erst einmal die große Richtung festlegen. Der nächste wichtige Schritt sind dann die Belohnungen. Als letzten wollte ich dann die Ausformulierungen machen. 

Für das Google Docs Dokument muß du eine Anforderung an mich senden oder mir deine EMail zusenden. (aber nicht per PM im Forum, da ich diese dort nicht lesen kann, werden weiß überblendet)

Zu den einzelnen Mods habe ich mir Listen aller Items und die Abhängigkeiten darin für eine mögliche Reihenfolge erstellt. Auf dieser Grundlage erarbeite ich mir dann die Questfolgen und Task. Vorbereitet sind schon Draconic, AE2 und Thaumcraft. Ich habe festgestellt, das man nur grobe Kenntnisse der Mods braucht, um das aufzustellen. Bei Ars Magica habe ich noch keinen Plan. Auch für den Anfang, Pam, usw. habe ich noch kein Plan.

**Comment by BakermanLP** [comment]
Dann wühle ich mich später mal durch deine Doku und werde mal anfangen, Questreihen mit Leben zu füllen. Du schaust dir danach an, ob das so passt und dann gehts weiter.

**Comment by krakel** [comment]
Wenn ihr mein Programm zum Anschauen benutzt, bitte immer mal eine aktuelle Version herunterladen. Ich merze da hin und wieder ein paar Fehler aus!

**Comment by krakel** [comment]
So, habe jetzt alles in mein Programm integriert. Kann alles offline machen außer Dinge die ein nbt brauchen. Hoffe das keine Bugs drin sind. :)

**Comment by krakel** [comment]
Ich habe jetzt für alle von mir geplanten Questfolgen entspechende Zusammenstellungen fertig. Diese sind aber an vielen Stellen noch diskussionswürdig und auch unvollständig. Hier bitte ich um konstruktive Kritik.
Als nächstes werde ich an den Texten arbeiten. Es werden sowohl Questbeschreibung als auch kleine Taskbeschreibung gebraucht. Ihr könnt da aktiv mitarbeiten, entweder über das online Office Dokument oder direkt in das JSON. Parallel dazu werde ich die Questabhängigkeiten und Blockerquest weiter aktualisieren. Als letztes will ich die Belohnungen und Optionen bearbeiten.
Wir können uns auch hin und wieder mal online zusammen setzen und die Elemente direkt besprechen.
Unzufrieden bin ich aktuell mit:
- Botania und Forestry sind recht mikrig und sollten wohl zusammen gelegt werden
- Buildcraft und Thermal Expansion fehlen mir noch Ideen
- die zusätzlichen Mods zu Thaumcraft kenne ich nicht und habe sie deshalb außen vor gelassen
- wenn wir kein Ocean Biom im Zugriff haben müssen alle Mobquests dazu entferrnt werden
- brauchen wir Ruf im Questbuch, damit lassen sich Sichtbarkeiten steuern
- sind in Ars Magica alle Mobs erreichbar, gleich der erste braucht wohl auch ein Ocean Biom (oder mind. See)
- ist überhaupt soviel Draconium vernüftig machbar für alle Quests dazu
- ist das alles zu viel oder zu wenig

**Comment by krakel** [comment]
Aktuell kann das Questbuch nicht geöffnet werden, weil man keine Erlaubnis hat das /hqm Kommando auszuführen.

**Comment by krakel** [comment]
Ich habe eine aktuelle Version meines Editors erstellt (immer unter http://doerl.de/zip/hqm_convert.zip). Jetzt werden die Texte separat gespeichert. Dadurch lassen sie sich leichter überarbeiten. Außerdem könnten auch andere Sprachversionen erstellt werden (falls wir mal international werden wollen). Auch wenn das Questbuch noch keine lokalisierten Versionen anbietet, könnte man einem Admin eine Auswahl für seinen Server bieten.

Des weiteren habe ich ein anderes Questbuch gefunden, das die korrekten Namen für alle Bosse und Mobs enthält. Damit konnte ich unser Questbuch aufbessern. Jetzt sind alle Bosse aus Ars Magica 2 und alle Mobs aus Lycanite richtig drin. Bei Lycanite gibt es noch ein prinzipielles Problem, ich konnte noch kein Wassermob überreden in der Sky Dimension zu erscheinen. Die müssen wohl aus der Killliste rausgenommen werden.

**Comment by krakel** [comment]
Ich habe mal mit den Questbelohnungen angefangen. Das ist schwerer als die Questfolgen selbst.
Versuche eine Tabelle dazu immer aktuell zu halten.
https://docs.google.com/spreadsheets/d/1Upnu9bAzmJvH0WyOtuoHj33_Ve-qpN9b1SYD58t9U-k/edit#gid=0

**Comment by krakel** [comment]
Folge Veränderungen im Questbuch:
1. Einleitungstext reduziert, keine Serverinfos mehr
2. Startquests - Man muß am Anfang nur Sticks sammel und bekommt dadurch Flint und Torches. Damit kann man ohne Sorge weiter arbeiten. Der Tinkerquest wurde auf die Toolstation reduziert, da die anderen Teile Materialabhängig sind.
3. Neuer Questfolge "Das Endspiel" - Geplant sind 3 Bosse (Drache, Krieger, Wissenschaftler). Die werden in der Welt plaziert und können sich kaum bewegen, sind aber immer aktiv und sehr stark. Diese bewachen jeweils Händler, die dadurch nicht angesprochen werden können. Wenn man im Questbuch wichtige Sammelquest erfüllt werden die Zielkoordinaten der Bosse freigeschalten. Um an die Händler heran zu kommen, muß man die Bosse besiegen (Eventkämpfe). Danach kann man die Location für die Sammelquests erfüllen. Man bekommt im Questbuch ein Questitem, das man bei den Händlern für Loot eintauschen kann. Nach einiger Zeit respawnen die Bosse. Man kann diese immer wieder bekämpfen, auch wenn man die Questfolgen noch nicht fertig hat. Nur die, die das haben, können auch den Loot bekommen.
Drache: 20 von 22 Lycanitequests beendet
Krieger: 15 von ca. 18 Rüstungssätze gebaut (fast alle Rüstungssets sind enthalten)
Wissenschafler: 12 von ca. 15 Questfolgen beendet (schwere Endpunkte erreicht)

**Comment by krakel** [comment]
Folgende Rüstungen sind aktuell im Questbuch:
- Vanilla: Iron, Diamond
- TConstruct: Wood, Travel
- Harvestcraft: HardenedLeather
- Forestry: Apiarist
- EnderIO: DarkSteel
- Redstone Arsenal: Flux
- ArsMagica: Mage, BattleMage
- Thaumcraft: Thaumium, Thaumaturge, Fortress, Primordial, Void, Void Fortess, Crimson Cult, Crimson Cult Robe, Crimson Praetor
- Botania: Manasteel, Terrasteel, Elementium
- Blood Magic: Bounded, Sanguine
- Draconic Evolution: Wyvern, Draconic

Eventuell sind das etwas zu viel. Besonders Thaumcraft schlägt ganz schön rein. Was haltet ihr davon?

**Comment by Grambosch** [comment]
Crimson sind glaub ich Drops von den Kultisten. So weit ich weiß nicht baubar(Kann mich aber auch vertun)

**Comment by krakel** [comment]
Das ist richtig. Aber sie können gefarmt und benutzt werden. Deshalb hatte ich sie aufgenommen.

**Comment by krakel** [comment]
Ich merke gerade, das ich es wohl ein klein wenig übertieben habe. Bei den Rüstungen ist aktuell auch die Primordial aus Witching Gadgets mit dabei. Nach genauem Studium des Rezeptes fiel mir auf, das man dafür insgesamt 12 Primordial Pears braucht, also 12 mal die Endbosse von Thaumcraft in den Outher Lands. 
Ups

**Comment by Nedelosk** [comment]
Naja so viel ist das jetzt auch nicht.

**Comment by hellamie** [comment]
GRAYAL????  wie mache ich den Holzkohle? ..bitte sei so lieb und nimm (die doch große veränderung) ins Questbuch auf.

**Comment by krakel** [comment]
@hellamie 
Ja, das ist @Nedelosk 's Werk :) . 
Das ist im Quest "Der rauchende Berg" beschrieben. Die aktuelle Version des Questbuchs enthält das noch nicht. Du nimmst 18 Stück Holz und baust ein 3x3x2 Stapel daraus. Dann zündest du den oberen mittleren mit einem Feuerzeug (Flint and Steel) an. Der Stapel ändert seine Optik. Nach ca. 1 min oder so, ist der Prozess abgeschlossen und du siehst einen Dreckhaufen. Diesen kannst du abbauen und siehe da: 18 Stück Holzkohle.

**Comment by krakel** [comment]
Habe jetzt eine Version 1.0 des Questbuches fertig. Schaut euch bitte die Quest, Texte und Belohnungen an. Bin für Hinweise zu Fehlern oder Verbesserungen dankbar. Werde in den nächsten Tagen noch einige Statistiken nachreichen. Noch nicht fertig sind die Endbosse.

**Comment by DerOliDE** [comment]
Werde das heute oder morgen mit der 0.7.2 raus hauen.

Am 08.11.2015 um 14:26 schrieb Uwe Dörl:

**Comment by krakel** [comment]
Denke bitte auch daran den Ordner HardcoreQuesting im World Verzeichnis zu löschen.

**Comment by krakel** [comment]
So ich habe mal einen ersten Entwurf für die Endbosse gemacht. Mein Designverständnis ist nicht sehr berauschend.
Drache: -890,50,64
![2015-11-11_10 25 38](https://cloud.githubusercontent.com/assets/4434299/11087969/ef9bc914-885e-11e5-9fe8-ef9fc52e2c34.jpg)
Krieger: 590,-570,64
![2015-11-11_09 57 34](https://cloud.githubusercontent.com/assets/4434299/11087973/f5c2b9b0-885e-11e5-8a52-302903c27235.jpg)
Wissenschaftler: 560,480,64
![2015-11-11_09 25 55](https://cloud.githubusercontent.com/assets/4434299/11087979/fb737c5a-885e-11e5-84e4-fe7792c261ad.jpg)

**Comment by Nedelosk** [comment]
Ich habe mal etwas mit deinem wunderschönen Tool rum gespielt. Ich glaube ich brauche dann irgend wann mal deine Hilfe.

**Comment by krakel** [comment]
Habe mein Tool der neuen HQM Version angepasst (HQM-The Journey-4.4.4).
http://doerl.de/zip/hqm_convert-1.0.100.zip
Hat jetzt auch ein Versionsmanagement.

**Comment by krakel** [comment]
Habe meinem Programm ein paar Reports hinzu gefügt. Damit kann man sich alle Items, die benutzt werden auflisten. So als Summenfunktion. Leider kann ich nicht auf die lokalisierten Namen zugreifen. Aber für einen Überblick reicht es.
Neue Version http://doerl.de/zip/hqm_convert-1.0.102.zip

**Comment by krakel** [comment]
Habe jetzt die Endbosse fertig. Alle haben 10000 HP. Mit guter Draconic Rüstung kann man die allein machen. Hauen gut zu. Sie haben kein Loot. Der Drop kommt aus dem Questbuch, wodurch jeder nur einmal den Loot abfassen kann. Dieser Loot kann beim Schatzmeister eingetauscht werden.

| Boss | Loot | Pos |
| --- | --- | --- |
| Drache | 8x Infinty Ingot | -688,83,177 |
| Krieger | 8x Awakened Draconium Block | 591,57,-496 |
| Wissenschaftler | Dice of Fate | 382,62,496 |
| Schatzmeister | --- | -12,74,8 im Turm |

**Comment by DerOliDE** [comment]
Questbuch kaputt! fixen! ^^

**Comment by krakel** [comment]
Olli wars.

**Comment by DerOliDE** [comment]
Das hat Dir der Teufel gesagt!

**Comment by hellamie** [comment]
SO. Ich spiele brav Appel Milk an Tea durch...ABER

1) der Braumeister geht nicht. Der erkennt den Eimer Whisky nicht an. Nimm da lieber das Vorprodukt Ale Yeast.
2)Schnapsdrossel. Flasche Whisky abgefüllt..nicht erkannt. MÖÖÖP Und den Apfel Likör kann ich nicht bauen...AHAHAHAHAHAHAh
3) habe ich noch nicht gefunden

**Comment by hellamie** [comment]
3) ich kann die Ladestation nicht abgeben..

**Comment by hellamie** [comment]
3) 10 Flaschen Öl bei der Quest Ladestation heist 10 Plätze im Inventar frei haben. ist bisschen bläd

**Comment by DerOliDE** [comment]
Wurde als fertiggestellt gemeldet, darum close.
