### ISSUE TITLE
Addons zu Storage Drawers

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#72]
Hab eben gesehen das es dazu Addons gibt für Forestry und Natura. Also mehr "Skins" für die Drawer
Enbauen oder nicht?

**Comment by krakel** [comment]
Ich wäre dafür.

**Comment by DerOliDE** [comment]
Solang uns die Modanzahl nicht um die Ohren fliegt solls mir recht sein _g_

**Comment by DerOliDE** [comment]
Für die nächste Version hinzugefügt.
