### ISSUE TITLE
Manakekse hebeln Spice of Life aus

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#74]
Manakekse haben den Effekt Saturation. Die geben erst mal laut Tooltip keine Hungerkeulen füllen aber also Zeiteffekt in nullkommanix die komplette Hungerleiste inkl. der Sättigungsleiste auf.
Meiner Meinung nach müssen die raus

**Comment by DerOliDE** [comment]
Rezept deaktiviert
