### ISSUE TITLE
Ex-Astris bekommt nur noch Bugfixes, es wird auf ein neues Projekt verwiesen

### ISSUE THREAD

**Issue by jkauven** [combak/ShatteredWorld#75]
Falls ihr es noch nciht gesehen habt.

In den Changelogs steht, dass dieses Projekt nur noch Bugfixes bekommt und man sich Ex-Astris-Rebirt anschauen soll. Hier die Links zu den Changelogs und dem neuen Projekt.

http://minecraft.curseforge.com/mc-mods/226340-ex-astris/files/2239780

https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth

**Comment by DerOliDE** [comment]
Schaue ich mir die Tage mal an.

**Comment by DerOliDE** [comment]
Ich bekomme noch ein Crash beim starten, sobald das behoben wurde wandert es in die nächste Version.

**Comment by DerOliDE** [comment]
Issue gemeldet: https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth/issues/40

**Comment by DerOliDE** [comment]
Ich war zu blind um Ex Nihilo zu updaten :-S Jetzt läuft es und es wird in die 0.5.9 wandern.
