### ISSUE TITLE
Netherportal

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#78]
Wie ist das eigentlich mit dem Netherportal. Da alle in Ihrer Welt an ca. der gleichen Koordinate sind, werden alle Netherportale zur gleichen Zielkoordinate im Nether führen. Der Rückweg wird dann immer zum ersten erfolgen. Kann man das Portal verhindern, so das nur eines am Spawn steht, oder gibt es eine andere Möglichkeit?

**Comment by DerOliDE** [comment]
Zur Zeit haben wir ja erst noch das Problem das wir via MultiWorld Modul von ForgeEssentials keine Fun World Gen nicht die gewünschten Welten erstellen können, da es keine generator-settings gibt.

Man könnte den Nether deaktivieren und einen eigenen erstellen in den man sich nur über den Spawn teleportieren kann, da könnte man dann auch verschiedene Einstiegspunkte anbieten.

**Comment by BakermanLP** [comment]
Mach einen Update von forgeessentials auf beta7, dann geht das mit den generator-settings.

/mw list worlds
/mw list worldtypes
/mw list providers
/mw create myFunnyWorld normal FWG

**Comment by DerOliDE** [comment]
Siehe Forum habe Dir dazu schon geantwortet ;-)

Am 10.06.2015 um 11:20 schrieb BakermanLP:

**Comment by BakermanLP** [comment]
Nun habe ich dann folgendes gemacht:
ForgeEssentials/ForgeEssentialsMain#1576

**Comment by DerOliDE** [comment]
Ja daran habe ich auch schon gedacht im Code scheinen die Settings zu mindestens für die Flatworld schon als TODO vermerkt worden zu sein.

https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/multiworld/gen/WorldTypeMultiworld.java#L44

Aber das scheint auch schon solange da drin zu stehen wie die Datei existiert.

**Comment by DerOliDE** [comment]
Immerhin schon auf die Feature TODO Liste gewandert. :)

**Comment by DerOliDE** [comment]
Die Thematik sollte gegessen sein.

In den YADM Dimensionen kann man kein Netherportal setzen, in der Overworld wird man keine Portale setzen können und der Nether wird eine YADM Dimension die via Quest NPCs betretbar sein wird.
