### ISSUE TITLE
Integration in AgriCraft und Ex-Nihilo

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#8]
Man sollte noch einmal über die Integration nachdenken. Ars Magica könnte auch integriert werden.
Anderer seits ist es schon spannend etwas rumfliegen zu müssen.

**Comment by Grambosch** [comment]
Die bisher gesehene Menge an AM2 Blumen macht mich nicht gerade optimistisch. Ergo machen wir Saat und Blumenrezepte dafür

**Comment by Grambosch** [comment]
Sonst noch irgendwelche Pflanzen?

**Comment by DerOliDE** [comment]
Da sich hier nichts mehr getan hat vorerst geschlossen.
