### ISSUE TITLE
[TConstruct] Molten Redstone/Destabilized Redstone

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#81]
Aus Redstone in der Schmelze soll ausschließlich Destabilized Redstone werden.

**Comment by BakermanLP** [comment]
Kopiere die Einstellungen aus dem Phoenix github. Da ist es so eingestellt.

Oliver notifications@github.com schrieb am Fr., 12. Juni 2015 17:56:

**Comment by DerOliDE** [comment]
Da war ich schon schneller mit dem tippen. :D
