### ISSUE TITLE
Natura Flour im Crafting Grid herstellbar -> deaktivieren

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#82]

**Comment by Grambosch** [comment]
hab angefangen unter anderem auch 3 Barley> 1 Brot muss raus aber "not supported yet" ...

**Comment by Grambosch** [comment]
Umgangen durch alle Brotrezepte deaktivieren in Vanilla zs. jetzt an die BAckrezepte das das nur mit Pamteig geht

**Comment by krakel** [comment]
Es gibt auch ein Rezept in AE2 um Flour herzustellen, aus dem man auch Brot machen kann.

**Comment by Grambosch** [comment]
Joa das ist komplizierter als gedacht. Ich hab alles raus ohne Backen und ich hab alle Backrezepte aus dem Vanillafurnace. Und dann kam TE...da gehts dann nicht weiter

**Comment by DerOliDE** [comment]
Müssen wir TE rausschmeißen O:-)

**Comment by DerOliDE** [comment]
So ich habe jetzt erst einmal soweit wie möglich die Änderungen übernommen, was noch zu machen ist, sobald TE es zulässt:
- Pulverizer Wheat (Vanilla) zu Flour (AppEng2)
- Redstone Furnace Flour (Natura&AE2) zu Bread

**Comment by DerOliDE** [comment]
Damit sollten nun alle Flour Sorten außer Pams beseitigt sein.
