### ISSUE TITLE
Ruf-Farm-Fraktion gedöns

### ISSUE THREAD

**Issue by hellamie** [combak/ShatteredWorld#83]
https://docs.google.com/document/d/1MS8uH15rpmbWnwSenqy-5nlkTroMEj3cUFyOoFVhjOQ/edit?usp=sharing

Hier mal meine Notizen über die Elfen/Botania Etc..

**Comment by DerOliDE** [comment]
Ich störe mich etwas an der statischen Aufteilung nach Fraktion=>Mods, ich würde das ganze andersrum aufsetzen z.B. ich habe eine Fraktion Kult des Stachels die nutzt Magie und betet böse Bienen an (Bloodmagic & fiese/stechende Nether Bienen). 

Man muss glaube ich auch nicht alle Aspekte einer Mod in eine Fraktion abbilden bspw. bietet ja Thaumcraft über das Spektrum hinweg Dinge die man als gute, neutrale oder böse Magie einstufen kann.

/edit
Die Elfen könnten bspw. zusätzlich zu Botania noch Agricraft und Thaumcraft (Alchemie/Schutzzauber?) verwenden.

**Comment by DerOliDE** [comment]
Wenn die NPCs im Cloner gespeichert werden und das sollten sie Sicherheitshalber, dann bitte Tabs zum sortieren der Fraktionen nutzen siehe: https://github.com/combak/ShatteredWorld/wiki/dev:-Custom-NPCs

**Comment by hellamie** [comment]
Alle letztPlayer in der Welt verteilt und gespeichert...darfst sie aber auch gerne wieder löschen wenn es doof ist.

Habe eine Begrüßung und "kleine" Questreihe mit dem Letzplayern gemacht. bzw angefangen. Bitte testen und ggf Rechtschreibfehler (regeln) Ändern.
