### ISSUE TITLE
World Reset für Betatest mit neuer Version

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#84]
Welt vom Server (Stand 14.06. 11:00) ist untergeladen 
Server soweit bereit zum Reset und Survival Test mit neuer Version

**Comment by DerOliDE** [comment]
Jetzt hängt alles nur noch an Larson _druckmach_ ;-) 

Genießt das schöne Wetter heute, das haben wir uns verdient.

**Comment by DerOliDE** [comment]
Neue Version und der damit verbundene Server Reset wird morgen umgesetzt.

**Comment by DerOliDE** [comment]
Kommt gleich -> closed
