### ISSUE TITLE
Verstärkung fürs Team suchen?

### ISSUE THREAD

**Issue by Grambosch** [combak/ShatteredWorld#85]
So wie es ausschaut kämpfen wir zZ an vielen Fronten und cieles ist noch nicht mal angefasst an Quests/Fraktionen/Texturen etc.,
Sollen wir im offiziellen Teil des Forums mal nach Verstärkung suchen?

**Comment by DerOliDE** [comment]
Vielleicht sollten wir mal strukturieren was noch alles zu machen ist und uns dann Milestones einrichten und das dann systematisch von Version zu Version angehen, ich glaub nicht mehr das es soviel arbeit ist gemessen an der Zeit bis Herbst/Winter, wenn wir mal systematisch die Baustellen abarbeiten.

Die großen Baustellen sind doch jetzt eigentlich nur noch:
- Welt designen ( Lobby + Questwelt/Overworld )
- NPC/Fraktionen designen
- Quests/Dialoge
- Questbuch

Daneben gibt es noch das restliche Balancing und ggf. Probleme die beim testen noch auftreten.

Können wir später ( gegen 17 Uhr?) mal im Teamspeak besprechen und schauen was es wirklich noch zu tun gibt, wer was macht und welche Aufgaben noch an neue Leute dirigiert werden können.

**Comment by BakermanLP** [comment]
Ab Mitte dieser Woche werde ich mich auch mehr einbringen und mal testen
und fixen. Die Issues kann man auf Github ja zuweisen, somit sollte es
Übersichtlichkeit bleiben. Das Questbuch ist leider blöd zu pflegen.
Vielleicht können wir da Texte generieren, damit der Editor die nur Copy
und Pasten muss.

Oliver notifications@github.com schrieb am Mo., 15. Juni 2015 15:12:

**Comment by DerOliDE** [comment]
Für das Questbuch hat Grayal ein nettes Tool geschrieben mit dem man die Textinhalte im JSON Format ex- und importieren kann.

see: https://github.com/combak/ShatteredWorld/blob/master/config/hqm/ShatteredWorld.json

Damit könnten zu mindestens an den Texten mehre Arbeiten und am Ende muss einer das Ganze wieder ins Binärformat exportieren und im Spiel Icons hinzufügen.

**Comment by krakel** [comment]
Bitte hängt diese Programm nicht an die große Glocke. Ich habe noch nicht nach einer Berechtigung bei den Machern von HQM gefragt. Auch ist es noch nicht ganz fertig (immer mal neu laden, da ich fast jeden Tag was verbessere).
Aber man kann die hqm's lesen und schreiben und sie in ein json Format konvertieren. Einen ersten Eindruck sieht man in den Sourcen hier im config/hqm Ordner. 
Wenn ihr bestimmte Daten von NEI exportiert, kann man darauf zugreifen und sogar fast alle Icons sehen. Im Prinzip ist fast alles möglich außer den NBT Informationen, die müssen direkt aus dem Spiel entnommen werden.

**Comment by BakermanLP** [comment]
Ich habe jetzt mal ein paar Texte für das erste Kapitel geschrieben. Bitte drüber schauen, ob das stilistisch und inhaltlich in etwa euren Vorstellungen entspricht. Stellt sich mir nur die Frage, wo und wie ich das abstellen soll.

**Comment by BakermanLP** [comment]
Habe die Texte mal hier als Teil des Pull Requests abgestellt:
https://github.com/BakermanLP/ShatteredWorld/commit/cdcc70618709b8b6b62bc3ca0bd89efb53be1a41

**Comment by DerOliDE** [comment]
Ich mach das Thema mal dicht, sollte sich erledigt haben.
