### ISSUE TITLE
Testserver Version 0.6.0

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#89]
So dann will ich mal hier weiter machen.
Das Problem mit den Items beim ersten Login ist wohl keins. Das scheint wohl Standard von Minecraft zu sein.
Ansonsten weiß ich auch nicht weiter.

**Comment by DerOliDE** [comment]
Ich werde später einfach mal 0.5.8 wieder einspielen und einzeln jede neue Mod dazu nehmen.

**Comment by krakel** [comment]
Ich habe mir mal eine Version mit Forge 1408 gebastelt. Darin sind nur hqm, open blocks und tconstruct. Jetzt bleibt nur noch ein Bug beim Öffnen des Inventars, aber auch nur im SMP.

```
java.lang.NullPointerException: Unexpected error
    at tconstruct.client.tabs.InventoryTabKnapsack.shouldAddToList(InventoryTabKnapsack.java:23)
    at tconstruct.client.tabs.TabRegistry.updateTabValues(TabRegistry.java:64)
    at tconstruct.client.tabs.TabRegistry.guiPostInit(TabRegistry.java:43)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_67_TabRegistry_guiPostInit_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:257)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1895)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by krakel** [comment]
habe dazu ein Issue bei denen aufgemacht
https://github.com/SlimeKnights/TinkersConstruct/issues/1657

**Comment by krakel** [comment]
Es sieht übrigens auch gerade danach aus das NEIIntegration-MC1.7.10-1.0.9 genauso geschrieben werden muß. Erst nachdem ich das gemacht hatte, schrie NEI nach weiteren abhängigen Libs. Nicht das neiaddons-mc1710-1.12.9.32 genau nach diesem Namen sucht.

**Comment by BakermanLP** [comment]
Ich vermutete auch solche Geschichten und habe deswegen die Namen der Mods gleich belassen, auch in dem Skript. Sollte zwar nicht notwendig sein, aber hier sind eben zum Teil Hobbyprogrammierer am Werk

**Comment by BakermanLP** [comment]
Es hat irgendwas mit den Custom Items / Fluids zu tun. Was ich getan habe
1. forge auf 1448
1.5 Forgeessentials erst mal vom Server entfernt
2. Alle Vorkommen von frTerrasteel, frManasteel und frElementium auskommentiert in der Datei scripts/TinkersConstruct.zs
3. Die Datei config/customitems/botania-fluids.json verschoben / gelöscht

Bei jedem Durchlauf hatten sich die Fehlermeldungen etwas geändert. 

Am Schluss habe ich alle Scripts und alle CustomItem configs wegverschoben, dann geht es.

Im Moment füge ich die Scripts wieder langsam ein.

**Comment by DerOliDE** [comment]
Wenn eine Mod mit einer Umbenennung nicht klar kommt gehört die raus geworfen sorry aber das ist ganz großer Pfusch.

**Comment by BakermanLP** [comment]
Nun habe ich alle Scripts außer den folgenden wieder eingebunden:
- EnderIO.zs  
- ThermalExpansion.zs  
- TinkersConstruct.zs

Diese habe ich draussen gelassen, da hier die Fluids aus dem Mod CustomItems verwendet werden. Login funktioniert bei mir.

Die CustomItem Configs sind auch noch draussen.

**Comment by krakel** [comment]
@DerOli82 
Die Namen der Mods gehören dir nicht. Auch wenn dir das jetzt stinkt, damit mußt du leben.

@BakermanLP 
Kannst du das Inventar öffnen?

**Comment by BakermanLP** [comment]
Eventuell ... in der richtigen Mondphase usw ... liegt es an CustomItems. Der Mod wurde mit der Forge Version 1272 kompiliert. Da war das Liquid / Fluid System noch nicht überarbeitet. Leider ist im Github seit Februar nichts mehr bei denen passiert. 

@krakel 
![inventar](https://cloud.githubusercontent.com/assets/3873443/8207677/60789ed4-1503-11e5-86ac-276cf8bd68bd.jpg)

**Comment by DerOliDE** [comment]
@krakel Ne sorry da habe ich kein Verständnis, ich möchte da etwas System in die Modbenennung bringen damit es für mich übersichtlicher/einheitlicher wird. Bei so vielen Mods verliert man auch so schon schnell den Überblick.

**Comment by krakel** [comment]
Im Singleplayer geht das mit dem Inventar öffnen immer. Das Problem tritt nur bei Server - Client auf und auch nur wenn die auf verschiedenen Maschinen sind.

**Comment by krakel** [comment]
Bei einzelnen Mods wird das sicher keine Problem sein. Aber bei Librayries oder Sammelmods wie NEI kann das Probleme bringen. (neues Bier holen, schnell austrinken, dann wird das besser)

**Comment by DerOliDE** [comment]
CustomItems ist Open Source zur Not versuche ich es mal mit einer neueren Forge Version zu kompilieren bzw dann die Fehler auszubügeln.

**Comment by Grambosch** [comment]
Blöder Gedanke. DIe gennanten Fluids haben in dem Update eine Textur bekommen. Kann das irgendwo daran hängen Einfach mal ohne Texturen aufspielen oder so

**Comment by DerOliDE** [comment]
Die Texturen gibt es nur clientseitig, die werden ja quasi wie ein resourcepack zur Verfügung gestellt

**Comment by Grambosch** [comment]
War ja nur ein Gedanke..nicht hauen

**Comment by BakermanLP** [comment]
@krakel Ich habe das Inventar auf dem Server geöffnet und diese beiden Instanzen sind auf unterschiedlichen Maschinen.

**Comment by DerOliDE** [comment]
CustomItems auf Server und Client disabled, sowie die Custom Fluids aus dem Tinkers Script entfernt und das Problem ist behoben.

Ich werde jetzt die 0.6.1 ohne CustomItems machen, mir die Mod dann mal forken und dann in die nächste Version hoffentlich wieder reinpacken.

**Comment by BakermanLP** [comment]
Eventuell einen forge update, da dort sich noch ein paar Sachen geändert
haben ( z.B. Fehlermeldungen verbessert )

Oliver notifications@github.com schrieb am Mi., 17. Juni 2015 17:31:

**Comment by DerOliDE** [comment]
@BakermanLP Ich werde CustomItems mit einer aktuellen Forge Version kompilieren, ich denke dort gibt es Probleme mit dem neuen FluidRegistry-Geraffel.

**Comment by DerOliDE** [comment]
P.S.: Aktuellere Forge Version kommt dann in die 0.6.2 rein, ich wollte erst einmal den Fehler "raus schneiden" ohne größere Änderungen.

**Comment by DerOliDE** [comment]
Die FluidRegistry aus CustomItems kann es nicht allein sein, ich habe um die Registrierung eine if FluidRegistry.isFluidRegistered Abfrage gebastelt, es auf Forge 1448 kompiliert und bekomme noch immer den selben Fehler.

**Comment by BakermanLP** [comment]
Es ist nicht nur das neu kompilieren mit der neuen Forge Version. Da muss, so weit ich das weiß, auch im Mod einiges geändert werden. Aber Programmierung ist nicht mein Ding, zumindest nicht Java.

**Comment by DerOliDE** [comment]
Steht doch da was ich geändert habe :)

Beim verbinden zum Server schmiert der Client mit sowas hier ab:
[13:30:11] [Client thread/DEBUG] [FML/]: The fluid customitems:molten_manasteel has been selected as the default fluid for molten_manasteel
......
[13:30:11] [Client thread/ERROR] [FML/]: FluidIdRegistryMessageHandler exception
java.lang.IllegalArgumentException: value already present: molten_manasteel
....

Die "if FluidRegistry.isFluidRegistered" Abfrage sollte eigentlich verhindern das irgendetwas doppelt registriert wird.

**Comment by BakermanLP** [comment]
Da solltest du mal @GregoriusT oder @Drummer fragen. Die Beiden fallen mir da am ehesten ein, die mit Flüssigkeiten schon gearbeitet haben. Eventuell haben die einen Tipp

**Comment by DerOliDE** [comment]
Wenn ich die Custom Fluids aus dem Ordner entferne schnappt der sich die nächst bessere Flüssigkeit aus irgendeiner anderen Mod und wirft den selben Fehler.

Ich werde später einfach mal den Fluid-Part aus der Mod raus ziehen und allein kompilieren.

/edit Ersetzt später durch am Wochenende. ^^

**Comment by GregoriusT** [comment]
Sieht aus als würden zwei verschiedene Mods einen platzierbaren Fluid
BLOCK zum selben Fluid hinzufügen wodurch es zur Exception kommt, da
es nur einen Fluid Block pro Fluid geben kann.

Und wenn dann einer der Mods or gar beide Mods nicht vorher überprüfen
ob da schon ein Fluid Block am Fluid hängt crasht es.

Aber es kann auch schlimmer kommen. Wenn es einen Mod gibt der
automatisch Fluid Blöcke hinzufügt aber es mehr als 3 bis 4 tausend
Fluids im register gibt, dann gehen euch die Block IDs aus und es
kommt dadurch zum Crash, weil es nur 4096 Block IDs gibt die, auch
wenn mann sich nicht mehr in den Configs darum kümmern muss, immernoch
existieren.

**Comment by DerOliDE** [comment]
Hier ist der Part wo die Custom Fluids registriert werden: http://pastebin.com/Py0n2rUE

Ich habe da nur noch das if-else Konstrukt drum gestrickt, um zu prüfen ob ein Fluid schon registriert wurde.

**Comment by DerOliDE** [comment]
Quick n' Dirty den Fluid Part in eine Mod ausgelagert http://pastebin.com/N7e0PDTe und das Ganze funktioniert.

**Comment by DerOliDE** [comment]
So im TS beschlossen, wir machen es uns leicht und benutzen den ausgelagerten Fluid Part und ich bau morgen noch eine Config darum. CustomItems wird ja scheinbar nicht mehr gepflegt.

**Comment by DerOliDE** [comment]
Vorerst beseitigt aber noch nicht völlig gelöst.
