### ISSUE TITLE
AE2 wie soll man an die Inscriber Schablonen kommen

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#9]
Vielleicht irgend welche Rezepte oder als Loot aus den Dungeonkisten.

**Comment by combak** [comment]
Steht schon in Google Docs, da ist ein Rezept geplant über die Materialkosten dafür lässt sich das ganze Autocrafting dann auch ins Late Game verschieben, wenn man anfangs nur den Logic Processor zulässt. Ich hätte am liebsten ein Rezept mit dem Buildcraft Laser aber mangels Buildcraft leider noch nicht möglich. (Oli)

**Comment by krakel** [comment]
Nur der Logic Processor wird nicht gehen, da einige einfache Sachen auch den Calculation Processor brauchen. Wenn ihr nur das Autocrafting erschweren wollt, braucht eigentlich nur der Molecular Assembler modifiziert werden.

P.S. Wir sollten nur hier diskutieren. Da lassen sich Themen viel leichter verfolgen und auch rückwirkend analysieren.

**Comment by combak** [comment]
Nur den Logic Prozessor zu verwenden limitiert anfangs die Möglichkeiten des AE Netzes auf:
- 1k Storage Cells
- ME Chest anstatt Drive
- Interface, Storage, Import und Export Bus
- Energy Acceptor und damit kleine 8 Kanal Netze
- ME Terminal (ohne crafting)

Damit lassen sich kleine Arbeitsabläufe automatisieren aber die Möglichkeiten bleiben noch eingeschränkt. Für was bräuchte man denn zwingend den Calculation Processor und ist das so notwendig das man es zwingend vor dem mid bis late game benötigt? (Oli)

**Comment by krakel** [comment]
Mit dem Calculation Processor kann man:
- 4k Storage Cells (warum nicht)
- Basic + Advanced Cards (import und export regeln)
- Cell Workbench
- Network Tool (den Energieverbrauch messen)
- ME Crafting Terminal (crafting mit Hand)
- ME Level Emitter

**Comment by combak** [comment]
Sehe da noch immer nicht das Problem den Calulation Processor aus dem early bis mid game fern zu halten. Ich möchte das einfach etwas staffeln, sodass der Logic Processor relativ früh verfügbar ist, der Calculation meinetwegen schon im mid game und der Engeeniering erst im late game. (Oli)

**Comment by krakel** [comment]
Na damit kann ich leben. Jetzt muß nur noch geklärt werden was mid game heißt. :)

**Comment by combak** [comment]
Minimal Hürde soll der Buildcraft Laser sein, sofern damit auch Custom Rezepte möglich sind und dann muss man halt mal schauen wie hoch man welche Hürde legt. (Oli)

**Comment by DerOliDE** [comment]
In 0.5.2 via BC Laser craftbar.
