### ISSUE TITLE
Ore Generation und cofh / thermalfoundation

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#90]
Cross ref: CoFH/Feedback#612

**Comment by BakermanLP** [comment]
Neue Cross Ref: Ted80-Minecraft-Mods/Fun-World-Gen#4

**Comment by BakermanLP** [comment]
So, hier mal was neues, was nicht so richtig in Github reinpasst.

Die Erze, die in der Overworld (Skyland) erzeugt werden kommen aus FWG. Hier ist das Thema, dass er für die unterschiedlichen Welt Typen unterschiedliche Ore Generations einsetzt ( https://github.com/Ted80-Minecraft-Mods/Fun-World-Gen/tree/5b19af1f448a7439a05334cfe3c2ceb84f9229af/fwg/generator ). Bei SkyIsland greift der Eintrag von CoFH leider nicht.

Ich sehe hier 3 Möglichkeiten eventuell sogar 4
1. Ich habe einen Issue aufgemacht ( https://github.com/Ted80-Minecraft-Mods/Fun-World-Gen/issues/4 ) und eventuell kommt da was
2. Selber compilieren und die komplette OreGeneration aus dem Source Code rauswerfen
3. Selber compilieren und die OreGeneration umstellen, damit die CoFH Einstellungen greifen (Wäre für OpenSource die schönste Lösung, aber die aufwendigste)
4. Mod einbauen, der generierte Erze wieder ersetzt (Wäre meiner Meinung nach die schlechteste).

**Comment by DerOliDE** [comment]
2+3) Wird ein Problem, da zu mindestens auf den ersten Block keine Lizenz hinterlegt ist die das erlaubt.

Ich persönlich habe auch kein Problem wenn ein paar Vanilla Erze ( imho sind es nur die ) als "Leckerlies" verteilt sind, die paar magischen Erze die auf der Karte verteilt sind wollten wir eigentlich auch drin lassen.

**Comment by BakermanLP** [comment]
Die magischen Erze habe ich mittlerweile in dem Pull Request deaktiviert. OK, aber die Vanilla Erze kann man ruhig als Leckerlies drinnen lassen. Ich lasse aber mal den Request bei FWG offen. Mal schauen, ob da was kommt.
