### ISSUE TITLE
Testen alternativer Compactor

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#92]
http://minecraft.curseforge.com/mc-mods/231549-compacter

Da der Mod autopackager schon Probleme gemacht hatte, hier eine aktuelle Alternative dazu. Die sollten wir mal testen. Kommt außerdem von einem IMHO guten Entwickler bdew, von dem auch ae2stuff, generators ... kommt.

**Comment by BakermanLP** [comment]
Bietet alles in allem nette Features, z.B. recursion, aber braucht deutlich mehr CPU Zeit und zieht Items nicht automatisch rein und nicht automatisch wieder raus.
Messung:
Non Operating:
- AutoPackager ~ 0,7us
- Compactor ~ 2 us
  Operating:
- Autopackager ~ 1,6 us
- Compactor ~ 5 us + rein und raus ziehen
  Deswegen erst mal weg mit dem Issue hier. Eventuell später nochmal testen, da es die erste Beta Version ist.

**Comment by Grambosch** [comment]
Testen kostet nix und wenn sich da noch was dran tut , weil ja Beta , dann ist es ja ne Alternative

**Comment by DerOliDE** [comment]
Hat sich da etwas an der Performance verbessert? 

Wenn das 2 bis 3 mal solang brauch, auch wenn es nur im Mikrosekunden-Bereich ist, würde ich es nicht unbedingt nehmen wollen.

**Comment by BakermanLP** [comment]
Bitte erst mal schliessen. Hat zwar Vorteile, aber muss nicht sein.
