### ISSUE TITLE
Deep Dark abschalten

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#93]
Ist nur ein Vorschlag, den Deep Dark abzuschalten. Wenn hier keine Erze erzeugt werden, und so ist eigentlich CoFH eingestellt, dann macht die Dimension keinen Sinn und "belastet" auch nur den Server.

**Comment by DerOliDE** [comment]
Deep Dark stand eventuell als Lobby zu Diskussion.

see: https://github.com/combak/ShatteredWorld/issues/52

**Comment by BakermanLP** [comment]
Das habe ich gesehen, aber mit all den Seiteneffekten dieser Dimension ... Ist das wirklich eine gute Idee? Könnte man da nicht "schöner" etwas mit FWG erzeugen und aufbauen? Mittels Forgeessentials ist ja eine andere Welt kein Problem.

**Comment by DerOliDE** [comment]
Gäbe alternativ noch The Last Millennium (Void Dimension), das wurde von Grambosch als Lobby vorgeschlagen.

**Comment by Grambosch** [comment]
Also ich halte das Deep Dark auch für "unnütz" in unserem Paket

**Comment by DerOliDE** [comment]
Mit dem deaktivieren des Deep Dark wird auch das Last Millenium deaktiviert aber eine Void Dimension für die Lobby können wir uns auch mit Multiworld erstellen.
