### ISSUE TITLE
[Diskussion] Eimer zusätzlich aus Aluminium machen lassen

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#95]
Wenigsten etwas Nutzen aus Aluminium ziehen.

**Comment by DerOliDE** [comment]
Hätte ich grundsätzlich nix dagegen, das könnte man vll. auch noch mit anderen Standard Eisen Produkten machen.

**Comment by BakermanLP** [comment]
Sonst liegt das nur sinnlos rum :)

**Comment by Grambosch** [comment]
SInnlos nicht , das braucht man im Alumit in den EnderIO Chassis aber gut wenn mans auch woanders braucht, Dafür

**Comment by krakel** [comment]
Dann müssen wir aber auch die Dropchance von Alu wieder erhöhen!
