### ISSUE TITLE
Pams pot und saucepan nur in der Schmelze herstellbar

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#96]
Wäre das was?

**Comment by DerOliDE** [comment]
Welche Vorlage/Gussform würde Dir da vorschweben?

**Comment by BakermanLP** [comment]
Hier die Vorschläge:
Saucepen : Casting Table -> unfired Clay Bucket -> molten Alu (288mB)
Pot: Casting Table -> fired Clay Bucket -> molten AluBrass (288mB)
Das sind die Werte und Rezepte aus Agrarian Skies 2 und die gefallen mir sehr gut.
