### ISSUE TITLE
Aluminium Ore (Dust, Sand und Gravel) in den Pulverizer und SagMill

### ISSUE THREAD

**Issue by BakermanLP** [combak/ShatteredWorld#98]
Die Aluminium Ore (Dust, Sand und Gravel) sollten in den Pulverizer und in die SagMill integriert werden mit dem Wert 1x Ore => 2x Dust ( => 2x Ingot ). Dann sind die gleich zu den anderen Ores aus Ex Nihilo zu bearbeiten.

**Comment by DerOliDE** [comment]
Steht alles noch aufm Plan aber z.Z. nicht möglich da TE nicht mit ModTweaker funktioniert, die arbeiten gerade an einem eigenen Custom Crafting Geraffel was noch nicht fertig ist, sprich z.Z. geht da überhaupt nix :-S

**Comment by DerOliDE** [comment]
Ich verlinke das mal der Übersicht halber zum Ore Processing ( https://github.com/combak/ShatteredWorld/issues/61 ) und mach das hier dicht, gehört ja zu der Thematik.
