### ISSUE TITLE
Forstday überdecht Rezept für Stoneslab

### ISSUE THREAD

**Issue by krakel** [combak/ShatteredWorld#99]
Das shapeless Rezept für Stone Grinder Coil Holder überdeckt das Rezept für Stoneslabs. Hier und da braucht man exakt diese Slabs. Bitte doch mal alle shapeless Rezepte überprüfen. Wo ist eigentlich das Repository für Forestday?

**Comment by DerOliDE** [comment]
Doppelpost: https://github.com/combak/ShatteredWorld/issues/36
